CeruleanCity_House1_Text_AnyInterestInBerries:: @ 8192F67
    .string "I concoct a variety of medicine\n"
    .string "from BERRY POWDER.\p"
    .string "Using good BERRY POWDER, I can\n"
    .string "make any kind of medicine.\p"
    .string "Now tell me, have you any interest\n"
    .string "in BERRIES?$"

CeruleanCity_House1_Text_HaveJustTheThing:: @ 8193003
    .string "Ah, good! For you, then, I have\n"
    .string "just the thing.$"

CeruleanCity_House1_Text_HaveANiceDay:: @ 8193033
    .string "Enjoy, and have a nice day.$"

CeruleanCity_House1_Text_TakeInterestInAllSortsOfThings:: @ 819325E
    .string "You have no interest in BERRIES?\p"
    .string "Young one, it's important to take an\n"
    .string "interest in all sorts of things.$"
