#ifndef GUARD_BATTLE_STRING_IDS_H
#define GUARD_BATTLE_STRING_IDS_H

#define STRINGID_INTROMSG        0
#define STRINGID_INTROSENDOUT    1
#define STRINGID_RETURNMON       2
#define STRINGID_SWITCHINMON     3
#define STRINGID_USEDMOVE        4
#define STRINGID_BATTLEEND       5
#define STRINGID_TRAINERSLIDE    6
#define STRINGID_TRAINERUSEDITEM 7
#define STRINGID_ITEMCATCHYTUNE  8
#define STRINGID_ITEMPLAYED      9

#define BATTLESTRINGS_ID_ADDER   10

// Atk = gBattlerAttacker, Def = gBattlerTarget, Pkmn = gBattleScripting.battler, Eff = gEffectBattler
// AtkTeam = "Your team" or "The opposing team" prefix of gBattlerAttacker
// DefTeam = "Your team" or "The opposing team" prefix of gBattlerTarget

#define STRINGID_TRAINER1LOSETEXT              (BATTLESTRINGS_ID_ADDER + 0)
#define STRINGID_PKMNGAINEDEXP                 (BATTLESTRINGS_ID_ADDER + 1)
#define STRINGID_PKMNGREWTOLV                  (BATTLESTRINGS_ID_ADDER + 2)
#define STRINGID_PKMNLEARNEDMOVE               (BATTLESTRINGS_ID_ADDER + 3)
#define STRINGID_TRYTOLEARNMOVE1               (BATTLESTRINGS_ID_ADDER + 4)
#define STRINGID_TRYTOLEARNMOVE2               (BATTLESTRINGS_ID_ADDER + 5)
#define STRINGID_TRYTOLEARNMOVE3               (BATTLESTRINGS_ID_ADDER + 6)
#define STRINGID_PKMNFORGOTMOVE                (BATTLESTRINGS_ID_ADDER + 7)
#define STRINGID_STOPLEARNINGMOVE              (BATTLESTRINGS_ID_ADDER + 8)
#define STRINGID_DIDNOTLEARNMOVE               (BATTLESTRINGS_ID_ADDER + 9)
#define STRINGID_ATKLEARNEDBUFF1               (BATTLESTRINGS_ID_ADDER + 10)
#define STRINGID_ATTACKMISSED                  (BATTLESTRINGS_ID_ADDER + 11)
#define STRINGID_DEFPROTECTEDITSELF            (BATTLESTRINGS_ID_ADDER + 12)
#define STRINGID_ITDOESNTAFFECT                (BATTLESTRINGS_ID_ADDER + 13)
#define STRINGID_PKMNFAINTED                   (BATTLESTRINGS_ID_ADDER + 14)
#define STRINGID_BUFF1DRANKALLMATCHAPKMNMADE   (BATTLESTRINGS_ID_ADDER + 15)
#define STRINGID_PLAYERGOTMONEY                (BATTLESTRINGS_ID_ADDER + 16)
#define STRINGID_PLAYERWHITEOUT                (BATTLESTRINGS_ID_ADDER + 17)
#define STRINGID_PLAYERPANICKEDANDLOST         (BATTLESTRINGS_ID_ADDER + 18)
#define STRINGID_PKMNPREVENTSESCAPEWITHABL     (BATTLESTRINGS_ID_ADDER + 19)
#define STRINGID_HITXTIMES                     (BATTLESTRINGS_ID_ADDER + 20)
#define STRINGID_EFFFELLASLEEP                 (BATTLESTRINGS_ID_ADDER + 21)
#define STRINGID_DEFALREADYASLEEP              (BATTLESTRINGS_ID_ADDER + 22)
#define STRINGID_DEFWASNTAFFECTED              (BATTLESTRINGS_ID_ADDER + 23)
#define STRINGID_EFFWASPOISONED                (BATTLESTRINGS_ID_ADDER + 24)
#define STRINGID_ATKHURTBYPOISON               (BATTLESTRINGS_ID_ADDER + 25)
#define STRINGID_DEFALREADYPOISONED            (BATTLESTRINGS_ID_ADDER + 26)
#define STRINGID_EFFBADLYPOISONED              (BATTLESTRINGS_ID_ADDER + 27)
#define STRINGID_DEFENERGYDRAINED              (BATTLESTRINGS_ID_ADDER + 28)
#define STRINGID_EFFWASBURNED                  (BATTLESTRINGS_ID_ADDER + 29)
#define STRINGID_ATKHURTBYBURN                 (BATTLESTRINGS_ID_ADDER + 30)
#define STRINGID_EFFWASFROZEN                  (BATTLESTRINGS_ID_ADDER + 31)
#define STRINGID_ATKISFROZEN                   (BATTLESTRINGS_ID_ADDER + 32)
#define STRINGID_BUFF1WASDEFROSTED             (BATTLESTRINGS_ID_ADDER + 33)
#define STRINGID_ATKDEFROSTEDBYCURRMOVE        (BATTLESTRINGS_ID_ADDER + 34)
#define STRINGID_EFFWASPARALYZED               (BATTLESTRINGS_ID_ADDER + 35)
#define STRINGID_ATKISPARALYZED                (BATTLESTRINGS_ID_ADDER + 36)
#define STRINGID_DEFISALREADYPARALYZED         (BATTLESTRINGS_ID_ADDER + 37)
#define STRINGID_EFFABLPREVENTSBURNS           (BATTLESTRINGS_ID_ADDER + 38)
#define STRINGID_EFFCUREDOFBUFF1               (BATTLESTRINGS_ID_ADDER + 39)
#define STRINGID_EFFWOKEUP                     (BATTLESTRINGS_ID_ADDER + 40)
#define STRINGID_ATKISCONFUSED                 (BATTLESTRINGS_ID_ADDER + 41)
#define STRINGID_ATKSNAPPEDOUTOFCONFUSION      (BATTLESTRINGS_ID_ADDER + 42)
#define STRINGID_EFFBECAMECONFUSED             (BATTLESTRINGS_ID_ADDER + 43)
#define STRINGID_DEFALREADYCONFUSED            (BATTLESTRINGS_ID_ADDER + 44)
#define STRINGID_DEFFELLINLOVE                 (BATTLESTRINGS_ID_ADDER + 45)
#define STRINGID_ATKISINLOVEWITHPKMN           (BATTLESTRINGS_ID_ADDER + 46)
#define STRINGID_ATKIMMOBILIZEDBYLOVE          (BATTLESTRINGS_ID_ADDER + 47)
#define STRINGID_PKMNTYPECHANGEDTOBUFF1        (BATTLESTRINGS_ID_ADDER + 48)
#define STRINGID_ATKFLINCHED                   (BATTLESTRINGS_ID_ADDER + 49)
#define STRINGID_DEFREGAINEDHEALTH             (BATTLESTRINGS_ID_ADDER + 50)
#define STRINGID_DEFHPFULL                     (BATTLESTRINGS_ID_ADDER + 51)
#define STRINGID_ATKTEAMCLOAKEDINMYSTICALVEIL  (BATTLESTRINGS_ID_ADDER + 52)
#define STRINGID_BUFF1RAISEDATKTEAMBUFF2       (BATTLESTRINGS_ID_ADDER + 53)
#define STRINGID_DEFTEAMSAFEGUARDPROTECTED     (BATTLESTRINGS_ID_ADDER + 54)
#define STRINGID_ATKTEAMSAFEGUARDEXPIRED       (BATTLESTRINGS_ID_ADDER + 55)
#define STRINGID_ATKTEAMBUFF1WOREOFF           (BATTLESTRINGS_ID_ADDER + 56)
#define STRINGID_DEFWENTTOSLEEP                (BATTLESTRINGS_ID_ADDER + 57)
#define STRINGID_DEFSLEPTHEALTHY               (BATTLESTRINGS_ID_ADDER + 58)
#define STRINGID_BUTITFAILED                   (BATTLESTRINGS_ID_ADDER + 59)
#define STRINGID_ATKWHIPPEDWHIRLWIND           (BATTLESTRINGS_ID_ADDER + 60)
#define STRINGID_ATKBECAMECLOAKEDINSUNLIGHT    (BATTLESTRINGS_ID_ADDER + 61)
#define STRINGID_ATKBURROWEDUNDERTHEGROUND     (BATTLESTRINGS_ID_ADDER + 62)
#define STRINGID_ATKTUCKEDINHEAD               (BATTLESTRINGS_ID_ADDER + 63)
#define STRINGID_ATKSPRANGUP                   (BATTLESTRINGS_ID_ADDER + 64)
#define STRINGID_ATKHIDUNDERWATER              (BATTLESTRINGS_ID_ADDER + 65)
#define STRINGID_ATKFLEWHIGH                   (BATTLESTRINGS_ID_ADDER + 66)
#define STRINGID_ATKABSORBEDLIGHT              (BATTLESTRINGS_ID_ADDER + 67)
#define STRINGID_EFFSQUEEZEDBYPKMN             (BATTLESTRINGS_ID_ADDER + 68)
#define STRINGID_EFFWRAPPEDBYPKMN              (BATTLESTRINGS_ID_ADDER + 69)
#define STRINGID_EFFTRAPPEDINVORTEX            (BATTLESTRINGS_ID_ADDER + 70)
#define STRINGID_PKMNCLAMPEDEFF                (BATTLESTRINGS_ID_ADDER + 71)
#define STRINGID_EFFTRAPPEDBYCURRMOVE          (BATTLESTRINGS_ID_ADDER + 72)
#define STRINGID_ATKHURTBYBUFF1                (BATTLESTRINGS_ID_ADDER + 73)
#define STRINGID_ATKFREEDFROMBUFF1             (BATTLESTRINGS_ID_ADDER + 74)
#define STRINGID_ATKKEPTANDCRASHED             (BATTLESTRINGS_ID_ADDER + 75)
#define STRINGID_ATKTEAMSHROUDEDINMIST         (BATTLESTRINGS_ID_ADDER + 76)
#define STRINGID_ATKGETTINGPUMPED              (BATTLESTRINGS_ID_ADDER + 77)
#define STRINGID_ATKHITWITHRECOIL              (BATTLESTRINGS_ID_ADDER + 78)
#define STRINGID_ATKBUFFETEDBYSANDSTORM        (BATTLESTRINGS_ID_ADDER + 79)
#define STRINGID_ATKPELTEDBYHAIL               (BATTLESTRINGS_ID_ADDER + 80)
#define STRINGID_DEFWASSEEDED                  (BATTLESTRINGS_ID_ADDER + 81)
#define STRINGID_DEFEVADEDATTACK               (BATTLESTRINGS_ID_ADDER + 82)
#define STRINGID_DEFSAPPEDBYLEECHSEED          (BATTLESTRINGS_ID_ADDER + 83)
#define STRINGID_ATKFASTASLEEP                 (BATTLESTRINGS_ID_ADDER + 84)
#define STRINGID_ATKWOKEUP                     (BATTLESTRINGS_ID_ADDER + 85)
#define STRINGID_ATKWOKEUPINUPROAR             (BATTLESTRINGS_ID_ADDER + 86)
#define STRINGID_DEFENDUREDHIT                 (BATTLESTRINGS_ID_ADDER + 87)
#define STRINGID_ONEHITKO                      (BATTLESTRINGS_ID_ADDER + 88)
#define STRINGID_ATKSTORINGENERGY              (BATTLESTRINGS_ID_ADDER + 89)
#define STRINGID_ATKUNLEASHEDENERGY            (BATTLESTRINGS_ID_ADDER + 90)
#define STRINGID_FIZZLESBUFF1TYPEATTACK        (BATTLESTRINGS_ID_ADDER + 91)
#define STRINGID_EVAPORATEBUFF1TYPEATTACK      (BATTLESTRINGS_ID_ADDER + 92)
#define STRINGID_ATKFATIGUECONFUSION           (BATTLESTRINGS_ID_ADDER + 93)
#define STRINGID_PLAYERPICKEDUPMONEY           (BATTLESTRINGS_ID_ADDER + 94)
#define STRINGID_DEFUNAFFECTED                 (BATTLESTRINGS_ID_ADDER + 95)
#define STRINGID_ATKTRANSFORMEDINTOBUFF1       (BATTLESTRINGS_ID_ADDER + 96)
#define STRINGID_ATKMADESUBSTITUTE             (BATTLESTRINGS_ID_ADDER + 97)
#define STRINGID_ATKHASSUBSTITUTE              (BATTLESTRINGS_ID_ADDER + 98)
#define STRINGID_TOOWEAKFORSUBSTITUTE          (BATTLESTRINGS_ID_ADDER + 99)
#define STRINGID_SUBSTITUTEDAMAGED             (BATTLESTRINGS_ID_ADDER + 100)
#define STRINGID_DEFSUBSTITUTEFADED            (BATTLESTRINGS_ID_ADDER + 101)
#define STRINGID_ATKMUSTRECHARGE               (BATTLESTRINGS_ID_ADDER + 102)
#define STRINGID_ATKTOOKAIMATDEF               (BATTLESTRINGS_ID_ADDER + 103)
#define STRINGID_DEFBUFF1WASDISABLED           (BATTLESTRINGS_ID_ADDER + 104)
#define STRINGID_ATKCURRMOVEISDISABLED         (BATTLESTRINGS_ID_ADDER + 105)
#define STRINGID_ATKDISABLEDNOMORE             (BATTLESTRINGS_ID_ADDER + 106)
#define STRINGID_DEFRECEIVEDENCORE             (BATTLESTRINGS_ID_ADDER + 107)
#define STRINGID_ATKENCOREENDED                (BATTLESTRINGS_ID_ADDER + 108)
#define STRINGID_ATKTRYINGTOTAKEFOEDOWN        (BATTLESTRINGS_ID_ADDER + 109)
#define STRINGID_DEFTOOKATTACKERWITHIT         (BATTLESTRINGS_ID_ADDER + 110)
#define STRINGID_REDUCEDPPOFDEFBUFF1BYBUFF2    (BATTLESTRINGS_ID_ADDER + 111)
#define STRINGID_PKMNSTOLEEFFLASTITEM          (BATTLESTRINGS_ID_ADDER + 112)
#define STRINGID_DEFCANNOLONGERESCAPE          (BATTLESTRINGS_ID_ADDER + 113)
#define STRINGID_DEFBEGANHAVINGNIGHTMARE       (BATTLESTRINGS_ID_ADDER + 114)
#define STRINGID_ATKLOCKEDINNIGHTMARE          (BATTLESTRINGS_ID_ADDER + 115)
#define STRINGID_SPIKESSCATTERED               (BATTLESTRINGS_ID_ADDER + 116)
#define STRINGID_DEFWASIDENTIFIED              (BATTLESTRINGS_ID_ADDER + 117)
#define STRINGID_ATKPERISHCOUNTFELLTOBUFF1     (BATTLESTRINGS_ID_ADDER + 118)
#define STRINGID_ATKBRACEDITSELF               (BATTLESTRINGS_ID_ADDER + 119)
#define STRINGID_MAGNITUDEBUFF1                (BATTLESTRINGS_ID_ADDER + 120)
#define STRINGID_PKMNCOPIEDBUFF1STATCHANGES    (BATTLESTRINGS_ID_ADDER + 121)
#define STRINGID_ATKFLEDFROMBATTLE             (BATTLESTRINGS_ID_ADDER + 122)
#define STRINGID_ATKFORESAWATTACK              (BATTLESTRINGS_ID_ADDER + 123)
#define STRINGID_ATKCHOSECURRMOVEASDESTINY     (BATTLESTRINGS_ID_ADDER + 124)
#define STRINGID_DEFTOOKTHECURRMOVEATTACK      (BATTLESTRINGS_ID_ADDER + 125)
#define STRINGID_ATKBECAMETHECENTERATTENTION   (BATTLESTRINGS_ID_ADDER + 126)
#define STRINGID_BUFF1TURNEDINTOCURRMOVE       (BATTLESTRINGS_ID_ADDER + 127)
#define STRINGID_ATKHASNOMOVESLEFT             (BATTLESTRINGS_ID_ADDER + 128)
#define STRINGID_DEFSUBJECTEDTOTORMENT         (BATTLESTRINGS_ID_ADDER + 129)
#define STRINGID_ATKCANTUSEMOVETORMENT         (BATTLESTRINGS_ID_ADDER + 130)
#define STRINGID_ATKTIGHTENINGFOCUS            (BATTLESTRINGS_ID_ADDER + 131)
#define STRINGID_DEFFELLFORTAUNT               (BATTLESTRINGS_ID_ADDER + 132)
#define STRINGID_ATKCANTUSECURRMOVETAUNT       (BATTLESTRINGS_ID_ADDER + 133)
#define STRINGID_ATKREADYTOHELPDEF             (BATTLESTRINGS_ID_ADDER + 134)
#define STRINGID_ATKCOPIEDDEFABL               (BATTLESTRINGS_ID_ADDER + 135)
#define STRINGID_BUFF1WISHCAMETRUE             (BATTLESTRINGS_ID_ADDER + 136)
#define STRINGID_ATKPLANTEDROOTS               (BATTLESTRINGS_ID_ADDER + 137)
#define STRINGID_ATKABSORBEDNUTRIENTS          (BATTLESTRINGS_ID_ADDER + 138)
#define STRINGID_DEFANCHOREDITSELF             (BATTLESTRINGS_ID_ADDER + 139)
#define STRINGID_DEFGREWDROWSY                 (BATTLESTRINGS_ID_ADDER + 140)
#define STRINGID_ATKSWAPPEDABILITIESWITHTARGET (BATTLESTRINGS_ID_ADDER + 141)
#define STRINGID_DEFBOUNCEDCURRMOVEBACK        (BATTLESTRINGS_ID_ADDER + 142)
#define STRINGID_ATKSHROUDEDWITHCURRMOVE       (BATTLESTRINGS_ID_ADDER + 143)
#define STRINGID_CRITICALHIT                   (BATTLESTRINGS_ID_ADDER + 144)
#define STRINGID_CRITICALHITONDEF              (BATTLESTRINGS_ID_ADDER + 145)
#define STRINGID_123POOF                       (BATTLESTRINGS_ID_ADDER + 146)
#define STRINGID_ANDELLIPSIS                   (BATTLESTRINGS_ID_ADDER + 147)
#define STRINGID_NOTVERYEFFECTIVE              (BATTLESTRINGS_ID_ADDER + 148)
#define STRINGID_NOTVERYEFFECTIVEONDEF         (BATTLESTRINGS_ID_ADDER + 149)
#define STRINGID_SUPEREFFECTIVE                (BATTLESTRINGS_ID_ADDER + 150)
#define STRINGID_SUPEREFFECTIVEONDEF           (BATTLESTRINGS_ID_ADDER + 151)
#define STRINGID_ATKISLOAFINGAROUND            (BATTLESTRINGS_ID_ADDER + 152)
#define STRINGID_ATKWONTOBEY                   (BATTLESTRINGS_ID_ADDER + 153)
#define STRINGID_ATKTURNEDAWAY                 (BATTLESTRINGS_ID_ADDER + 154)
#define STRINGID_ATKPRETENDNOTNOTICE           (BATTLESTRINGS_ID_ADDER + 155)
#define STRINGID_BUFF1ISNERVOUSTOEATBERRIES    (BATTLESTRINGS_ID_ADDER + 156)
#define STRINGID_EFFPREVENTSPOISONINGWITH      (BATTLESTRINGS_ID_ADDER + 157)
#define STRINGID_EMPTYSTRING                   (BATTLESTRINGS_ID_ADDER + 158)
#define STRINGID_ABOOSTED                      (BATTLESTRINGS_ID_ADDER + 159)
#define STRINGID_STARTEDTORAIN                 (BATTLESTRINGS_ID_ADDER + 160)
#define STRINGID_GOTAWAYSAFELY                 (BATTLESTRINGS_ID_ADDER + 161)
#define STRINGID_WILDBUFF1FLED                 (BATTLESTRINGS_ID_ADDER + 162)
#define STRINGID_DEFPROTECTEDBYDEFABL          (BATTLESTRINGS_ID_ADDER + 163)
#define STRINGID_PKMNABLPREVENTSATKUSECURRMOVE (BATTLESTRINGS_ID_ADDER + 164)
#define STRINGID_BUTNOTHINGHAPPENED            (BATTLESTRINGS_ID_ADDER + 165)
#define STRINGID_ITHURTITSELFINCONFUSION       (BATTLESTRINGS_ID_ADDER + 166)
#define STRINGID_THECURRMOVEFAILED             (BATTLESTRINGS_ID_ADDER + 167)
#define STRINGID_DEFHADHPRESTORED              (BATTLESTRINGS_ID_ADDER + 168)
#define STRINGID_POWEROFDEFBUFF1TYPEMOVESROSE  (BATTLESTRINGS_ID_ADDER + 169)
#define STRINGID_ITTRACEDDEFABL                (BATTLESTRINGS_ID_ADDER + 170)
#define STRINGID_ATKWASHURT                    (BATTLESTRINGS_ID_ADDER + 171)
#define STRINGID_MONHEARINGFLUTEAWOKE          (BATTLESTRINGS_ID_ADDER + 172)
#define STRINGID_GOTCHADEFCAUGHT               (BATTLESTRINGS_ID_ADDER + 173)
#define STRINGID_DEFDATAADDEDTODEX             (BATTLESTRINGS_ID_ADDER + 174)
#define STRINGID_PKMNTRANSFERREDSOMEONESPC     (BATTLESTRINGS_ID_ADDER + 175)
#define STRINGID_PKMNTRANSFERREDBILLSPC        (BATTLESTRINGS_ID_ADDER + 176)
#define STRINGID_PKMNBOXSOMEONESPCFULL         (BATTLESTRINGS_ID_ADDER + 177)
#define STRINGID_PKMNBOXBILLSPCFULL            (BATTLESTRINGS_ID_ADDER + 178)
#define STRINGID_OUTOFSAFARIBALLS              (BATTLESTRINGS_ID_ADDER + 179)
#define STRINGID_POKEMONBROKEFREE              (BATTLESTRINGS_ID_ADDER + 180)
#define STRINGID_ITAPPEAREDCAUGHT              (BATTLESTRINGS_ID_ADDER + 181)
#define STRINGID_AARGHALMOSTHADIT              (BATTLESTRINGS_ID_ADDER + 182)
#define STRINGID_SHOOTSOCLOSE                  (BATTLESTRINGS_ID_ADDER + 183)
#define STRINGID_TRAINERBLOCKEDBALL            (BATTLESTRINGS_ID_ADDER + 184)
#define STRINGID_DONTBEATHIEF                  (BATTLESTRINGS_ID_ADDER + 185)
#define STRINGID_ITDODGEDBALL                  (BATTLESTRINGS_ID_ADDER + 186)
#define STRINGID_PKMNWATCHINGCAREFULLY         (BATTLESTRINGS_ID_ADDER + 187)
#define STRINGID_PKMNANGRY                     (BATTLESTRINGS_ID_ADDER + 188)
#define STRINGID_PKMNEATING                    (BATTLESTRINGS_ID_ADDER + 189)
#define STRINGID_THREWROCK                     (BATTLESTRINGS_ID_ADDER + 190)
#define STRINGID_THREWBAIT                     (BATTLESTRINGS_ID_ADDER + 191)
#define STRINGID_YOUTHROWABALLNOWRIGHT         (BATTLESTRINGS_ID_ADDER + 192)
#define STRINGID_NORUNNINGFROMTRAINERS         (BATTLESTRINGS_ID_ADDER + 193)
#define STRINGID_CANTESCAPE                    (BATTLESTRINGS_ID_ADDER + 194)
#define STRINGID_DONTLEAVEBIRCH                (BATTLESTRINGS_ID_ADDER + 195)
#define STRINGID_ATKCANTESCAPE                 (BATTLESTRINGS_ID_ADDER + 196)
#define STRINGID_RAINCONTINUES                 (BATTLESTRINGS_ID_ADDER + 197)
#define STRINGID_RAINSTOPPED                   (BATTLESTRINGS_ID_ADDER + 198)
#define STRINGID_SUNLIGHTSTRONG                (BATTLESTRINGS_ID_ADDER + 199)
#define STRINGID_SUNLIGHTFADED                 (BATTLESTRINGS_ID_ADDER + 200)
#define STRINGID_SANDSTORMRAGES                (BATTLESTRINGS_ID_ADDER + 201)
#define STRINGID_SANDSTORMSUBSIDED             (BATTLESTRINGS_ID_ADDER + 202)
#define STRINGID_HAILCONTINUES                 (BATTLESTRINGS_ID_ADDER + 203)
#define STRINGID_HAILSTOPPED                   (BATTLESTRINGS_ID_ADDER + 204)
#define STRINGID_DEEPFOG                       (BATTLESTRINGS_ID_ADDER + 205)
#define STRINGID_FOGENDED                      (BATTLESTRINGS_ID_ADDER + 206)
#define STRINGID_STRONGWINDSCONTINUES          (BATTLESTRINGS_ID_ADDER + 207)
#define STRINGID_ASANDSTORMKICKEDUP            (BATTLESTRINGS_ID_ADDER + 208)
#define STRINGID_SUNLIGHTTURNEDHARSH           (BATTLESTRINGS_ID_ADDER + 209)
#define STRINGID_STARTEDHAIL                   (BATTLESTRINGS_ID_ADDER + 210)
#define STRINGID_COINSSCATTERED                (BATTLESTRINGS_ID_ADDER + 211)
#define STRINGID_GIVENICKNAMECAPTURED          (BATTLESTRINGS_ID_ADDER + 212)
#define STRINGID_BATTLERSSHAREDTHEIRPAIN       (BATTLESTRINGS_ID_ADDER + 213)
#define STRINGID_BELLCHIMED                    (BATTLESTRINGS_ID_ADDER + 214)
#define STRINGID_SOOTHINGAROMA                 (BATTLESTRINGS_ID_ADDER + 215)
#define STRINGID_STATCHANGESELIMINATED         (BATTLESTRINGS_ID_ADDER + 216)
#define STRINGID_ALLPOKEMONFAINTINTHREETURNS   (BATTLESTRINGS_ID_ADDER + 217)
#define STRINGID_NOPPLEFT                      (BATTLESTRINGS_ID_ADDER + 218)
#define STRINGID_BUTNOPPLEFT                   (BATTLESTRINGS_ID_ADDER + 219)
#define STRINGID_ATKIGNOREDORDERSASLEEP        (BATTLESTRINGS_ID_ADDER + 220)
#define STRINGID_ATKIGNOREDORDERS              (BATTLESTRINGS_ID_ADDER + 221)
#define STRINGID_ATKBEGANTONAP                 (BATTLESTRINGS_ID_ADDER + 222)
#define STRINGID_ENEMYABOUTTOSWITCHPKMN        (BATTLESTRINGS_ID_ADDER + 223)
#define STRINGID_LASTITEMALLOWSONLYCURRMOVE    (BATTLESTRINGS_ID_ADDER + 224)
#define STRINGID_ITEMSCANTBEUSEDNOW            (BATTLESTRINGS_ID_ADDER + 225)
#define STRINGID_BOXISFULL                     (BATTLESTRINGS_ID_ADDER + 226)
#define STRINGID_EFFSTATCHANGED                (BATTLESTRINGS_ID_ADDER + 227)
#define STRINGID_EFFSTATCANTCHANGE             (BATTLESTRINGS_ID_ADDER + 228)
#define STRINGID_DEFSTATSWONTCHANGE            (BATTLESTRINGS_ID_ADDER + 229)
#define STRINGID_EFFCUTHPMAXEDBUFF1            (BATTLESTRINGS_ID_ADDER + 230)
#define STRINGID_PKMNGOTFREEOFBUFF1BUFF2       (BATTLESTRINGS_ID_ADDER + 231)
#define STRINGID_PKMNSHEDLEECHSEED             (BATTLESTRINGS_ID_ADDER + 232)
#define STRINGID_PKMNBLEWAWAYHAZARDS           (BATTLESTRINGS_ID_ADDER + 233)
#define STRINGID_ATKBEGANCHARGINGPOWER         (BATTLESTRINGS_ID_ADDER + 234)
#define STRINGID_EFFPROTECTEDBYMIST            (BATTLESTRINGS_ID_ADDER + 235)
#define STRINGID_EFFPREVENTSSTATLOSS           (BATTLESTRINGS_ID_ADDER + 236)
#define STRINGID_EFFPREVENTSBUFF1LOSS          (BATTLESTRINGS_ID_ADDER + 237)
#define STRINGID_EFFRAGEBUILDING               (BATTLESTRINGS_ID_ADDER + 238)
#define STRINGID_DEFPREVENTEDFROMWORKING       (BATTLESTRINGS_ID_ADDER + 239)
#define STRINGID_EFFMAXEDSTAT                  (BATTLESTRINGS_ID_ADDER + 240)
#define STRINGID_DEFALREADYHASBURN             (BATTLESTRINGS_ID_ADDER + 241)
#define STRINGID_PKMNABLMADEITINEFFECTIVE      (BATTLESTRINGS_ID_ADDER + 242)
#define STRINGID_ATKSTOCKPILED                 (BATTLESTRINGS_ID_ADDER + 243)
#define STRINGID_ATKCANTSTOCKPILE              (BATTLESTRINGS_ID_ADDER + 244)
#define STRINGID_BUTFAILEDTOCURRMOVEATHING     (BATTLESTRINGS_ID_ADDER + 245)
#define STRINGID_ELECTRICITYPOWERWEAKENED      (BATTLESTRINGS_ID_ADDER + 246)
#define STRINGID_FIREPOWERWEAKENED             (BATTLESTRINGS_ID_ADDER + 247)
#define STRINGID_BUFF1EFFECTSWOREOFF           (BATTLESTRINGS_ID_ADDER + 248)
#define STRINGID_DEFTOOKTHEATTACK              (BATTLESTRINGS_ID_ADDER + 249)
#define STRINGID_USENEXTPKMN                   (BATTLESTRINGS_ID_ADDER + 250)
#define STRINGID_PLAYERDEFEATEDTRAINER1        (BATTLESTRINGS_ID_ADDER + 251)
#define STRINGID_TRAINER1MON1COMEBACK          (BATTLESTRINGS_ID_ADDER + 252)
#define STRINGID_TRAINER1WINTEXT               (BATTLESTRINGS_ID_ADDER + 253)
#define STRINGID_PLAYERLOSTAGAINSTENEMYTRAINER (BATTLESTRINGS_ID_ADDER + 254)
#define STRINGID_PLAYERPAIDPRIZEMONEY          (BATTLESTRINGS_ID_ADDER + 255)
#define STRINGID_PLAYERWHITEDOUT               (BATTLESTRINGS_ID_ADDER + 256)
#define STRINGID_ATKLOSTITSFOCUS               (BATTLESTRINGS_ID_ADDER + 257)
#define STRINGID_DEFWASDRAGGEDOUT              (BATTLESTRINGS_ID_ADDER + 258)
#define STRINGID_ITSUCKEDTHEDEFABL             (BATTLESTRINGS_ID_ADDER + 259)
#define STRINGID_THEWALLSHATTERED              (BATTLESTRINGS_ID_ADDER + 260)
#define STRINGID_ATKTOOSCAREDTOMOVE            (BATTLESTRINGS_ID_ADDER + 261)
#define STRINGID_GHOSTGETOUTGETOUT             (BATTLESTRINGS_ID_ADDER + 262)
#define STRINGID_LASTITEMUNVEILEDGHOST         (BATTLESTRINGS_ID_ADDER + 263)
#define STRINGID_THEGHOSTWASDEF                (BATTLESTRINGS_ID_ADDER + 264)
#define STRINGID_DEFPROTECTEDBYAROMATICVEIL    (BATTLESTRINGS_ID_ADDER + 265)
#define STRINGID_EFFSURROUNDEDINVEILOFPETALS   (BATTLESTRINGS_ID_ADDER + 266)
#define STRINGID_DEFSURROUNDEDINSWEETVEIL      (BATTLESTRINGS_ID_ADDER + 267)
#define STRINGID_HEAVYRAINLIFTED               (BATTLESTRINGS_ID_ADDER + 268)
#define STRINGID_EXTREMESUNLIGHTFADED          (BATTLESTRINGS_ID_ADDER + 269)
#define STRINGID_STRONGWINDSDISSIPATED         (BATTLESTRINGS_ID_ADDER + 270)
#define STRINGID_BUTNOEFFECT                   (BATTLESTRINGS_ID_ADDER + 271)
#define STRINGID_DEFHUNGONUSINGLASTITEM        (BATTLESTRINGS_ID_ADDER + 272)
#define STRINGID_PKMNABLBLOCKSCURRMOVE         (BATTLESTRINGS_ID_ADDER + 273)
#define STRINGID_ATKCUTHPANDLAIDCURSEONDEF     (BATTLESTRINGS_ID_ADDER + 274)
#define STRINGID_ATKAFFLICTEDBYCURSE           (BATTLESTRINGS_ID_ADDER + 275)
#define STRINGID_DEFSNATCHEDPKMNMOVE           (BATTLESTRINGS_ID_ADDER + 276)
#define STRINGID_WEATHEREFFECTSDISAPPEARED     (BATTLESTRINGS_ID_ADDER + 277)
#define STRINGID_PKMNBREAKSTHEMOLD             (BATTLESTRINGS_ID_ADDER + 278)
#define STRINGID_PKMNCANTGETGOING              (BATTLESTRINGS_ID_ADDER + 279)
#define STRINGID_PKMNRADIATINGABLAZINGAURA     (BATTLESTRINGS_ID_ADDER + 280)
#define STRINGID_PKMNRADIATINGABURSTINGAURA    (BATTLESTRINGS_ID_ADDER + 281)
#define STRINGID_PKMNRADIATINGADARKAURA        (BATTLESTRINGS_ID_ADDER + 282)
#define STRINGID_PKMNRADIATINGAFAIRYAURA       (BATTLESTRINGS_ID_ADDER + 283)
#define STRINGID_PKMNREVERSEDALLOTHERAURAS     (BATTLESTRINGS_ID_ADDER + 284)
#define STRINGID_PKMNISDROWSING                (BATTLESTRINGS_ID_ADDER + 285)
#define STRINGID_PKMNUNDERWENTTRANSFORMATION   (BATTLESTRINGS_ID_ADDER + 286)
#define STRINGID_PKMNSHUDDERED                 (BATTLESTRINGS_ID_ADDER + 287)
#define STRINGID_ALERTEDTOPKMNBUFF1            (BATTLESTRINGS_ID_ADDER + 288)
#define STRINGID_ALLSCREENSCLEANSED            (BATTLESTRINGS_ID_ADDER + 289)
#define STRINGID_PKMNSTATCHANGESWERERESET      (BATTLESTRINGS_ID_ADDER + 290)
#define STRINGID_PKMNHASTWOABILITIES           (BATTLESTRINGS_ID_ADDER + 291)
#define STRINGID_PKMNEXERTINGITSABL            (BATTLESTRINGS_ID_ADDER + 292)
#define STRINGID_PKMNGAINEDSTRENGTHFROMFALLEN  (BATTLESTRINGS_ID_ADDER + 293)
#define STRINGID_PKMNABLWEAKENEDBUFF1OFALL     (BATTLESTRINGS_ID_ADDER + 294)
#define STRINGID_PKMNILLUSIONOFF               (BATTLESTRINGS_ID_ADDER + 295)
#define STRINGID_ATKABILITYBECAMEABL           (BATTLESTRINGS_ID_ADDER + 296)
#define STRINGID_ATKGOTITSACTTOGETHER          (BATTLESTRINGS_ID_ADDER + 297)
#define STRINGID_DEFISTORMENTED                (BATTLESTRINGS_ID_ADDER + 298)
#define STRINGID_DISGUISESERVEDASDECOY         (BATTLESTRINGS_ID_ADDER + 299)
#define STRINGID_DEFDISGUISEBUSTED             (BATTLESTRINGS_ID_ADDER + 300)
#define STRINGID_GRAVITYINTENSIFIED            (BATTLESTRINGS_ID_ADDER + 301)
#define STRINGID_PKMNCANTSTAYINAIR             (BATTLESTRINGS_ID_ADDER + 302)
#define STRINGID_ATKCANTUSECURRMOVEINGRAVITY   (BATTLESTRINGS_ID_ADDER + 303)
#define STRINGID_GRAVITYRETURNEDTONORMAL       (BATTLESTRINGS_ID_ADDER + 304)
#define STRINGID_MOVECANTBESELECTED            (BATTLESTRINGS_ID_ADDER + 305)
#define STRINGID_ATKCANTUSESEALEDCURRMOVE      (BATTLESTRINGS_ID_ADDER + 306)
#define STRINGID_HEALINGWISHCAMETRUEFORPKMN    (BATTLESTRINGS_ID_ADDER + 307)
#define STRINGID_PKMNHURTBYSPIKES              (BATTLESTRINGS_ID_ADDER + 308)
#define STRINGID_EFFFELLFORTHEFEINT            (BATTLESTRINGS_ID_ADDER + 309)
#define STRINGID_TAILWINDBLEWBEHINDATKTEAM     (BATTLESTRINGS_ID_ADDER + 310)
#define STRINGID_ATKTEAMTAILWINDPETEREDOUT     (BATTLESTRINGS_ID_ADDER + 311)
#define STRINGID_CURRMOVECHARGEDPKMNPOWER      (BATTLESTRINGS_ID_ADDER + 312)
#define STRINGID_DEFCANTUSEITEMSANYMORE        (BATTLESTRINGS_ID_ADDER + 313)
#define STRINGID_ATKCANUSEITEMSAGAIN           (BATTLESTRINGS_ID_ADDER + 314)
#define STRINGID_ATKBUFF1WASHEALED             (BATTLESTRINGS_ID_ADDER + 315)
#define STRINGID_ATKABLALLOWSONLYCURRMOVE      (BATTLESTRINGS_ID_ADDER + 316)
#define STRINGID_ATKBECAMECHARGEDDUETOITSBOND  (BATTLESTRINGS_ID_ADDER + 317)
#define STRINGID_PKMNABLTRIGGERED              (BATTLESTRINGS_ID_ADDER + 318)
#define STRINGID_PKMNFORMEDASCHOOL             (BATTLESTRINGS_ID_ADDER + 319)
#define STRINGID_PKMNSTOPPEDSCHOOLING          (BATTLESTRINGS_ID_ADDER + 320)
#define STRINGID_PKMNABLACTIVATED              (BATTLESTRINGS_ID_ADDER + 321)
#define STRINGID_PKMNABLDEACTIVATED            (BATTLESTRINGS_ID_ADDER + 322)
#define STRINGID_PKMNTRANSFORMED               (BATTLESTRINGS_ID_ADDER + 323)
#define STRINGID_CHANGEDTOBLADEFORME           (BATTLESTRINGS_ID_ADDER + 324)
#define STRINGID_CHANGEDTOSHIELDFORME          (BATTLESTRINGS_ID_ADDER + 325)
#define STRINGID_ATKBECAMEASHBUFF1             (BATTLESTRINGS_ID_ADDER + 326)
#define STRINGID_DEFPREVENTEDFROMHEALING       (BATTLESTRINGS_ID_ADDER + 327)
#define STRINGID_ATKHEALBLOCKWOREOFF           (BATTLESTRINGS_ID_ADDER + 328)
#define STRINGID_ATKPREVENTEDFROMHEALING       (BATTLESTRINGS_ID_ADDER + 329)
#define STRINGID_ATKSWITCHEDBUFF1ANDBUFF2      (BATTLESTRINGS_ID_ADDER + 330)
#define STRINGID_DEFABILITYWASSUPPRESSED       (BATTLESTRINGS_ID_ADDER + 331)
#define STRINGID_CURRMOVESHIELDEDTEAMFROMCRITS (BATTLESTRINGS_ID_ADDER + 332)
#define STRINGID_HEAVYRAINFALL                 (BATTLESTRINGS_ID_ADDER + 333)
#define STRINGID_SUNLIGHTTURNEDEXTREMELYHARSH  (BATTLESTRINGS_ID_ADDER + 334)
#define STRINGID_STRONGWINDSPROTECTBUFF1TYPE   (BATTLESTRINGS_ID_ADDER + 335)
#define STRINGID_ATKSEALEDOPPONENTSMOVE        (BATTLESTRINGS_ID_ADDER + 336)
#define STRINGID_ATKWANTSTARGETTOBEARGRUDGE    (BATTLESTRINGS_ID_ADDER + 337)
#define STRINGID_ATKBUFF1LOSTPPDUETOGRUDGE     (BATTLESTRINGS_ID_ADDER + 338)
#define STRINGID_ATKWAITSFORTARGETTOMOVE       (BATTLESTRINGS_ID_ADDER + 339)
#define STRINGID_DEFABLDISABLEDATKCURRMOVE     (BATTLESTRINGS_ID_ADDER + 340)
#define STRINGID_ATKFRISKEDDEFFOUNDLASTITEM    (BATTLESTRINGS_ID_ADDER + 341)
#define STRINGID_BOTHPOKEMONPERISHINTHREETURNS (BATTLESTRINGS_ID_ADDER + 342)
#define STRINGID_ATKABLFILLEDTHEAREA           (BATTLESTRINGS_ID_ADDER + 343)
#define STRINGID_THEEFFECTSOFBUFF1WOREOFF      (BATTLESTRINGS_ID_ADDER + 344)
#define STRINGID_PKMNABLWASTAKENOVER           (BATTLESTRINGS_ID_ADDER + 345)
#define STRINGID_ITEMPKMNHADHPRESTORED         (BATTLESTRINGS_ID_ADDER + 346)
#define STRINGID_ITEMPKMNHADSTATUSHEALED       (BATTLESTRINGS_ID_ADDER + 347)
#define STRINGID_ITEMPKMNHADPPRESTORED         (BATTLESTRINGS_ID_ADDER + 348)
#define STRINGID_DEFABLCUREDPKMNBUFF1PROBLEM   (BATTLESTRINGS_ID_ADDER + 349)
#define STRINGID_PKMNABLCUREDITSBUFF1PROBLEM   (BATTLESTRINGS_ID_ADDER + 350)
#define STRINGID_ATKHARVESTEDITSLASTITEM       (BATTLESTRINGS_ID_ADDER + 351)
#define STRINGID_ATKFOUNDONELASTITEM           (BATTLESTRINGS_ID_ADDER + 352)
#define STRINGID_BUFF2CUREDOFITSBUFF1          (BATTLESTRINGS_ID_ADDER + 353)
#define STRINGID_DEFANCHORSITSELFWITHABL       (BATTLESTRINGS_ID_ADDER + 354)
#define STRINGID_DEFABLMADECURRMOVEINEFFECTIVE (BATTLESTRINGS_ID_ADDER + 355)
#define STRINGID_DEFAVOIDEDATTACK              (BATTLESTRINGS_ID_ADDER + 356)
#define STRINGID_EFFABLPREVENTSFLINCHING       (BATTLESTRINGS_ID_ADDER + 357)
#define STRINGID_EFFABLPREVENTSPARALYSIS       (BATTLESTRINGS_ID_ADDER + 358)
#define STRINGID_DEFABLPREVENTSCONFUSION       (BATTLESTRINGS_ID_ADDER + 359)
#define STRINGID_DEFPROTECTEDBYPASTELVEIL      (BATTLESTRINGS_ID_ADDER + 360)
#define STRINGID_ATKLOSTSOMEOFITSHP            (BATTLESTRINGS_ID_ADDER + 361)
#define STRINGID_ATKGAINSOMEOFITSHP            (BATTLESTRINGS_ID_ADDER + 362)
#define STRINGID_PKMNABLCUREDITSMENTALSTATE    (BATTLESTRINGS_ID_ADDER + 363)
#define STRINGID_PKMNABLCUREDITSCONFUSION      (BATTLESTRINGS_ID_ADDER + 364)
#define STRINGID_PKMNCUREDOFITSBUFF1           (BATTLESTRINGS_ID_ADDER + 365)
#define STRINGID_ATKSWITCHBUFF1ANDBUFF2CHANGES (BATTLESTRINGS_ID_ADDER + 366)
#define STRINGID_DEFACQUIREDDEFABL             (BATTLESTRINGS_ID_ADDER + 367)
#define STRINGID_POISONSPIKESSCATTERED         (BATTLESTRINGS_ID_ADDER + 368)
#define STRINGID_POISONSPIKESDISAPPEARED       (BATTLESTRINGS_ID_ADDER + 369)
#define STRINGID_STRONGWINDSWEAKENEDATTACK     (BATTLESTRINGS_ID_ADDER + 370)
#define STRINGID_PKMNTRANSFORMINCOMPLETEFORME  (BATTLESTRINGS_ID_ADDER + 371)
#define STRINGID_SENSETHEPRESENCEOFMANY        (BATTLESTRINGS_ID_ADDER + 372)
#define STRINGID_ATKSWITCHEDSTATCHANGES        (BATTLESTRINGS_ID_ADDER + 373)
#define STRINGID_PKMNKNOCKEDOFFEFFLASTITEM     (BATTLESTRINGS_ID_ADDER + 374)
#define STRINGID_DEFSHAREDITSLASTITEMWITHATK   (BATTLESTRINGS_ID_ADDER + 375)
#define STRINGID_EFFCALLEDFORHELP              (BATTLESTRINGS_ID_ADDER + 376)
#define STRINGID_EFFCALLEDITSALLY              (BATTLESTRINGS_ID_ADDER + 377)
#define STRINGID_ITSHELPDIDNTAPPEAR            (BATTLESTRINGS_ID_ADDER + 378)
#define STRINGID_PKMNAPPEARED                  (BATTLESTRINGS_ID_ADDER + 379)
#define STRINGID_ATKAURAFLAREDTOLIFE           (BATTLESTRINGS_ID_ADDER + 380)
#define STRINGID_THELASTITEMMAKESWILDNERVOUS   (BATTLESTRINGS_ID_ADDER + 381)

#define BATTLESTRINGS_COUNT                    (BATTLESTRINGS_ID_ADDER + 382)

// Strings related to items. Will be done later
#define STRINGID_PKMNFLEDUSINGITS 338
#define STRINGID_PKMNFLEDUSING 339
#define STRINGID_PKMNSITEMNORMALIZEDSTATUS 342
#define STRINGID_PKMNOBTAINEDX 358
#define STRINGID_PKMNOBTAINEDX2 359
#define STRINGID_PKMNOBTAINEDXYOBTAINEDZ 360
#define STRINGID_PKMNUPROARKEPTAWAKE 402
#define STRINGID_PKMNCAUSEDUPROAR 444
#define STRINGID_PKMNMAKINGUPROAR 329
#define STRINGID_PKMNCALMEDDOWN 330
#define STRINGID_PKMNCANTSLEEPINUPROAR 168
#define STRINGID_PKMNCANTSLEEPINUPROAR2 171
#define STRINGID_UPROARKEPTPKMNAWAKE 172
#define STRINGID_PKMNSTAYEDAWAKEUSING 173
#define STRINGID_PKMNSWITCHEDITEMS 184
#define STRINGID_PKMNCUTSATTACKWITH 205
#define STRINGID_PKMNSITEMCUREDPARALYSIS 291
#define STRINGID_PKMNSITEMCUREDPOISON 292
#define STRINGID_PKMNSITEMHEALEDBURN 293
#define STRINGID_PKMNSITEMDEFROSTEDIT 294
#define STRINGID_PKMNSITEMWOKEIT 295
#define STRINGID_PKMNSITEMSNAPPEDOUT 296
#define STRINGID_PKMNSITEMCUREDPROBLEM 297
#define STRINGID_PKMNSITEMRESTOREDHEALTH 298
#define STRINGID_PKMNSITEMRESTOREDPP 299
#define STRINGID_PKMNSITEMRESTOREDSTATUS 300
#define STRINGID_PKMNSITEMRESTOREDHPALITTLE 301

// gMissStringIds
#define B_MSG_MISSED        0
#define B_MSG_PROTECTED     1
#define B_MSG_AVOIDED_ATK   2
#define B_MSG_ABILITY_AVOID 3

// gGotDefrostedStringIds
#define B_MSG_DEFROST         0
#define B_MSG_DEFROST_BY_MOVE 1

// gStatusHealStringIds
#define B_MSG_WOKEUP_EFFECT 0
#define B_MSG_CURED_BUFF1   1

// gReflectLightScreenSafeguardStringIds
#define B_MSG_REFLECT_RAISED      0
#define B_MSG_SAFEGUARD_COVERED   1

// gSideStatusWoreOffStringIds
#define B_MSG_SIDE_STATUS_WORE_OFF 0
#define B_MSG_SAFEGUARD_WORE_OFF   1
#define B_MSG_TAILWIND_PETERED_OUT 2

// gRestUsedStringIds
#define B_MSG_WENT_TO_SLEEP 0
#define B_MSG_SLEPT_HEALTHY 1

// gFirstTurnOfTwoStringIds
#define B_MSG_WHIPPED_WHIRLWIND   0
#define B_MSG_CLOAKED_IN_SUNLIGHT 1
#define B_MSG_BURROWED_IN_GROUND  2
#define B_MSG_TUCKED_HEAD         3
#define B_MSG_SPRANG_UP           4
#define B_MSG_HID_UNDERWATER      5
#define B_MSG_FLEW_UP_HIGH        6
#define B_MSG_ABSORBED_LIGHT      7

// gSandstormHailDmgStringIds
#define B_MSG_DAMAGED_BY_SANDSTORM 0
#define B_MSG_DAMAGED_BY_HAIL      1

// gLeechSeedStringIds
#define B_MSG_SEEDED                  0
#define B_MSG_EVADED_ATTACK           1
#define B_MSG_LEECH_SEED_DOEST_AFFECT 2

// gWokeUpStringIds
#define B_MSG_WOKEUP        0
#define B_MSG_UPROAR_WOKEUP 1

// gPrimalWeatherBlocksAttackStringIds
#define B_MSG_FIZZLES_ATTACK   0
#define B_MSG_EVAPORATE_ATTACK 1

// gKOFailedStringIds
#define B_MSG_KO_MISSED  0
#define B_MSG_UNAFFECTED 1

// gSubsituteUsedStringIds
#define B_MSG_MADE_SUBSTITUTE        0
#define B_MSG_TOO_WEAK_TO_SUBSTITUTE 1
#define B_MSG_HAS_SUBSTITUTE         2

// gProtectLikeUsedStringIds
#define B_MSG_USED_PROTECT   0
#define B_MSG_BRACED_ITSELF  1

// gFutureMoveUsedStringIds
#define B_MSG_FORESAW_ATTACK   0
#define B_MSG_CHOSE_AS_DESTINY 1

// gInobedientStringIds
#define B_MSG_LOAFING_AROUND 0

// gFlashFireStringIds
#define B_MSG_FLASH_FIRE_BOOST       0
#define B_MSG_FLASH_FIRE_DONT_AFFECT 1

// gCaughtMonStringIds
#define B_MSG_TRANSFERRED_TO_SOMEONE_PC 0
#define B_MSG_TRANSFERRED_TO_BILL_PC    1
#define B_MSG_SOMEONE_PC_BOX_FULL       2
#define B_MSG_BILL_PC_BOX_FULL          3

// gSafariPokeblockResultStringIds
#define B_MSG_WATCHING_CAREFULLY 0
#define B_MSG_ANGRY              1
#define B_MSG_EATING             2

// gNoEscapeStringIds
#define B_MSG_CANT_ESCAPE            0
#define B_MSG_DONT_LEAVE_BIRTH       1
#define B_MSG_ABILITY_PREVENT_ESCAPE 2
#define B_MSG_ATK_CANT_ESCAPE        3

// gWeatherContinuesStringIds
#define B_MSG_RAIN_CONTINUES         0
#define B_MSG_RAIN_STOPPED           1
#define B_MSG_SUN_CONTINUES          2
#define B_MSG_SUN_STOPPED            3
#define B_MSG_SANDSTORM_CONTINUES    4
#define B_MSG_SANDSTORM_STOPPED      5
#define B_MSG_HAIL_CONTINUES         6
#define B_MSG_HAIL_STOPPED           7
#define B_MSG_FOG_CONTINUES          8
#define B_MSG_FOG_STOPPED            9
#define B_MSG_STRONG_WINDS_CONTINUES 10

// gWeatherStartsStringIds
#define B_MSG_STARTED_RAIN             0
#define B_MSG_WEATHER_MOVE_FAIL        1
#define B_MSG_SANDSTORM_UP             2
#define B_MSG_SUN_TURN_HARSH           3
#define B_MSG_STARTED_HAIL             4
#define B_MSG_DEEP_FOG                 5
#define B_MSG_HEAVY_RAIN               6
#define B_MSG_SUN_TURN_EXTREMELY_HARSH 7
#define B_MSG_STRONG_WINDS_PROTECTING  8

// gPartyStatusHealStringIds
#define B_MSG_BELL_CHIMED    0
#define B_MSG_SOOTHING_AROMA 1

// gCantUseItemStringIds
#define B_MSG_CANT_USE_ITEM 0
#define B_MSG_BOX_FULL      1

// gNotAllowedMoveStringIds
#define B_MSG_MOVE_DISABLED           0
#define B_MSG_NO_MOVES                1
#define B_MSG_MOVE_TORMENTED          2
#define B_MSG_MOVE_TAUNTED            3
#define B_MSG_MOVE_SEALED             4
#define B_MSG_MOVE_LOCKED_CHOICE_ITEM 5
#define B_MSG_MOVE_NO_PP              6
#define B_MSG_MOVE_IN_GRAVITY         7
#define B_MSG_MOVE_LOCKED_ABILITY     8
#define B_MSG_MOVE_HEAL_BLOCKED       9

// gStockpileUsedStringIds
#define B_MSG_ATK_STOCKPILED     0
#define B_MSG_ATK_CANT_STOCKPILE 1

// gSwallowFailStringIds
#define B_MSG_FAILED_TO_SWALLOW 0
#define B_MSG_SWALLOW_FULL_HP   1

// gFieldSportUsedStringIds
#define B_MSG_ELECTRICITY_WEAKENED 0
#define B_MSG_FIRE_WEAKENED        1

// gFieldStatusWoreOffStringIds
#define B_MSG_FIELD_EFFECTS_WORE_OFF 0
#define B_MSG_GRAVITY_NORMALIZED     1

// gSwitchInAbilitiesMsgStringIds
#define B_MSG_BREAKS_THE_MOLD          0
#define B_MSG_CANT_GET_GOING           1
#define B_MSG_BLAZING_AURA             2
#define B_MSG_NERVOUS_TO_EAT           3
#define B_MSG_BURSTING_AURA            4
#define B_MSG_DARK_AURA                5
#define B_MSG_FAIRY_AURA               6
#define B_MSG_REVERSED_AURAS           7
#define B_MSG_PKMN_DROWSING            8
#define B_MSG_UNDERWENT_TRANSFORMATION 9
#define B_MSG_SHUDDERED                10
#define B_MSG_ALERTED                  11
#define B_MSG_SCREENS_CLEANSED         12
#define B_MSG_STAT_CHANGES_RESETED     13
#define B_MSG_HAS_TWO_ABILITIES        14
#define B_MSG_EXERTING_ABILITY         15
#define B_MSG_GAINED_STRENGTH          16
#define B_MSG_WEAKENED_STAT            17
#define B_MSG_COPIED_STAT_CHANGES      18

// gHealingWishLunarDanceStringIds
#define B_MSG_HEALING_WISH_TRUE 0

// gEntryHazardsDmgStringIds
#define B_MSG_HURT_BY_SPIKES        0
#define B_MSG_ABSORBED_TOXIC_SPIKES 1

// gFormChangeAbilitiesStringIds
#define B_MSG_ABL_TRIGGERED       0
#define B_MSG_FORMED_SCHOOL       1
#define B_MSG_STOPPED_SCHOOLING   2
#define B_MSG_ABL_ACTIVATED       3
#define B_MSG_ABL_DEACTIVATED     4
#define B_MSG_TRANSFORMED         5
#define B_MSG_TRANS_INTO_COMPLETE 6

// gStanceChangeStringIds
#define B_MSG_CHANGED_TO_BLADE  0
#define B_MSG_CHANGED_TO_SHIELD 1

// gSplitSwapMovesStringIds
#define B_MSG_SWITCHED_STATS            0
#define B_MSG_SWITCHED_STAT_CHANGES     1
#define B_MSG_SWITCHED_ALL_STAT_CHANGES 2

// gStatusCureAbilityStringIds
#define B_MSG_CURED_ITS_PROBLEM     0
#define B_MSG_CURED_POKEMON_PROBLEM 1
#define B_MSG_CURED_MENTAL_STATE    2
#define B_MSG_CURED_CONFUSION       3
#define B_MSG_CURED_OF_ITS_PROBLEM  4

// gSosCallStringIds
#define B_MSG_CALLED_FOR_HELP 0
#define B_MSG_CALLED_ITS_ALLY 1

// gAdrenalineOrbUsedStringIds
#define B_MSG_MAKES_WILD_NERVOUS 0
#define B_MSG_BUT_HAD_NO_EFFECT  1

#endif // GUARD_BATTLE_STRING_IDS_H
