#ifndef GUARD_CONSTANTS_BATTLE_MOVE_EFFECTS_H
#define GUARD_CONSTANTS_BATTLE_MOVE_EFFECTS_H

// Move effects
#define EFFECT_HIT 0
#define EFFECT_MULTI_HIT 1
#define EFFECT_PAY_DAY 2
#define EFFECT_BURN_HIT 3
#define EFFECT_FREEZE_HIT 4
#define EFFECT_PARALYZE_HIT 5
#define EFFECT_OHKO 6
#define EFFECT_TWO_TURNS_ATTACK 7
#define EFFECT_USER_ATTACK_UP_2 8
#define EFFECT_ROAR 9
#define EFFECT_SEMI_INVULNERABLE 10
#define EFFECT_TRAP 11
#define EFFECT_FLINCH_HIT 12
#define EFFECT_RECOIL_IF_MISS 13
#define EFFECT_ACCURACY_DOWN 14
#define EFFECT_RAMPAGE 15
#define EFFECT_DEFENSE_DOWN 16
#define EFFECT_POISON_HIT 17
#define EFFECT_ATTACK_DOWN 18
#define EFFECT_SLEEP 19
#define EFFECT_CONFUSE 20
#define EFFECT_FIXED_DAMAGE 21
#define EFFECT_DISABLE 22
#define EFFECT_TARGET_SP_DEFENSE_DOWN_HIT 23
#define EFFECT_MIST 24
#define EFFECT_CONFUSE_HIT 25
#define EFFECT_TARGET_SPEED_DOWN_HIT 26
#define EFFECT_TARGET_ATTACK_DOWN_HIT 27
#define EFFECT_RECHARGE 28
#define EFFECT_LOW_KICK 29
#define EFFECT_COUNTER 30
#define EFFECT_LEVEL_DAMAGE 31
#define EFFECT_ABSORB 32
#define EFFECT_LEECH_SEED 33
#define EFFECT_GROWTH 34
#define EFFECT_SOLARBEAM 35
#define EFFECT_POISON 36
#define EFFECT_PARALYZE 37
#define EFFECT_SPEED_DOWN_2 38
#define EFFECT_TOXIC 39
#define EFFECT_ATTACK_UP 40
#define EFFECT_SPEED_UP_2 41
#define EFFECT_RAGE 42
#define EFFECT_TELEPORT 43
#define EFFECT_MIMIC 44
#define EFFECT_DEFENSE_DOWN_2 45
#define EFFECT_EVASION_UP 46
#define EFFECT_RESTORE_HP 47
#define EFFECT_DEFENSE_UP 48
#define EFFECT_MINIMIZE 49
#define EFFECT_DEFENSE_CURL 50
#define EFFECT_DEFENSE_UP_2 51
#define EFFECT_LIGHT_SCREEN 52
#define EFFECT_HAZE 53
#define EFFECT_REFLECT 54
#define EFFECT_FOCUS_ENERGY 55
#define EFFECT_BIDE 56
#define EFFECT_METRONOME 57
#define EFFECT_MIRROR_MOVE 58
#define EFFECT_EXPLOSION 59
#define EFFECT_SKULL_BASH 60
#define EFFECT_SPECIAL_DEFENSE_UP_2 61
#define EFFECT_DREAM_EATER 62
#define EFFECT_TRANSFORM 63
#define EFFECT_PSYWAVE 64
#define EFFECT_DO_NOTHING 65
#define EFFECT_REST 66
#define EFFECT_CONVERSION 67
#define EFFECT_TRI_ATTACK 68
#define EFFECT_SUPER_FANG 69
#define EFFECT_SUBSTITUTE 70
#define EFFECT_SKETCH 71
#define EFFECT_TRIPLE_KICK 72
#define EFFECT_THIEF 73
#define EFFECT_MEAN_LOOK 74
#define EFFECT_LOCK_ON 75
#define EFFECT_NIGHTMARE 76
#define EFFECT_SNORE 77
#define EFFECT_CURSE 78
#define EFFECT_FLAIL 79
#define EFFECT_CONVERSION_2 80
#define EFFECT_SPITE 81
#define EFFECT_PROTECT 82
#define EFFECT_BELLY_DRUM 83
#define EFFECT_TARGET_ACCURACY_DOWN_HIT 84
#define EFFECT_SPIKES 85
#define EFFECT_FORESIGHT 86
#define EFFECT_DESTINY_BOND 87
#define EFFECT_PERISH_SONG 88
#define EFFECT_SANDSTORM 89
#define EFFECT_ENDURE 90
#define EFFECT_ATTACK_DOWN_2 91
#define EFFECT_ROLLOUT 92
#define EFFECT_FALSE_SWIPE 93
#define EFFECT_SWAGGER 94
#define EFFECT_FURY_CUTTER 95
#define EFFECT_USER_DEFENSE_UP_HIT 96
#define EFFECT_ATTRACT 97
#define EFFECT_SLEEP_TALK 98
#define EFFECT_HEAL_BELL 99
#define EFFECT_RETURN 100
#define EFFECT_PRESENT 101
#define EFFECT_FRUSTRATION 102
#define EFFECT_SAFEGUARD 103
#define EFFECT_PAIN_SPLIT 104
#define EFFECT_MAGNITUDE 105
#define EFFECT_BATON_PASS 106
#define EFFECT_ENCORE 107
#define EFFECT_PURSUIT 108
#define EFFECT_RAPID_SPIN 109
#define EFFECT_EVASION_DOWN_2 110
#define EFFECT_TARGET_DEFENSE_DOWN_HIT 111
#define EFFECT_USER_ATTACK_UP_HIT 112
#define EFFECT_MORNING_SUN 113
#define EFFECT_HIDDEN_POWER 114
#define EFFECT_RAIN_DANCE 115
#define EFFECT_SUNNY_DAY 116
#define EFFECT_MIRROR_COAT 117
#define EFFECT_PSYCH_UP 118
#define EFFECT_ALL_STATS_UP_HIT 119
#define EFFECT_FUTURE_SIGHT 120
#define EFFECT_BEAT_UP 121
#define EFFECT_FAKE_OUT 122
#define EFFECT_UPROAR 123
#define EFFECT_STOCKPILE 124
#define EFFECT_SPIT_UP 125
#define EFFECT_SWALLOW 126
#define EFFECT_HAIL 127
#define EFFECT_TORMENT 128
#define EFFECT_FLATTER 129
#define EFFECT_WILL_O_WISP 130
#define EFFECT_MEMENTO 131
#define EFFECT_FACADE 132
#define EFFECT_FOCUS_PUNCH 133
#define EFFECT_SMELLING_SALT 134
#define EFFECT_FOLLOW_ME 135
#define EFFECT_NATURE_POWER 136
#define EFFECT_CHARGE 137
#define EFFECT_TAUNT 138
#define EFFECT_HELPING_HAND 139
#define EFFECT_TRICK 140
#define EFFECT_ROLE_PLAY 141
#define EFFECT_WISH 142
#define EFFECT_ASSIST 143
#define EFFECT_INGRAIN 144
#define EFFECT_SUPERPOWER 145
#define EFFECT_MAGIC_COAT 146
#define EFFECT_RECYCLE 147
#define EFFECT_REVENGE 148
#define EFFECT_BRICK_BREAK 149
#define EFFECT_YAWN 150
#define EFFECT_KNOCK_OFF 151
#define EFFECT_ENDEAVOR 152
#define EFFECT_ERUPTION 153
#define EFFECT_SKILL_SWAP 154
#define EFFECT_IMPRISON 155
#define EFFECT_REFRESH 156
#define EFFECT_GRUDGE 157
#define EFFECT_SNATCH 158
#define EFFECT_SECRET_POWER 159
#define EFFECT_CAMOUFLAGE 160
#define EFFECT_SPECIAL_ATTACK_UP_3 161
#define EFFECT_TARGET_SP_ATTACK_DOWN_HIT 162
#define EFFECT_MUD_SPORT 163
#define EFFECT_POISON_FANG 164
#define EFFECT_WEATHER_BALL 165
#define EFFECT_SPECIAL_DEFENSE_DOWN_2 166
#define EFFECT_OVERHEAT 167
#define EFFECT_TICKLE 168
#define EFFECT_COSMIC_POWER 169
#define EFFECT_HOWL 170
#define EFFECT_BULK_UP 171
#define EFFECT_WATER_SPORT 172
#define EFFECT_CALM_MIND 173
#define EFFECT_DRAGON_DANCE 174
#define EFFECT_ROOST 175
#define EFFECT_GRAVITY 176
#define EFFECT_MIRACLE_EYE 177
#define EFFECT_WAKE_UP_SLAP 178
#define EFFECT_USER_SPEED_DOWN_HIT 179
#define EFFECT_GYRO_BALL 180
#define EFFECT_HEALING_WISH 181
#define EFFECT_BRINE 182
#define EFFECT_NATURAL_GIFT 183
#define EFFECT_FEINT 184
#define EFFECT_BUG_BITE 185
#define EFFECT_TAILWIND 186
#define EFFECT_ACUPRESSURE 187
#define EFFECT_METAL_BURST 188
#define EFFECT_HIT_ESCAPE 189
#define EFFECT_CLOSE_COMBAT 190
#define EFFECT_PAYBACK 191
#define EFFECT_ASSURANCE 192
#define EFFECT_EMBARGO 193
#define EFFECT_FLING 194
#define EFFECT_PSYCHO_SHIFT 195
#define EFFECT_TRUMP_CARD 196
#define EFFECT_HEAL_BLOCK 197
#define EFFECT_WRING_OUT 198
#define EFFECT_POWER_TRICK 199
#define EFFECT_GASTRO_ACID 200
#define EFFECT_LUCKY_CHANT 201
#define EFFECT_ME_FIRST 202
#define EFFECT_COPYCAT 203
#define EFFECT_POWER_SWAP 204
#define EFFECT_GUARD_SWAP 205
#define EFFECT_PUNISHMENT 206
#define EFFECT_LAST_RESORT 207
#define EFFECT_SET_ABILITY 208
#define EFFECT_SUCKER_PUNCH 209
#define EFFECT_TOXIC_SPIKES 210

#define EFFECT_SPEED_UP 12
#define EFFECT_SPECIAL_ATTACK_UP 13
#define EFFECT_SPECIAL_DEFENSE_UP 14
#define EFFECT_ACCURACY_UP 15
#define EFFECT_SPEED_DOWN 20
#define EFFECT_SPECIAL_ATTACK_DOWN 21  // unused
#define EFFECT_SPECIAL_DEFENSE_DOWN 22  // unused
#define EFFECT_EVASION_DOWN 24
#define EFFECT_SPECIAL_ATTACK_UP_2 53
#define EFFECT_ACCURACY_UP_2 55
#define EFFECT_EVASION_UP_2 56
#define EFFECT_SPECIAL_ATTACK_DOWN_2 61
#define EFFECT_ACCURACY_DOWN_2 63
#define EFFECT_EVASION_DOWN_HIT 74
#define EFFECT_FLINCH_MINIMIZE_HIT 150
#define EFFECT_HEX                          217
#define EFFECT_ACROBATICS                   220
#define EFFECT_HEAT_CRASH                   221
#define EFFECT_STORED_POWER                 223
#define EFFECT_ELECTRO_BALL                 224
#define EFFECT_ECHOED_VOICE                 226
#define EFFECT_ROUND                        228
#define EFFECT_VENOSHOCK                    230
#define EFFECT_RETALIATE                    231
#define EFFECT_BULLDOZE                     232
#define EFFECT_FOUL_PLAY                    233
#define EFFECT_PSYSHOCK                     234
#define EFFECT_AQUA_RING                    240
#define EFFECT_TRICK_ROOM                   241
#define EFFECT_WONDER_ROOM                  242
#define EFFECT_MAGIC_ROOM                   243
#define EFFECT_MAGNET_RISE                  244
#define EFFECT_STEALTH_ROCK                 247
#define EFFECT_TELEKINESIS                  248
#define EFFECT_HEART_SWAP                   251
#define EFFECT_POWER_SPLIT                  252
#define EFFECT_GUARD_SPLIT                  253
#define EFFECT_STICKY_WEB                   254
#define EFFECT_SPECIAL_DEFENSE_DOWN_HIT_2   258
#define EFFECT_SIMPLE_BEAM                  259
#define EFFECT_ENTRAINMENT                  260
#define EFFECT_HEAL_PULSE                   261
#define EFFECT_QUASH                        262
#define EFFECT_ION_DELUGE                   263
#define EFFECT_FREEZE_DRY                   264
#define EFFECT_TOPSY_TURVY                  265
#define EFFECT_MISTY_TERRAIN                266
#define EFFECT_GRASSY_TERRAIN               267
#define EFFECT_ELECTRIC_TERRAIN             268
#define EFFECT_PSYCHIC_TERRAIN              269
#define EFFECT_ATTACK_ACCURACY_UP           270
#define EFFECT_ATTACK_SPATK_UP              271
#define EFFECT_HURRICANE                    272
#define EFFECT_TWO_TYPED_MOVE               273
#define EFFECT_SPEED_UP_HIT                 275
#define EFFECT_QUIVER_DANCE                 276
#define EFFECT_COIL                         277
#define EFFECT_ELECTRIFY                    278
#define EFFECT_SCALD                        279
#define EFFECT_REFLECT_TYPE                 280
#define EFFECT_SOAK                         281
#define EFFECT_FLINCH_STATUS                286
#define EFFECT_SHELL_SMASH                  288
#define EFFECT_SHIFT_GEAR                   289
#define EFFECT_DEFENSE_UP_3                 290
#define EFFECT_NOBLE_ROAR                   291
#define EFFECT_VENOM_DRENCH                 292
#define EFFECT_TOXIC_THREAD                 293
#define EFFECT_CLEAR_SMOG                   294
#define EFFECT_HIT_SWITCH_TARGET            295
#define EFFECT_FINAL_GAMBIT                 296
#define EFFECT_CHANGE_TYPE_ON_ITEM          297
#define EFFECT_AUTOTOMIZE                   298
#define EFFECT_DEFOG                        300
#define EFFECT_HIT_ENEMY_HEAL_ALLY          301
#define EFFECT_SMACK_DOWN                   302
#define EFFECT_SYNCHRONOISE                 303
#define EFFECT_FLAME_BURST                  306
#define EFFECT_AFTER_YOU                    307
#define EFFECT_BESTOW                       308
#define EFFECT_ROTOTILLER                   309
#define EFFECT_FLOWER_SHIELD                310
#define EFFECT_HIT_PREVENT_ESCAPE           311
#define EFFECT_SPEED_SWAP                   312
#define EFFECT_DEFENSE_UP2_HIT              313
#define EFFECT_REVELATION_DANCE             314
#define EFFECT_AURORA_VEIL                  315
#define EFFECT_THIRD_TYPE                   316
#define EFFECT_SPARKLING_ARIA               318
#define EFFECT_AROMATIC_MIST                320
#define EFFECT_POWDER                       321
#define EFFECT_SP_ATTACK_UP_HIT             322
#define EFFECT_BELCH                        323
#define EFFECT_PARTING_SHOT                 324
#define EFFECT_SPECTRAL_THIEF               325
#define EFFECT_V_CREATE                     326
#define EFFECT_MAT_BLOCK                    327
#define EFFECT_STOMPING_TANTRUM             328
#define EFFECT_CORE_ENFORCER                329
#define EFFECT_INSTRUCT                     330
#define EFFECT_THROAT_CHOP                  331
#define EFFECT_LASER_FOCUS                  332
#define EFFECT_MAGNETIC_FLUX                333
#define EFFECT_GEAR_UP                      334
#define EFFECT_INCINERATE                   335
#define EFFECT_STRENGTH_SAP                 337
#define EFFECT_MIND_BLOWN                   338
#define EFFECT_PURIFY                       339
#define EFFECT_BURN_UP                      340
#define EFFECT_SHORE_UP                     341
#define EFFECT_GEOMANCY                     342
#define EFFECT_FAIRY_LOCK                   343
#define EFFECT_ALLY_SWITCH                  344
#define EFFECT_RELIC_SONG                   345
#define EFFECT_ATTACKER_DEFENSE_DOWN_HIT    346
#define EFFECT_BODY_PRESS                   347
#define EFFECT_EERIE_SPELL                  348
#define EFFECT_JUNGLE_HEALING               349
#define EFFECT_COACHING                     350
#define EFFECT_LASH_OUT                     351
#define EFFECT_GRASSY_GLIDE                 352
#define EFFECT_REMOVE_TERRAIN               353
#define EFFECT_DYNAMAX_DOUBLE_DMG           354
#define EFFECT_DECORATE                     355
#define EFFECT_SNIPE_SHOT                   356
#define EFFECT_STUFF_CHEEKS                 358
#define EFFECT_GRAV_APPLE                   359
#define EFFECT_EVASION_UP_HIT               360
#define EFFECT_GLITZY_GLOW                  361
#define EFFECT_BADDY_BAD                    362
#define EFFECT_SAPPY_SEED                   363
#define EFFECT_FREEZY_FROST                 364
#define EFFECT_SPARKLY_SWIRL                365
#define EFFECT_PLASMA_FISTS                 366
#define EFFECT_HYPERSPACE_FURY              367
#define EFFECT_AURA_WHEEL                   368
#define EFFECT_PHOTON_GEYSER                369
#define EFFECT_SHELL_SIDE_ARM               370
#define EFFECT_TERRAIN_PULSE                371
#define EFFECT_JAW_LOCK                     372
#define EFFECT_NO_RETREAT                   373
#define EFFECT_TAR_SHOT                     374
#define EFFECT_POLTERGEIST                  375
#define EFFECT_OCTOLOCK                     376
#define EFFECT_CLANGOROUS_SOUL              377
#define EFFECT_BOLT_BEAK                    378
#define EFFECT_SKY_DROP                     379
#define EFFECT_EXPANDING_FORCE              380
#define EFFECT_SCALE_SHOT                   381
#define EFFECT_METEOR_BEAM                  382
#define EFFECT_RISING_VOLTAGE               383
#define EFFECT_BEAK_BLAST                   384
#define EFFECT_COURT_CHANGE                 385
#define EFFECT_STEEL_BEAM                   386
#define EFFECT_EXTREME_EVOBOOST             387
#define EFFECT_DAMAGE_SET_TERRAIN           388 // genesis supernova
#define EFFECT_DARK_VOID                    389
#define EFFECT_PLEDGE                       390
#define EFFECT_FUSION_COMBO                 393
#define EFFECT_ALWAYS_CRIT 397
#define EFFECT_CAPTIVATE 399
#define EFFECT_FELL_STINGER 400
#define EFFECT_PLACEHOLDER 0

// Move effect bytes
#define MOVE_EFFECT_NONE                0
#define MOVE_EFFECT_SLEEP               1
#define MOVE_EFFECT_POISON              2
#define MOVE_EFFECT_BURN                3
#define MOVE_EFFECT_FREEZE              4
#define MOVE_EFFECT_PARALYSIS           5
#define MOVE_EFFECT_TOXIC               6
#define MOVE_EFFECT_CONFUSION           7 // From here to up all prevented by Safeguard
#define MOVE_EFFECT_FLINCH              8
#define MOVE_EFFECT_TRI_ATTACK          9
#define MOVE_EFFECT_ATK_PLUS_1          10
#define MOVE_EFFECT_DEF_PLUS_1          11
#define MOVE_EFFECT_SPD_PLUS_1          12
#define MOVE_EFFECT_SP_ATK_PLUS_1       13
#define MOVE_EFFECT_SP_DEF_PLUS_1       14
#define MOVE_EFFECT_ACC_PLUS_1          15
#define MOVE_EFFECT_EVS_PLUS_1          16
#define MOVE_EFFECT_ATK_MINUS_1         17
#define MOVE_EFFECT_DEF_MINUS_1         18
#define MOVE_EFFECT_SPD_MINUS_1         19
#define MOVE_EFFECT_SP_ATK_MINUS_1      20
#define MOVE_EFFECT_SP_DEF_MINUS_1      21
#define MOVE_EFFECT_ACC_MINUS_1         22
#define MOVE_EFFECT_EVS_MINUS_1         23
#define MOVE_EFFECT_ATK_PLUS_2          24
#define MOVE_EFFECT_DEF_PLUS_2          25
#define MOVE_EFFECT_SPD_PLUS_2          26
#define MOVE_EFFECT_SP_ATK_PLUS_2       27
#define MOVE_EFFECT_SP_DEF_PLUS_2       28
#define MOVE_EFFECT_ACC_PLUS_2          29
#define MOVE_EFFECT_EVS_PLUS_2          30
#define MOVE_EFFECT_ATK_MINUS_2         31
#define MOVE_EFFECT_DEF_MINUS_2         32
#define MOVE_EFFECT_SPD_MINUS_2         33
#define MOVE_EFFECT_SP_ATK_MINUS_2      34
#define MOVE_EFFECT_SP_DEF_MINUS_2      35
#define MOVE_EFFECT_ACC_MINUS_2         36
#define MOVE_EFFECT_EVS_MINUS_2         37
#define MOVE_EFFECT_SECRET_POWER        38 // From here to up are all prevented by Shield Dust
#define MOVE_EFFECT_ALL_STATS_UP        39
#define MOVE_EFFECT_ATK_DEF_DOWN        40
#define MOVE_EFFECT_PAYDAY              41
#define MOVE_EFFECT_WRAP                42
#define MOVE_EFFECT_RECHARGE            43
#define MOVE_EFFECT_SMELLING_SALT       44
#define MOVE_EFFECT_THRASH              45
#define MOVE_EFFECT_STOCKPILE_WORE_OFF  46
#define MOVE_EFFECT_WAKE_UP_SLAP        47
#define MOVE_EFFECT_FEINT               48
#define MOVE_EFFECT_DEF_SPDEF_DOWN      49
// TODO
#define MOVE_EFFECT_STEAL_ITEM          50
#define MOVE_EFFECT_KNOCK_OFF           51
#define MOVE_EFFECT_UPROAR              52

// Z-Move effect bytes
#define Z_EFFECT_NONE                   0
#define Z_EFFECT_RESET_STATS            1
#define Z_EFFECT_ALL_STATS_UP_1         2
#define Z_EFFECT_BOOST_CRITS            3
#define Z_EFFECT_FOLLOW_ME              4
#define Z_EFFECT_CURSE                  5
#define Z_EFFECT_RECOVER_HP             6
#define Z_EFFECT_RESTORE_REPLACEMENT_HP 7
#define Z_EFFECT_ATK_UP_1               8
#define Z_EFFECT_DEF_UP_1               9
#define Z_EFFECT_SPD_UP_1               10
#define Z_EFFECT_SPATK_UP_1             11
#define Z_EFFECT_SPDEF_UP_1             12
#define Z_EFFECT_ACC_UP_1               13
#define Z_EFFECT_EVSN_UP_1              14
#define Z_EFFECT_ATK_UP_2               15
#define Z_EFFECT_DEF_UP_2               16
#define Z_EFFECT_SPD_UP_2               17
#define Z_EFFECT_SPATK_UP_2             18
#define Z_EFFECT_SPDEF_UP_2             19
#define Z_EFFECT_ACC_UP_2               20
#define Z_EFFECT_EVSN_UP_2              21
#define Z_EFFECT_ATK_UP_3               22
#define Z_EFFECT_DEF_UP_3               23
#define Z_EFFECT_SPD_UP_3               24
#define Z_EFFECT_SPATK_UP_3             25
#define Z_EFFECT_SPDEF_UP_3             26
#define Z_EFFECT_ACC_UP_3               27
#define Z_EFFECT_EVSN_UP_3              28

#endif  // GUARD_CONSTANTS_BATTLE_MOVE_EFFECTS_H
