#ifndef GUARD_CONSTANTS_BATTLE_MOVE_EFFECTS_H
#define GUARD_CONSTANTS_BATTLE_MOVE_EFFECTS_H

// Move effects
#define EFFECT_HIT 0
#define EFFECT_MULTI_HIT 1
#define EFFECT_PAY_DAY 2
#define EFFECT_BURN_HIT 3
#define EFFECT_FREEZE_HIT 4
#define EFFECT_PARALYZE_HIT 5
#define EFFECT_OHKO 6
#define EFFECT_TWO_TURNS_ATTACK 7
#define EFFECT_ATTACK_UP_2 8
#define EFFECT_ROAR 9
#define EFFECT_SEMI_INVULNERABLE 10
#define EFFECT_TRAP 11
#define EFFECT_FLINCH_HIT 12
#define EFFECT_RECOIL_IF_MISS 13
#define EFFECT_ACCURACY_DOWN 14
#define EFFECT_RECOIL_25 15
#define EFFECT_RAMPAGE 16
#define EFFECT_DOUBLE_EDGE 17
#define EFFECT_DEFENSE_DOWN 18
#define EFFECT_POISON_HIT 19
#define EFFECT_ATTACK_DOWN 20
#define EFFECT_SLEEP 21
#define EFFECT_CONFUSE 22
#define EFFECT_FIXED_DAMAGE 23
#define EFFECT_DISABLE 24
#define EFFECT_SPECIAL_DEFENSE_DOWN_HIT 25
#define EFFECT_MIST 26
#define EFFECT_CONFUSE_HIT 27
#define EFFECT_SPEED_DOWN_HIT 28
#define EFFECT_ATTACK_DOWN_HIT 29
#define EFFECT_RECHARGE 30
#define EFFECT_LOW_KICK 31
#define EFFECT_COUNTER 32
#define EFFECT_LEVEL_DAMAGE 33
#define EFFECT_ABSORB 34
#define EFFECT_LEECH_SEED 35
#define EFFECT_GROWTH 36
#define EFFECT_SOLARBEAM 37
#define EFFECT_POISON 38
#define EFFECT_PARALYZE 39
#define EFFECT_SPEED_DOWN_2 40
#define EFFECT_TOXIC 41
#define EFFECT_ATTACK_UP 42
#define EFFECT_SPEED_UP_2 43
#define EFFECT_RAGE 44
#define EFFECT_TELEPORT 45
#define EFFECT_MIMIC 46
#define EFFECT_DEFENSE_DOWN_2 47
#define EFFECT_EVASION_UP 48
#define EFFECT_RESTORE_HP 49
#define EFFECT_DEFENSE_UP 50
#define EFFECT_MINIMIZE 51
#define EFFECT_DEFENSE_CURL 52
#define EFFECT_DEFENSE_UP_2 53
#define EFFECT_LIGHT_SCREEN 54
#define EFFECT_HAZE 55
#define EFFECT_REFLECT 56
#define EFFECT_FOCUS_ENERGY 57
#define EFFECT_BIDE 58
#define EFFECT_METRONOME 59
#define EFFECT_MIRROR_MOVE 60
#define EFFECT_EXPLOSION 61
#define EFFECT_SKULL_BASH 62
#define EFFECT_SPECIAL_DEFENSE_UP_2 63
#define EFFECT_DREAM_EATER 64
#define EFFECT_TRANSFORM 65
#define EFFECT_PSYWAVE 66
#define EFFECT_DO_NOTHING 67
#define EFFECT_REST 68
#define EFFECT_CONVERSION 69
#define EFFECT_TRI_ATTACK 70
#define EFFECT_SUPER_FANG 71
#define EFFECT_SUBSTITUTE 72
#define EFFECT_RECOIL_HP_25 73
#define EFFECT_SKETCH 74
#define EFFECT_TRIPLE_KICK 75
#define EFFECT_THIEF 76
#define EFFECT_MEAN_LOOK 77
#define EFFECT_LOCK_ON 78
#define EFFECT_NIGHTMARE 79
#define EFFECT_SNORE 80
#define EFFECT_CURSE 81
#define EFFECT_FLAIL 82
#define EFFECT_CONVERSION_2 83
#define EFFECT_SPITE 84
#define EFFECT_PROTECT 85
#define EFFECT_BELLY_DRUM 86
#define EFFECT_ACCURACY_DOWN_HIT 87
#define EFFECT_SPIKES 88
#define EFFECT_FORESIGHT 89
#define EFFECT_DESTINY_BOND 90
#define EFFECT_PERISH_SONG 91
#define EFFECT_SANDSTORM 92
#define EFFECT_ENDURE 93
#define EFFECT_ATTACK_DOWN_2 94
#define EFFECT_ROLLOUT 95
#define EFFECT_FALSE_SWIPE 96
#define EFFECT_SWAGGER 97
#define EFFECT_FURY_CUTTER 98
#define EFFECT_DEFENSE_UP_HIT 99
#define EFFECT_ATTRACT 100
#define EFFECT_SLEEP_TALK 101

#define EFFECT_SPEED_UP 12
#define EFFECT_SPECIAL_ATTACK_UP 13
#define EFFECT_SPECIAL_DEFENSE_UP 14
#define EFFECT_ACCURACY_UP 15
#define EFFECT_SPEED_DOWN 20
#define EFFECT_SPECIAL_ATTACK_DOWN 21  // unused
#define EFFECT_SPECIAL_DEFENSE_DOWN 22  // unused
#define EFFECT_EVASION_DOWN 24
#define EFFECT_SPECIAL_ATTACK_UP_2 53
#define EFFECT_ACCURACY_UP_2 55
#define EFFECT_EVASION_UP_2 56
#define EFFECT_SPECIAL_ATTACK_DOWN_2 61
#define EFFECT_SPECIAL_DEFENSE_DOWN_2 62
#define EFFECT_ACCURACY_DOWN_2 63
#define EFFECT_EVASION_DOWN_2 64
#define EFFECT_DEFENSE_DOWN_HIT 69
#define EFFECT_SPECIAL_ATTACK_DOWN_HIT 71
#define EFFECT_EVASION_DOWN_HIT 74
#define EFFECT_VITAL_THROW 78
#define EFFECT_ENCORE 90
#define EFFECT_PAIN_SPLIT 91
#define EFFECT_HEAL_BELL 102
#define EFFECT_RETURN 121
#define EFFECT_PRESENT 122
#define EFFECT_FRUSTRATION 123
#define EFFECT_SAFEGUARD 124
#define EFFECT_MAGNITUDE 126
#define EFFECT_BATON_PASS 127
#define EFFECT_PURSUIT 128
#define EFFECT_RAPID_SPIN 129
#define EFFECT_MORNING_SUN 132
#define EFFECT_SYNTHESIS 133
#define EFFECT_MOONLIGHT 134
#define EFFECT_HIDDEN_POWER 135
#define EFFECT_RAIN_DANCE 136
#define EFFECT_SUNNY_DAY 137
#define EFFECT_ATTACK_UP_HIT 139
#define EFFECT_ALL_STATS_UP_HIT 140
#define EFFECT_PSYCH_UP 143
#define EFFECT_MIRROR_COAT 144
#define EFFECT_TWISTER 146
#define EFFECT_FUTURE_SIGHT 148
#define EFFECT_FLINCH_MINIMIZE_HIT 150
#define EFFECT_BEAT_UP 154
#define EFFECT_FAKE_OUT 158
#define EFFECT_UPROAR 159
#define EFFECT_STOCKPILE 160
#define EFFECT_SPIT_UP 161
#define EFFECT_SWALLOW 162
#define EFFECT_HAIL 164
#define EFFECT_TORMENT 165
#define EFFECT_FLATTER 166
#define EFFECT_WILL_O_WISP 167
#define EFFECT_MEMENTO 168
#define EFFECT_FACADE 169
#define EFFECT_FOCUS_PUNCH 170
#define EFFECT_SMELLINGSALT 171
#define EFFECT_FOLLOW_ME 172
#define EFFECT_NATURE_POWER 173
#define EFFECT_CHARGE 174
#define EFFECT_TAUNT 175
#define EFFECT_HELPING_HAND 176
#define EFFECT_TRICK 177
#define EFFECT_ROLE_PLAY 178
#define EFFECT_WISH 179
#define EFFECT_ASSIST 180
#define EFFECT_INGRAIN 181
#define EFFECT_SUPERPOWER 182
#define EFFECT_MAGIC_COAT 183
#define EFFECT_RECYCLE 184
#define EFFECT_REVENGE 185
#define EFFECT_BRICK_BREAK 186
#define EFFECT_YAWN 187
#define EFFECT_KNOCK_OFF 188
#define EFFECT_ENDEAVOR 189
#define EFFECT_ERUPTION 190
#define EFFECT_SKILL_SWAP 191
#define EFFECT_IMPRISON 192
#define EFFECT_REFRESH 193
#define EFFECT_GRUDGE 194
#define EFFECT_SNATCH 195
#define EFFECT_SECRET_POWER 197
#define EFFECT_TEETER_DANCE 199
#define EFFECT_MUD_SPORT 201
#define EFFECT_POISON_FANG 202
#define EFFECT_WEATHER_BALL 203
#define EFFECT_OVERHEAT 204
#define EFFECT_TICKLE 205
#define EFFECT_COSMIC_POWER 206
#define EFFECT_SKY_UPPERCUT 207
#define EFFECT_BULK_UP 208
#define EFFECT_WATER_SPORT 210
#define EFFECT_CALM_MIND 211
#define EFFECT_DRAGON_DANCE 212
#define EFFECT_CAMOUFLAGE 213
#define EFFECT_NATURAL_GIFT                 214
#define EFFECT_WAKE_UP_SLAP                 215
#define EFFECT_WRING_OUT                    216
#define EFFECT_HEX                          217
#define EFFECT_ASSURANCE                    218
#define EFFECT_TRUMP_CARD                   219
#define EFFECT_ACROBATICS                   220
#define EFFECT_HEAT_CRASH                   221
#define EFFECT_PUNISHMENT                   222
#define EFFECT_STORED_POWER                 223
#define EFFECT_ELECTRO_BALL                 224
#define EFFECT_GYRO_BALL                    225
#define EFFECT_ECHOED_VOICE                 226
#define EFFECT_PAYBACK                      227
#define EFFECT_ROUND                        228
#define EFFECT_BRINE                        229
#define EFFECT_VENOSHOCK                    230
#define EFFECT_RETALIATE                    231
#define EFFECT_BULLDOZE                     232
#define EFFECT_FOUL_PLAY                    233
#define EFFECT_PSYSHOCK                     234
#define EFFECT_ROOST                        235
#define EFFECT_GRAVITY                      236
#define EFFECT_MIRACLE_EYE                  237
#define EFFECT_TAILWIND                     238
#define EFFECT_EMBARGO                      239
#define EFFECT_AQUA_RING                    240
#define EFFECT_TRICK_ROOM                   241
#define EFFECT_WONDER_ROOM                  242
#define EFFECT_MAGIC_ROOM                   243
#define EFFECT_MAGNET_RISE                  244
#define EFFECT_TOXIC_SPIKES                 245
#define EFFECT_GASTRO_ACID                  246
#define EFFECT_STEALTH_ROCK                 247
#define EFFECT_TELEKINESIS                  248
#define EFFECT_POWER_SWAP                   249
#define EFFECT_GUARD_SWAP                   250
#define EFFECT_HEART_SWAP                   251
#define EFFECT_POWER_SPLIT                  252
#define EFFECT_GUARD_SPLIT                  253
#define EFFECT_STICKY_WEB                   254
#define EFFECT_METAL_BURST                  255
#define EFFECT_LUCKY_CHANT                  256
#define EFFECT_SUCKER_PUNCH                 257
#define EFFECT_SPECIAL_DEFENSE_DOWN_HIT_2   258
#define EFFECT_SIMPLE_BEAM                  259
#define EFFECT_ENTRAINMENT                  260
#define EFFECT_HEAL_PULSE                   261
#define EFFECT_QUASH                        262
#define EFFECT_ION_DELUGE                   263
#define EFFECT_FREEZE_DRY                   264
#define EFFECT_TOPSY_TURVY                  265
#define EFFECT_MISTY_TERRAIN                266
#define EFFECT_GRASSY_TERRAIN               267
#define EFFECT_ELECTRIC_TERRAIN             268
#define EFFECT_PSYCHIC_TERRAIN              269
#define EFFECT_ATTACK_ACCURACY_UP           270
#define EFFECT_ATTACK_SPATK_UP              271
#define EFFECT_HURRICANE                    272
#define EFFECT_TWO_TYPED_MOVE               273
#define EFFECT_ME_FIRST                     274
#define EFFECT_SPEED_UP_HIT                 275
#define EFFECT_QUIVER_DANCE                 276
#define EFFECT_COIL                         277
#define EFFECT_ELECTRIFY                    278
#define EFFECT_SCALD                        279
#define EFFECT_REFLECT_TYPE                 280
#define EFFECT_SOAK                         281
#define EFFECT_CLOSE_COMBAT                 283
#define EFFECT_LAST_RESORT                  284
#define EFFECT_RECOIL_33_STATUS             285
#define EFFECT_FLINCH_STATUS                286
#define EFFECT_RECOIL_50                    287
#define EFFECT_SHELL_SMASH                  288
#define EFFECT_SHIFT_GEAR                   289
#define EFFECT_DEFENSE_UP_3                 290
#define EFFECT_NOBLE_ROAR                   291
#define EFFECT_VENOM_DRENCH                 292
#define EFFECT_TOXIC_THREAD                 293
#define EFFECT_CLEAR_SMOG                   294
#define EFFECT_HIT_SWITCH_TARGET            295
#define EFFECT_FINAL_GAMBIT                 296
#define EFFECT_CHANGE_TYPE_ON_ITEM          297
#define EFFECT_AUTOTOMIZE                   298
#define EFFECT_COPYCAT                      299
#define EFFECT_DEFOG                        300
#define EFFECT_HIT_ENEMY_HEAL_ALLY          301
#define EFFECT_SMACK_DOWN                   302
#define EFFECT_SYNCHRONOISE                 303
#define EFFECT_PSYCHO_SHIFT                 304
#define EFFECT_POWER_TRICK                  305
#define EFFECT_FLAME_BURST                  306
#define EFFECT_AFTER_YOU                    307
#define EFFECT_BESTOW                       308
#define EFFECT_ROTOTILLER                   309
#define EFFECT_FLOWER_SHIELD                310
#define EFFECT_HIT_PREVENT_ESCAPE           311
#define EFFECT_SPEED_SWAP                   312
#define EFFECT_DEFENSE_UP2_HIT              313
#define EFFECT_REVELATION_DANCE             314
#define EFFECT_AURORA_VEIL                  315
#define EFFECT_THIRD_TYPE                   316
#define EFFECT_FEINT                        317
#define EFFECT_SPARKLING_ARIA               318
#define EFFECT_ACUPRESSURE                  319
#define EFFECT_AROMATIC_MIST                320
#define EFFECT_POWDER                       321
#define EFFECT_SP_ATTACK_UP_HIT             322
#define EFFECT_BELCH                        323
#define EFFECT_PARTING_SHOT                 324
#define EFFECT_SPECTRAL_THIEF               325
#define EFFECT_V_CREATE                     326
#define EFFECT_MAT_BLOCK                    327
#define EFFECT_STOMPING_TANTRUM             328
#define EFFECT_CORE_ENFORCER                329
#define EFFECT_INSTRUCT                     330
#define EFFECT_THROAT_CHOP                  331
#define EFFECT_LASER_FOCUS                  332
#define EFFECT_MAGNETIC_FLUX                333
#define EFFECT_GEAR_UP                      334
#define EFFECT_INCINERATE                   335
#define EFFECT_BUG_BITE                     336
#define EFFECT_STRENGTH_SAP                 337
#define EFFECT_MIND_BLOWN                   338
#define EFFECT_PURIFY                       339
#define EFFECT_BURN_UP                      340
#define EFFECT_SHORE_UP                     341
#define EFFECT_GEOMANCY                     342
#define EFFECT_FAIRY_LOCK                   343
#define EFFECT_ALLY_SWITCH                  344
#define EFFECT_RELIC_SONG                   345
#define EFFECT_ATTACKER_DEFENSE_DOWN_HIT    346
#define EFFECT_BODY_PRESS                   347
#define EFFECT_EERIE_SPELL                  348
#define EFFECT_JUNGLE_HEALING               349
#define EFFECT_COACHING                     350
#define EFFECT_LASH_OUT                     351
#define EFFECT_GRASSY_GLIDE                 352
#define EFFECT_REMOVE_TERRAIN               353
#define EFFECT_DYNAMAX_DOUBLE_DMG           354
#define EFFECT_DECORATE                     355
#define EFFECT_SNIPE_SHOT                   356
#define EFFECT_STUFF_CHEEKS                 358
#define EFFECT_GRAV_APPLE                   359
#define EFFECT_EVASION_UP_HIT               360
#define EFFECT_GLITZY_GLOW                  361
#define EFFECT_BADDY_BAD                    362
#define EFFECT_SAPPY_SEED                   363
#define EFFECT_FREEZY_FROST                 364
#define EFFECT_SPARKLY_SWIRL                365
#define EFFECT_PLASMA_FISTS                 366
#define EFFECT_HYPERSPACE_FURY              367
#define EFFECT_AURA_WHEEL                   368
#define EFFECT_PHOTON_GEYSER                369
#define EFFECT_SHELL_SIDE_ARM               370
#define EFFECT_TERRAIN_PULSE                371
#define EFFECT_JAW_LOCK                     372
#define EFFECT_NO_RETREAT                   373
#define EFFECT_TAR_SHOT                     374
#define EFFECT_POLTERGEIST                  375
#define EFFECT_OCTOLOCK                     376
#define EFFECT_CLANGOROUS_SOUL              377
#define EFFECT_BOLT_BEAK                    378
#define EFFECT_SKY_DROP                     379
#define EFFECT_EXPANDING_FORCE              380
#define EFFECT_SCALE_SHOT                   381
#define EFFECT_METEOR_BEAM                  382
#define EFFECT_RISING_VOLTAGE               383
#define EFFECT_BEAK_BLAST                   384
#define EFFECT_COURT_CHANGE                 385
#define EFFECT_STEEL_BEAM                   386
#define EFFECT_EXTREME_EVOBOOST             387
#define EFFECT_DAMAGE_SET_TERRAIN           388 // genesis supernova
#define EFFECT_DARK_VOID                    389
#define EFFECT_PLEDGE                       390
#define EFFECT_FLING                        391
#define EFFECT_SPECIAL_ATTACK_UP_3          392
#define EFFECT_FUSION_COMBO                 393
#define EFFECT_HEAL_BLOCK                   394
#define EFFECT_HAMMER_ARM 396
#define EFFECT_ALWAYS_CRIT 397
#define EFFECT_HEALING_WISH 398
#define EFFECT_CAPTIVATE 399
#define EFFECT_FELL_STINGER 400
#define EFFECT_WORRY_SEED 401
#define EFFECT_HIT_ESCAPE 402
#define EFFECT_PLACEHOLDER 0

// Move effect bytes
#define MOVE_EFFECT_NONE                0
#define MOVE_EFFECT_SLEEP               1
#define MOVE_EFFECT_POISON              2
#define MOVE_EFFECT_BURN                3
#define MOVE_EFFECT_FREEZE              4
#define MOVE_EFFECT_PARALYSIS           5
#define MOVE_EFFECT_TOXIC               6
#define MOVE_EFFECT_CONFUSION           7 // From here to up all prevented by Safeguard
#define MOVE_EFFECT_FLINCH              8
#define MOVE_EFFECT_TRI_ATTACK          9 // From here to up are all prevented by Shield Dust
#define MOVE_EFFECT_UPROAR              10
#define MOVE_EFFECT_PAYDAY              11
#define MOVE_EFFECT_CHARGING            12 // Unused
#define MOVE_EFFECT_WRAP                13
#define MOVE_EFFECT_INCINERATE          14 // TODO
#define MOVE_EFFECT_ATK_PLUS_1          15
#define MOVE_EFFECT_DEF_PLUS_1          16
#define MOVE_EFFECT_SPD_PLUS_1          17
#define MOVE_EFFECT_SP_ATK_PLUS_1       18
#define MOVE_EFFECT_SP_DEF_PLUS_1       19
#define MOVE_EFFECT_ACC_PLUS_1          20
#define MOVE_EFFECT_EVS_PLUS_1          21
#define MOVE_EFFECT_ATK_MINUS_1         22
#define MOVE_EFFECT_DEF_MINUS_1         23
#define MOVE_EFFECT_SPD_MINUS_1         24
#define MOVE_EFFECT_SP_ATK_MINUS_1      25
#define MOVE_EFFECT_SP_DEF_MINUS_1      26
#define MOVE_EFFECT_ACC_MINUS_1         27
#define MOVE_EFFECT_EVS_MINUS_1         28
#define MOVE_EFFECT_RECHARGE            29
#define MOVE_EFFECT_RAGE                30 // Unused
#define MOVE_EFFECT_STEAL_ITEM          31
#define MOVE_EFFECT_PREVENT_ESCAPE      32 // Unused
#define MOVE_EFFECT_NIGHTMARE           33 // Unused
#define MOVE_EFFECT_ALL_STATS_UP        34
#define MOVE_EFFECT_RAPIDSPIN           35
#define MOVE_EFFECT_REMOVE_PARALYSIS    36
#define MOVE_EFFECT_ATK_DEF_DOWN        37
#define MOVE_EFFECT_BUG_BITE            38 // TODO
#define MOVE_EFFECT_ATK_PLUS_2          39
#define MOVE_EFFECT_DEF_PLUS_2          40
#define MOVE_EFFECT_SPD_PLUS_2          41
#define MOVE_EFFECT_SP_ATK_PLUS_2       42
#define MOVE_EFFECT_SP_DEF_PLUS_2       43
#define MOVE_EFFECT_ACC_PLUS_2          44
#define MOVE_EFFECT_EVS_PLUS_2          45
#define MOVE_EFFECT_ATK_MINUS_2         46
#define MOVE_EFFECT_DEF_MINUS_2         47
#define MOVE_EFFECT_SPD_MINUS_2         48
#define MOVE_EFFECT_SP_ATK_MINUS_2      49
#define MOVE_EFFECT_SP_DEF_MINUS_2      50
#define MOVE_EFFECT_ACC_MINUS_2         51
#define MOVE_EFFECT_EVS_MINUS_2         52
#define MOVE_EFFECT_THRASH              53
#define MOVE_EFFECT_KNOCK_OFF           54
#define MOVE_EFFECT_FEINT               55

#define MOVE_EFFECT_AFFECTS_USER        0x40
#define MOVE_EFFECT_CERTAIN             0x80

// Z-Move effect bytes
#define Z_EFFECT_NONE                   0
#define Z_EFFECT_RESET_STATS            1
#define Z_EFFECT_ALL_STATS_UP_1         2
#define Z_EFFECT_BOOST_CRITS            3
#define Z_EFFECT_FOLLOW_ME              4
#define Z_EFFECT_CURSE                  5
#define Z_EFFECT_RECOVER_HP             6
#define Z_EFFECT_RESTORE_REPLACEMENT_HP 7
#define Z_EFFECT_ATK_UP_1               8
#define Z_EFFECT_DEF_UP_1               9
#define Z_EFFECT_SPD_UP_1               10
#define Z_EFFECT_SPATK_UP_1             11
#define Z_EFFECT_SPDEF_UP_1             12
#define Z_EFFECT_ACC_UP_1               13
#define Z_EFFECT_EVSN_UP_1              14
#define Z_EFFECT_ATK_UP_2               15
#define Z_EFFECT_DEF_UP_2               16
#define Z_EFFECT_SPD_UP_2               17
#define Z_EFFECT_SPATK_UP_2             18
#define Z_EFFECT_SPDEF_UP_2             19
#define Z_EFFECT_ACC_UP_2               20
#define Z_EFFECT_EVSN_UP_2              21
#define Z_EFFECT_ATK_UP_3               22
#define Z_EFFECT_DEF_UP_3               23
#define Z_EFFECT_SPD_UP_3               24
#define Z_EFFECT_SPATK_UP_3             25
#define Z_EFFECT_SPDEF_UP_3             26
#define Z_EFFECT_ACC_UP_3               27
#define Z_EFFECT_EVSN_UP_3              28

#endif  // GUARD_CONSTANTS_BATTLE_MOVE_EFFECTS_H
