#ifndef GUARD_CONSTANTS_BATTLE_QUEUED_EFFECTS_H
#define GUARD_CONSTANTS_BATTLE_QUEUED_EFFECTS_H

// Per battler queued effects
#define B_BATTLER_QUEUED_FUTURE_SIGHT 0
#define B_BATTLER_QUEUED_WISH         1
#define B_BATTLER_QUEUED_COUNT        2

// Per side queued effects
#define B_SIDE_QUEUED_SEA_OF_FIRE     0
#define B_SIDE_QUEUED_GMAX_CANNONADE  1
#define B_SIDE_QUEUED_GMAX_VINE_LASH  2
#define B_SIDE_QUEUED_GMAX_VOLCALITH  3
#define B_SIDE_QUEUED_GMAX_WILDFIRE   4
#define B_SIDE_QUEUED_GMAX_STEELSURGE 5
#define B_SIDE_QUEUED_SPIKES          6
#define B_SIDE_QUEUED_TOXIC_SPIKES    7
#define B_SIDE_QUEUED_STEALTH_ROCK    8
#define B_SIDE_QUEUED_STICKY_WEB      9
#define B_SIDE_QUEUED_COUNT           10

#endif // GUARD_CONSTANTS_BATTLE_QUEUED_EFFECTS_H
