#ifndef GUARD_BATTLE_STRING_IDS_H
#define GUARD_BATTLE_STRING_IDS_H

#define STRINGID_INTROMSG        0
#define STRINGID_INTROSENDOUT    1
#define STRINGID_RETURNMON       2
#define STRINGID_SWITCHINMON     3
#define STRINGID_USEDMOVE        4
#define STRINGID_BATTLEEND       5
#define STRINGID_TRAINERSLIDE    6
#define STRINGID_TRAINERUSEDITEM 7
#define STRINGID_ITEMCATCHYTUNE  8
#define STRINGID_ITEMPLAYED      9

#define BATTLESTRINGS_ID_ADDER   10

// Atk = gBattlerAttacker, Def = gBattlerTarget, Pkmn = gBattleScripting.battler, Eff = gEffectBattler
// AtkTeam = "Your team" or "The opposing team" prefix of gBattlerAttacker
// DefTeam = "Your team" or "The opposing team" prefix of gBattlerTarget

#define STRINGID_TRAINER1LOSETEXT              (BATTLESTRINGS_ID_ADDER + 0)
#define STRINGID_PKMNGAINEDEXP                 (BATTLESTRINGS_ID_ADDER + 1)
#define STRINGID_PKMNGREWTOLV                  (BATTLESTRINGS_ID_ADDER + 2)
#define STRINGID_PKMNLEARNEDMOVE               (BATTLESTRINGS_ID_ADDER + 3)
#define STRINGID_TRYTOLEARNMOVE1               (BATTLESTRINGS_ID_ADDER + 4)
#define STRINGID_TRYTOLEARNMOVE2               (BATTLESTRINGS_ID_ADDER + 5)
#define STRINGID_TRYTOLEARNMOVE3               (BATTLESTRINGS_ID_ADDER + 6)
#define STRINGID_PKMNFORGOTMOVE                (BATTLESTRINGS_ID_ADDER + 7)
#define STRINGID_STOPLEARNINGMOVE              (BATTLESTRINGS_ID_ADDER + 8)
#define STRINGID_DIDNOTLEARNMOVE               (BATTLESTRINGS_ID_ADDER + 9)
#define STRINGID_ATKLEARNEDBUFF1               (BATTLESTRINGS_ID_ADDER + 10)
#define STRINGID_ATTACKMISSED                  (BATTLESTRINGS_ID_ADDER + 11)
#define STRINGID_DEFPROTECTEDITSELF            (BATTLESTRINGS_ID_ADDER + 12)
#define STRINGID_ITDOESNTAFFECT                (BATTLESTRINGS_ID_ADDER + 13)
#define STRINGID_ATKFAINTED                    (BATTLESTRINGS_ID_ADDER + 14)
#define STRINGID_DEFFAINTED                    (BATTLESTRINGS_ID_ADDER + 15)
#define STRINGID_PLAYERGOTMONEY                (BATTLESTRINGS_ID_ADDER + 16)
#define STRINGID_PLAYERWHITEOUT                (BATTLESTRINGS_ID_ADDER + 17)
#define STRINGID_PLAYERPANICKEDANDLOST         (BATTLESTRINGS_ID_ADDER + 18)
#define STRINGID_PKMNPREVENTSESCAPEWITHABL     (BATTLESTRINGS_ID_ADDER + 19)
#define STRINGID_HITXTIMES                     (BATTLESTRINGS_ID_ADDER + 20)
#define STRINGID_EFFFELLASLEEP                 (BATTLESTRINGS_ID_ADDER + 21)
#define STRINGID_DEFALREADYASLEEP              (BATTLESTRINGS_ID_ADDER + 22)
#define STRINGID_DEFWASNTAFFECTED              (BATTLESTRINGS_ID_ADDER + 23)
#define STRINGID_EFFWASPOISONED                (BATTLESTRINGS_ID_ADDER + 24)
#define STRINGID_ATKHURTBYPOISON               (BATTLESTRINGS_ID_ADDER + 25)
#define STRINGID_DEFALREADYPOISONED            (BATTLESTRINGS_ID_ADDER + 26)
#define STRINGID_EFFBADLYPOISONED              (BATTLESTRINGS_ID_ADDER + 27)
#define STRINGID_DEFENERGYDRAINED              (BATTLESTRINGS_ID_ADDER + 28)
#define STRINGID_EFFWASBURNED                  (BATTLESTRINGS_ID_ADDER + 29)
#define STRINGID_ATKHURTBYBURN                 (BATTLESTRINGS_ID_ADDER + 30)
#define STRINGID_EFFWASFROZEN                  (BATTLESTRINGS_ID_ADDER + 31)
#define STRINGID_ATKISFROZEN                   (BATTLESTRINGS_ID_ADDER + 32)
#define STRINGID_BUFF1WASDEFROSTED             (BATTLESTRINGS_ID_ADDER + 33)
#define STRINGID_ATKDEFROSTEDBYCURRMOVE        (BATTLESTRINGS_ID_ADDER + 34)
#define STRINGID_EFFWASPARALYZED               (BATTLESTRINGS_ID_ADDER + 35)
#define STRINGID_ATKISPARALYZED                (BATTLESTRINGS_ID_ADDER + 36)
#define STRINGID_DEFISALREADYPARALYZED         (BATTLESTRINGS_ID_ADDER + 37)
#define STRINGID_EFFABLPREVENTSBURNS           (BATTLESTRINGS_ID_ADDER + 38)
#define STRINGID_EFFCUREDOFBUFF1               (BATTLESTRINGS_ID_ADDER + 39)
#define STRINGID_EFFWOKEUP                     (BATTLESTRINGS_ID_ADDER + 40)
#define STRINGID_ATKISCONFUSED                 (BATTLESTRINGS_ID_ADDER + 41)
#define STRINGID_ATKSNAPPEDOUTOFCONFUSION      (BATTLESTRINGS_ID_ADDER + 42)
#define STRINGID_EFFBECAMECONFUSED             (BATTLESTRINGS_ID_ADDER + 43)
#define STRINGID_DEFALREADYCONFUSED            (BATTLESTRINGS_ID_ADDER + 44)
#define STRINGID_DEFFELLINLOVE                 (BATTLESTRINGS_ID_ADDER + 45)
#define STRINGID_ATKISINLOVEWITHPKMN           (BATTLESTRINGS_ID_ADDER + 46)
#define STRINGID_ATKIMMOBILIZEDBYLOVE          (BATTLESTRINGS_ID_ADDER + 47)
#define STRINGID_PKMNTYPECHANGEDTOBUFF1        (BATTLESTRINGS_ID_ADDER + 48)
#define STRINGID_ATKFLINCHED                   (BATTLESTRINGS_ID_ADDER + 49)
#define STRINGID_DEFREGAINEDHEALTH             (BATTLESTRINGS_ID_ADDER + 50)
#define STRINGID_DEFHPFULL                     (BATTLESTRINGS_ID_ADDER + 51)
#define STRINGID_ATKTEAMCLOAKEDINMYSTICALVEIL  (BATTLESTRINGS_ID_ADDER + 52)
#define STRINGID_BUFF1RAISEDATKTEAMBUFF2       (BATTLESTRINGS_ID_ADDER + 53)
#define STRINGID_DEFTEAMSAFEGUARDPROTECTED     (BATTLESTRINGS_ID_ADDER + 54)
#define STRINGID_ATKTEAMSAFEGUARDEXPIRED       (BATTLESTRINGS_ID_ADDER + 55)
#define STRINGID_ATKTEAMBUFF1WOREOFF           (BATTLESTRINGS_ID_ADDER + 56)
#define STRINGID_DEFWENTTOSLEEP                (BATTLESTRINGS_ID_ADDER + 57)
#define STRINGID_DEFSLEPTHEALTHY               (BATTLESTRINGS_ID_ADDER + 58)
#define STRINGID_BUTITFAILED                   (BATTLESTRINGS_ID_ADDER + 59)
#define STRINGID_ATKWHIPPEDWHIRLWIND           (BATTLESTRINGS_ID_ADDER + 60)
#define STRINGID_ATKBECAMECLOAKEDINSUNLIGHT    (BATTLESTRINGS_ID_ADDER + 61)
#define STRINGID_ATKBURROWEDUNDERTHEGROUND     (BATTLESTRINGS_ID_ADDER + 62)
#define STRINGID_ATKTUCKEDINHEAD               (BATTLESTRINGS_ID_ADDER + 63)
#define STRINGID_ATKSPRANGUP                   (BATTLESTRINGS_ID_ADDER + 64)
#define STRINGID_ATKHIDUNDERWATER              (BATTLESTRINGS_ID_ADDER + 65)
#define STRINGID_ATKFLEWHIGH                   (BATTLESTRINGS_ID_ADDER + 66)
#define STRINGID_ATKABSORBEDLIGHT              (BATTLESTRINGS_ID_ADDER + 67)
#define STRINGID_EFFSQUEEZEDBYPKMN             (BATTLESTRINGS_ID_ADDER + 68)
#define STRINGID_EFFWRAPPEDBYPKMN              (BATTLESTRINGS_ID_ADDER + 69)
#define STRINGID_EFFTRAPPEDINVORTEX            (BATTLESTRINGS_ID_ADDER + 70)
#define STRINGID_PKMNCLAMPEDEFF                (BATTLESTRINGS_ID_ADDER + 71)
#define STRINGID_EFFTRAPPEDBYCURRMOVE          (BATTLESTRINGS_ID_ADDER + 72)
#define STRINGID_ATKHURTBYBUFF1                (BATTLESTRINGS_ID_ADDER + 73)
#define STRINGID_ATKFREEDFROMBUFF1             (BATTLESTRINGS_ID_ADDER + 74)
#define STRINGID_ATKKEPTANDCRASHED             (BATTLESTRINGS_ID_ADDER + 75)
#define STRINGID_ATKTEAMSHROUDEDINMIST         (BATTLESTRINGS_ID_ADDER + 76)
#define STRINGID_ATKGETTINGPUMPED              (BATTLESTRINGS_ID_ADDER + 77)
#define STRINGID_ATKHITWITHRECOIL              (BATTLESTRINGS_ID_ADDER + 78)
#define STRINGID_ATKBUFFETEDBYSANDSTORM        (BATTLESTRINGS_ID_ADDER + 79)
#define STRINGID_ATKPELTEDBYHAIL               (BATTLESTRINGS_ID_ADDER + 80)
#define STRINGID_DEFWASSEEDED                  (BATTLESTRINGS_ID_ADDER + 81)
#define STRINGID_DEFEVADEDATTACK               (BATTLESTRINGS_ID_ADDER + 82)
#define STRINGID_DEFSAPPEDBYLEECHSEED          (BATTLESTRINGS_ID_ADDER + 83)
#define STRINGID_ATKFASTASLEEP                 (BATTLESTRINGS_ID_ADDER + 84)
#define STRINGID_ATKWOKEUP                     (BATTLESTRINGS_ID_ADDER + 85)
#define STRINGID_ATKWOKEUPINUPROAR             (BATTLESTRINGS_ID_ADDER + 86)
#define STRINGID_DEFENDUREDHIT                 (BATTLESTRINGS_ID_ADDER + 87)
#define STRINGID_ONEHITKO                      (BATTLESTRINGS_ID_ADDER + 88)
#define STRINGID_ATKSTORINGENERGY              (BATTLESTRINGS_ID_ADDER + 89)
#define STRINGID_ATKUNLEASHEDENERGY            (BATTLESTRINGS_ID_ADDER + 90)
#define STRINGID_FIZZLESBUFF1TYPEATTACK        (BATTLESTRINGS_ID_ADDER + 91)
#define STRINGID_EVAPORATEBUFF1TYPEATTACK      (BATTLESTRINGS_ID_ADDER + 92)
#define STRINGID_ATKFATIGUECONFUSION           (BATTLESTRINGS_ID_ADDER + 93)
#define STRINGID_PLAYERPICKEDUPMONEY           (BATTLESTRINGS_ID_ADDER + 94)
#define STRINGID_DEFUNAFFECTED                 (BATTLESTRINGS_ID_ADDER + 95)
#define STRINGID_ATKTRANSFORMEDINTOBUFF1       (BATTLESTRINGS_ID_ADDER + 96)
#define STRINGID_ATKMADESUBSTITUTE             (BATTLESTRINGS_ID_ADDER + 97)
#define STRINGID_ATKHASSUBSTITUTE              (BATTLESTRINGS_ID_ADDER + 98)
#define STRINGID_TOOWEAKFORSUBSTITUTE          (BATTLESTRINGS_ID_ADDER + 99)
#define STRINGID_SUBSTITUTEDAMAGED             (BATTLESTRINGS_ID_ADDER + 100)
#define STRINGID_DEFSUBSTITUTEFADED            (BATTLESTRINGS_ID_ADDER + 101)
#define STRINGID_ATKMUSTRECHARGE               (BATTLESTRINGS_ID_ADDER + 102)
#define STRINGID_ATKTOOKAIMATDEF               (BATTLESTRINGS_ID_ADDER + 103)
#define STRINGID_DEFBUFF1WASDISABLED           (BATTLESTRINGS_ID_ADDER + 104)
#define STRINGID_ATKCURRMOVEISDISABLED         (BATTLESTRINGS_ID_ADDER + 105)
#define STRINGID_ATKDISABLEDNOMORE             (BATTLESTRINGS_ID_ADDER + 106)
#define STRINGID_DEFRECEIVEDENCORE             (BATTLESTRINGS_ID_ADDER + 107)
#define STRINGID_ATKENCOREENDED                (BATTLESTRINGS_ID_ADDER + 108)
#define STRINGID_ATKTRYINGTOTAKEFOEDOWN        (BATTLESTRINGS_ID_ADDER + 109)
#define STRINGID_DEFTOOKATTACKERWITHIT         (BATTLESTRINGS_ID_ADDER + 110)
#define STRINGID_REDUCEDPPOFDEFBUFF1BYBUFF2    (BATTLESTRINGS_ID_ADDER + 111)
#define STRINGID_ATKSTOLEDEFLASTITEM           (BATTLESTRINGS_ID_ADDER + 112)
#define STRINGID_DEFCANNOLONGERESCAPE          (BATTLESTRINGS_ID_ADDER + 113)
#define STRINGID_DEFBEGANHAVINGNIGHTMARE       (BATTLESTRINGS_ID_ADDER + 114)
#define STRINGID_ATKLOCKEDINNIGHTMARE          (BATTLESTRINGS_ID_ADDER + 115)
#define STRINGID_SPIKESSCATTERED               (BATTLESTRINGS_ID_ADDER + 116)
#define STRINGID_DEFWASIDENTIFIED              (BATTLESTRINGS_ID_ADDER + 117)
#define STRINGID_ATKPERISHCOUNTFELLTOBUFF1     (BATTLESTRINGS_ID_ADDER + 118)
#define STRINGID_ATKBRACEDITSELF               (BATTLESTRINGS_ID_ADDER + 119)
#define STRINGID_MAGNITUDEBUFF1                (BATTLESTRINGS_ID_ADDER + 120)
#define STRINGID_ATKCOPIEDDEFSTATCHANGES       (BATTLESTRINGS_ID_ADDER + 121)
#define STRINGID_ATKFLEDFROMBATTLE             (BATTLESTRINGS_ID_ADDER + 122)
#define STRINGID_ATKFORESAWATTACK              (BATTLESTRINGS_ID_ADDER + 123)
#define STRINGID_ATKCHOSECURRMOVEASDESTINY     (BATTLESTRINGS_ID_ADDER + 124)
#define STRINGID_DEFTOOKTHECURRMOVEATTACK      (BATTLESTRINGS_ID_ADDER + 125)
#define STRINGID_ATKBECAMETHECENTERATTENTION   (BATTLESTRINGS_ID_ADDER + 126)
#define STRINGID_BUFF1TURNEDINTOCURRMOVE       (BATTLESTRINGS_ID_ADDER + 127)
#define STRINGID_ATKHASNOMOVESLEFT             (BATTLESTRINGS_ID_ADDER + 128)
#define STRINGID_DEFSUBJECTEDTOTORMENT         (BATTLESTRINGS_ID_ADDER + 129)
#define STRINGID_ATKCANTUSEMOVETORMENT         (BATTLESTRINGS_ID_ADDER + 130)
#define STRINGID_ATKTIGHTENINGFOCUS            (BATTLESTRINGS_ID_ADDER + 131)
#define STRINGID_DEFFELLFORTAUNT               (BATTLESTRINGS_ID_ADDER + 132)
#define STRINGID_ATKCANTUSECURRMOVETAUNT       (BATTLESTRINGS_ID_ADDER + 133)
#define STRINGID_ATKREADYTOHELPDEF             (BATTLESTRINGS_ID_ADDER + 134)
#define STRINGID_ATKCOPIEDDEFABL               (BATTLESTRINGS_ID_ADDER + 135)
#define STRINGID_BUFF1WISHCAMETRUE             (BATTLESTRINGS_ID_ADDER + 136)
#define STRINGID_ATKPLANTEDROOTS               (BATTLESTRINGS_ID_ADDER + 137)
#define STRINGID_ATKABSORBEDNUTRIENTS          (BATTLESTRINGS_ID_ADDER + 138)
#define STRINGID_DEFANCHOREDITSELF             (BATTLESTRINGS_ID_ADDER + 139)
#define STRINGID_DEFGREWDROWSY                 (BATTLESTRINGS_ID_ADDER + 140)
#define STRINGID_ATKSWAPPEDABILITIESWITHTARGET (BATTLESTRINGS_ID_ADDER + 141)
#define STRINGID_DEFBOUNCEDCURRMOVEBACK        (BATTLESTRINGS_ID_ADDER + 142)
#define STRINGID_ATKSHROUDEDWITHCURRMOVE       (BATTLESTRINGS_ID_ADDER + 143)
#define STRINGID_CRITICALHIT                   (BATTLESTRINGS_ID_ADDER + 144)
#define STRINGID_CRITICALHITONDEF              (BATTLESTRINGS_ID_ADDER + 145)
#define STRINGID_123POOF                       (BATTLESTRINGS_ID_ADDER + 146)
#define STRINGID_ANDELLIPSIS                   (BATTLESTRINGS_ID_ADDER + 147)
#define STRINGID_NOTVERYEFFECTIVE              (BATTLESTRINGS_ID_ADDER + 148)
#define STRINGID_NOTVERYEFFECTIVEONDEF         (BATTLESTRINGS_ID_ADDER + 149)
#define STRINGID_SUPEREFFECTIVE                (BATTLESTRINGS_ID_ADDER + 150)
#define STRINGID_SUPEREFFECTIVEONDEF           (BATTLESTRINGS_ID_ADDER + 151)
#define STRINGID_ATKISLOAFINGAROUND            (BATTLESTRINGS_ID_ADDER + 152)
#define STRINGID_ATKWONTOBEY                   (BATTLESTRINGS_ID_ADDER + 153)
#define STRINGID_ATKTURNEDAWAY                 (BATTLESTRINGS_ID_ADDER + 154)
#define STRINGID_ATKPRETENDNOTNOTICE           (BATTLESTRINGS_ID_ADDER + 155)
#define STRINGID_BUFF1ISNERVOUSTOEATBERRIES    (BATTLESTRINGS_ID_ADDER + 156)
#define STRINGID_EFFPREVENTSPOISONINGWITH      (BATTLESTRINGS_ID_ADDER + 157)
#define STRINGID_EMPTYSTRING                   (BATTLESTRINGS_ID_ADDER + 158)
#define STRINGID_ABOOSTED                      (BATTLESTRINGS_ID_ADDER + 159)
#define STRINGID_STARTEDTORAIN                 (BATTLESTRINGS_ID_ADDER + 160)
#define STRINGID_GOTAWAYSAFELY                 (BATTLESTRINGS_ID_ADDER + 161)
#define STRINGID_WILDBUFF1FLED                 (BATTLESTRINGS_ID_ADDER + 162)
#define STRINGID_DEFPROTECTEDBYDEFABL          (BATTLESTRINGS_ID_ADDER + 163)
#define STRINGID_PKMNABLPREVENTSATKUSECURRMOVE (BATTLESTRINGS_ID_ADDER + 164)
#define STRINGID_BUTNOTHINGHAPPENED            (BATTLESTRINGS_ID_ADDER + 165)
#define STRINGID_ITHURTITSELFINCONFUSION       (BATTLESTRINGS_ID_ADDER + 166)
#define STRINGID_THECURRMOVEFAILED             (BATTLESTRINGS_ID_ADDER + 167)
#define STRINGID_DEFHADHPRESTORED              (BATTLESTRINGS_ID_ADDER + 168)
#define STRINGID_POWEROFDEFBUFF1TYPEMOVESROSE  (BATTLESTRINGS_ID_ADDER + 169)
#define STRINGID_ITTRACEDDEFABL                (BATTLESTRINGS_ID_ADDER + 170)
#define STRINGID_ATKWASHURT                    (BATTLESTRINGS_ID_ADDER + 171)
#define STRINGID_MONHEARINGFLUTEAWOKE          (BATTLESTRINGS_ID_ADDER + 172)
#define STRINGID_GOTCHADEFCAUGHT               (BATTLESTRINGS_ID_ADDER + 173)
#define STRINGID_DEFDATAADDEDTODEX             (BATTLESTRINGS_ID_ADDER + 174)
#define STRINGID_PKMNTRANSFERREDSOMEONESPC     (BATTLESTRINGS_ID_ADDER + 175)
#define STRINGID_PKMNTRANSFERREDBILLSPC        (BATTLESTRINGS_ID_ADDER + 176)
#define STRINGID_PKMNBOXSOMEONESPCFULL         (BATTLESTRINGS_ID_ADDER + 177)
#define STRINGID_PKMNBOXBILLSPCFULL            (BATTLESTRINGS_ID_ADDER + 178)
#define STRINGID_OUTOFSAFARIBALLS              (BATTLESTRINGS_ID_ADDER + 179)
#define STRINGID_POKEMONBROKEFREE              (BATTLESTRINGS_ID_ADDER + 180)
#define STRINGID_ITAPPEAREDCAUGHT              (BATTLESTRINGS_ID_ADDER + 181)
#define STRINGID_AARGHALMOSTHADIT              (BATTLESTRINGS_ID_ADDER + 182)
#define STRINGID_SHOOTSOCLOSE                  (BATTLESTRINGS_ID_ADDER + 183)
#define STRINGID_TRAINERBLOCKEDBALL            (BATTLESTRINGS_ID_ADDER + 184)
#define STRINGID_DONTBEATHIEF                  (BATTLESTRINGS_ID_ADDER + 185)
#define STRINGID_ITDODGEDBALL                  (BATTLESTRINGS_ID_ADDER + 186)
#define STRINGID_PKMNWATCHINGCAREFULLY         (BATTLESTRINGS_ID_ADDER + 187)
#define STRINGID_PKMNANGRY                     (BATTLESTRINGS_ID_ADDER + 188)
#define STRINGID_PKMNEATING                    (BATTLESTRINGS_ID_ADDER + 189)
#define STRINGID_THREWROCK                     (BATTLESTRINGS_ID_ADDER + 190)
#define STRINGID_THREWBAIT                     (BATTLESTRINGS_ID_ADDER + 191)
#define STRINGID_YOUTHROWABALLNOWRIGHT         (BATTLESTRINGS_ID_ADDER + 192)
#define STRINGID_NORUNNINGFROMTRAINERS         (BATTLESTRINGS_ID_ADDER + 193)
#define STRINGID_CANTESCAPE                    (BATTLESTRINGS_ID_ADDER + 194)
#define STRINGID_DONTLEAVEBIRCH                (BATTLESTRINGS_ID_ADDER + 195)
#define STRINGID_ATKCANTESCAPE                 (BATTLESTRINGS_ID_ADDER + 196)
#define STRINGID_RAINCONTINUES                 (BATTLESTRINGS_ID_ADDER + 197)
#define STRINGID_RAINSTOPPED                   (BATTLESTRINGS_ID_ADDER + 198)
#define STRINGID_SUNLIGHTSTRONG                (BATTLESTRINGS_ID_ADDER + 199)
#define STRINGID_SUNLIGHTFADED                 (BATTLESTRINGS_ID_ADDER + 200)
#define STRINGID_SANDSTORMRAGES                (BATTLESTRINGS_ID_ADDER + 201)
#define STRINGID_SANDSTORMSUBSIDED             (BATTLESTRINGS_ID_ADDER + 202)
#define STRINGID_HAILCONTINUES                 (BATTLESTRINGS_ID_ADDER + 203)
#define STRINGID_HAILSTOPPED                   (BATTLESTRINGS_ID_ADDER + 204)
#define STRINGID_DEEPFOG                       (BATTLESTRINGS_ID_ADDER + 205)
#define STRINGID_FOGENDED                      (BATTLESTRINGS_ID_ADDER + 206)
#define STRINGID_MYSTERIOUSAIRCONTINUES        (BATTLESTRINGS_ID_ADDER + 207)
#define STRINGID_ASANDSTORMKICKEDUP            (BATTLESTRINGS_ID_ADDER + 208)
#define STRINGID_SUNLIGHTTURNEDHARSH           (BATTLESTRINGS_ID_ADDER + 209)
#define STRINGID_STARTEDHAIL                   (BATTLESTRINGS_ID_ADDER + 210)
#define STRINGID_COINSSCATTERED                (BATTLESTRINGS_ID_ADDER + 211)
#define STRINGID_GIVENICKNAMECAPTURED          (BATTLESTRINGS_ID_ADDER + 212)
#define STRINGID_BATTLERSSHAREDTHEIRPAIN       (BATTLESTRINGS_ID_ADDER + 213)
#define STRINGID_BELLCHIMED                    (BATTLESTRINGS_ID_ADDER + 214)
#define STRINGID_SOOTHINGAROMA                 (BATTLESTRINGS_ID_ADDER + 215)
#define STRINGID_STATCHANGESELIMINATED         (BATTLESTRINGS_ID_ADDER + 216)
#define STRINGID_ALLPOKEMONFAINTINTHREETURNS   (BATTLESTRINGS_ID_ADDER + 217)
#define STRINGID_NOPPLEFT                      (BATTLESTRINGS_ID_ADDER + 218)
#define STRINGID_BUTNOPPLEFT                   (BATTLESTRINGS_ID_ADDER + 219)
#define STRINGID_ATKIGNOREDORDERSASLEEP        (BATTLESTRINGS_ID_ADDER + 220)
#define STRINGID_ATKIGNOREDORDERS              (BATTLESTRINGS_ID_ADDER + 221)
#define STRINGID_ATKBEGANTONAP                 (BATTLESTRINGS_ID_ADDER + 222)
#define STRINGID_ENEMYABOUTTOSWITCHPKMN        (BATTLESTRINGS_ID_ADDER + 223)
#define STRINGID_LASTITEMALLOWSONLYCURRMOVE    (BATTLESTRINGS_ID_ADDER + 224)
#define STRINGID_ITEMSCANTBEUSEDNOW            (BATTLESTRINGS_ID_ADDER + 225)
#define STRINGID_BOXISFULL                     (BATTLESTRINGS_ID_ADDER + 226)


#define STRINGID_PKMNHUNGONWITHX 303
#define STRINGID_PKMNSXBLOCKSY 306
#define STRINGID_PKMNSXRESTOREDHPALITTLE2 307
#define STRINGID_PKMNSXWHIPPEDUPSANDSTORM 308
#define STRINGID_PKMNSXPREVENTSYLOSS 309
#define STRINGID_PKMNSXINFATUATEDY 310
#define STRINGID_PKMNSXMADEYINEFFECTIVE 311
#define STRINGID_PKMNSXCUREDYPROBLEM 312
#define STRINGID_ITSUCKEDLIQUIDOOZE 313
#define STRINGID_PKMNTRANSFORMED 314
#define STRINGID_ELECTRICITYWEAKENED 315
#define STRINGID_FIREWEAKENED 316
#define STRINGID_HMMOVESCANTBEFORGOTTEN 319
#define STRINGID_XFOUNDONEY 320
#define STRINGID_PLAYERDEFEATEDTRAINER1 321
#define STRINGID_FORXCOMMAYZ 324
#define STRINGID_USINGXTHEYOFZN 325
#define STRINGID_PKMNUSEDXTOGETPUMPED 326
#define STRINGID_PKMNSXMADEYUSELESS 327
#define STRINGID_PKMNSXINTENSIFIEDSUN 331
#define STRINGID_PKMNMAKESGROUNDMISS 332
#define STRINGID_PKMNSXTOOKATTACK 334
#define STRINGID_PKMNLOSTFOCUS 336
#define STRINGID_USENEXTPKMN 337
#define STRINGID_PKMNFLEDUSINGITS 338
#define STRINGID_PKMNFLEDUSING 339
#define STRINGID_PKMNWASDRAGGEDOUT 340
#define STRINGID_PREVENTEDFROMWORKING 341
#define STRINGID_PKMNSITEMNORMALIZEDSTATUS 342
#define STRINGID_PKMNAVOIDEDATTACK 345
#define STRINGID_PKMNSXMADEITINEFFECTIVE 346
#define STRINGID_PKMNSXPREVENTSFLINCHING 347
#define STRINGID_PKMNALREADYHASBURN 348
#define STRINGID_STATSWONTDECREASE2 349
#define STRINGID_PKMNSXBLOCKSY2 350
#define STRINGID_THEWALLSHATTERED 354
#define STRINGID_PKMNSXPREVENTSYSZ 355
#define STRINGID_PKMNSXCUREDITSYPROBLEM 356
#define STRINGID_PKMNOBTAINEDX 358
#define STRINGID_PKMNOBTAINEDX2 359
#define STRINGID_PKMNOBTAINEDXYOBTAINEDZ 360
#define STRINGID_BUTNOEFFECT 361
#define STRINGID_PKMNSXHADNOEFFECTONY 362
#define STRINGID_OAKPLAYERWON 363
#define STRINGID_OAKPLAYERLOST 364
#define STRINGID_PLAYERLOSTAGAINSTENEMYTRAINER 365
#define STRINGID_PLAYERPAIDPRIZEMONEY 366
#define STRINGID_TRAINER2NAME 376
#define STRINGID_PLAYERWHITEDOUT 377
#define STRINGID_MONTOOSCAREDTOMOVE 378
#define STRINGID_GHOSTGETOUTGETOUT 379
#define STRINGID_SILPHSCOPEUNVEILED 380
#define STRINGID_GHOSTWASMAROWAK 381
#define STRINGID_TRAINER1MON1COMEBACK 382
#define STRINGID_TRAINER1WINTEXT 383
#define STRINGID_TRAINER1MON2COMEBACK 384
#define STRINGID_TRAINER1MON1AND2COMEBACK 385
#define STRINGID_AROMAVEILPROTECTED 386
#define STRINGID_FLOWERVEILPROTECTED 387
#define STRINGID_SWEETVEILPROTECTED 388
#define STRINGID_HEAVYRAINLIFTED 389
#define STRINGID_EXTREMESUNLIGHTFADED 390
#define STRINGID_STRONGWINDSDISSIPATED 391
#define STRINGID_PKMNSXMADEITHAIL 395
#define STRINGID_HEAVYRAINBEGANFALL 396
#define STRINGID_EXTREHARSHSUNLIGHT 397
#define STRINGID_MYSTERIOUSAIRPROTECTINGPKMN 398
#define STRINGID_WEATHEREFFECTSDISAPPEARED 399
#define STRINGID_PKMNBREAKSTHEMOLD 400
#define STRINGID_PKMNCANTGETGOING 401
#define STRINGID_RADIATINGABLAZINGAURA 403
#define STRINGID_RADIATINGABURSTINGAURA 404
#define STRINGID_RADIATINGADARKAURA 405
#define STRINGID_RADIATINGAFAIRYAURA 406
#define STRINGID_REVERSEDALLOTHERAURAS 407
#define STRINGID_PKMNISDROWSING 408
#define STRINGID_PKMNUNDERWENTTRANSFORMATION 409
#define STRINGID_ABILITYTRIGGERED 410
#define STRINGID_PKMNGAINSOMEOFHP 411
#define STRINGID_PKMNLOSTSOMEOFHP 412
#define STRINGID_ATKABLCUREDEFFPROBLEM 413
#define STRINGID_PKMNGOTITSACT 414
#define STRINGID_DEFISTORMENTED 415
#define STRINGID_ATKHARVESTEDITSITEM 416
#define STRINGID_ATKCANTUSECURRMOVE 417
#define STRINGID_DEFLASTABLRAISEDBUFF1 418
#define STRINGID_DEFMAXEDATTACK 419
#define STRINGID_DEFABLDISABLEDATKCURRMOVE 420
#define STRINGID_PKMNILLUSIONOFF 421
#define STRINGID_ATKABILITYBECAMEABL 422
#define STRINGID_PKMNSHUDDERED 423
#define STRINGID_ATTACKERABILITYSTATRAISE 424
#define STRINGID_ALERTEDTODEFBUFF1 425
#define STRINGID_ATKFRISKEDDEFFOUNDLASTITEM 426
#define STRINGID_ATKCUTHPMINIMIZEDATTACK 427
#define STRINGID_ATKABLRAISEDITSSPEED 428
#define STRINGID_ALLSCREENSCLEANSED 429
#define STRINGID_BOTHWILLPERISHIN3TURNS 430
#define STRINGID_DEFSTATCHANGESWERERESET 431
#define STRINGID_CURRMOVECHARGEDDEFPOWER 432
#define STRINGID_NEUTRALIZINGGASOVER 433
#define STRINGID_PKMNABLFILLEDTHEAREA 434
#define STRINGID_PASTELVEILPROTECTED 435
#define STRINGID_PASTELVEILCUREDSTATUS 436
#define STRINGID_STARTEDSCHOOLING 437
#define STRINGID_STOPPEDSCHOOLING 438
#define STRINGID_DISGUISESERVEDASDECOY 439
#define STRINGID_DISGUISEBUSTED 440
#define STRINGID_PKMNGOTOVERINFATUATION 441
#define STRINGID_PKMNSHOOKOFFTAUNT 442
#define STRINGID_PKMNEXERTINGPRESSURE 443
#define STRINGID_CHANGEDTOBLADE 447
#define STRINGID_CHANGEDTOSHIELD 448
#define STRINGID_PKMNGAINEDSTRENGTH 449
#define STRINGID_PKMNABLWEAKENEDBUFF1 450
#define STRINGID_ATKFOUNDLASTITEM 451
#define STRINGID_PKMNHASTWOABILITIES 452
#define STRINGID_PKMNABLWASTAKENOVER 453
#define STRINGID_ITEMRESTOREDSPECIESHEALTH 454
#define STRINGID_ITEMCUREDSPECIESSTATUS 455
#define STRINGID_ITEMRESTOREDSPECIESPP 456
#define STRINGID_BUFF2CUREDOFITSBUFF1 457
#define STRINGID_ABILITYACTIVATED 459
#define STRINGID_ABILITYDEACTIVATED 460

#define BATTLESTRINGS_COUNT     460 + BATTLESTRINGS_ID_ADDER

#define STRINGID_PKMNRAISEDSPEED 194
#define STRINGID_PKMNUPROARKEPTAWAKE 402
#define STRINGID_PKMNCAUSEDUPROAR 444
#define STRINGID_PKMNMAKINGUPROAR 329
#define STRINGID_PKMNCALMEDDOWN 330
#define STRINGID_PKMNCANTSLEEPINUPROAR 168
#define STRINGID_PKMNSTOCKPILED 169
#define STRINGID_PKMNCANTSTOCKPILE 170
#define STRINGID_PKMNCANTSLEEPINUPROAR2 171
#define STRINGID_UPROARKEPTPKMNAWAKE 172
#define STRINGID_PKMNSTAYEDAWAKEUSING 173
#define STRINGID_PKMNRAGEBUILDING 174
#define STRINGID_PKMNLAIDCURSE 175
#define STRINGID_PKMNAFFLICTEDBYCURSE 176
#define STRINGID_PKMNHURTBYSPIKES 177
#define STRINGID_PKMNCUTHPMAXEDATTACK 178
#define STRINGID_PKMNGOTFREE 179
#define STRINGID_PKMNSHEDLEECHSEED 180
#define STRINGID_PKMNBLEWAWAYSPIKES 181
#define STRINGID_PKMNCHARGINGPOWER 182
#define STRINGID_PKMNSWITCHEDITEMS 184
#define STRINGID_PKMNKNOCKEDOFF 189
#define STRINGID_STATSWONTINCREASE2 190
#define STRINGID_STATSWONTINCREASE 198
#define STRINGID_STATSWONTDECREASE 305
#define STRINGID_PKMNPROTECTEDBYMIST 351
#define STRINGID_PKMNSEALEDOPPONENTMOVE 185
#define STRINGID_PKMNCANTUSEMOVESEALED 186
#define STRINGID_PKMNWANTSGRUDGE 187
#define STRINGID_PKMNLOSTPPGRUDGE 188
#define STRINGID_PKMNWAITSFORTARGET 191
#define STRINGID_PKMNSNATCHEDMOVE 192
#define STRINGID_STATSHARPLY 209
#define STRINGID_STATROSE 210
#define STRINGID_STATHARSHLY 211
#define STRINGID_STATFELL 212
#define STRINGID_PKMNSSTATCHANGED 213
#define STRINGID_PKMNSSTATCHANGED2 214
#define STRINGID_PKMNSSTATCHANGED3 215
#define STRINGID_PKMNSSTATCHANGED4 216
#define STRINGID_PKMNPREVENTSPARALYSISWITH 199
#define STRINGID_PKMNPREVENTSROMANCEWITH 200
#define STRINGID_PKMNPREVENTSCONFUSIONWITH 202
#define STRINGID_PKMNANCHORSITSELFWITH 204
#define STRINGID_PKMNCUTSATTACKWITH 205
#define STRINGID_PKMNPREVENTSSTATLOSSWITH 206
#define STRINGID_FAILEDTOSPITUP 246
#define STRINGID_FAILEDTOSWALLOW 247
#define STRINGID_PKMNSITEMCUREDPARALYSIS 291
#define STRINGID_PKMNSITEMCUREDPOISON 292
#define STRINGID_PKMNSITEMHEALEDBURN 293
#define STRINGID_PKMNSITEMDEFROSTEDIT 294
#define STRINGID_PKMNSITEMWOKEIT 295
#define STRINGID_PKMNSITEMSNAPPEDOUT 296
#define STRINGID_PKMNSITEMCUREDPROBLEM 297
#define STRINGID_PKMNSITEMRESTOREDHEALTH 298
#define STRINGID_PKMNSITEMRESTOREDPP 299
#define STRINGID_PKMNSITEMRESTOREDSTATUS 300
#define STRINGID_PKMNSITEMRESTOREDHPALITTLE 301

// gMissStringIds
#define B_MSG_MISSED        0
#define B_MSG_PROTECTED     1
#define B_MSG_AVOIDED_ATK   2
#define B_MSG_ABILITY_AVOID 3

// gGotDefrostedStringIds
#define B_MSG_DEFROST         0
#define B_MSG_DEFROST_BY_MOVE 1

// gStatusHealStringIds
#define B_MSG_WOKEUP_EFFECT 0
#define B_MSG_CURED_BUFF1   1

// gReflectLightScreenSafeguardStringIds
#define B_MSG_REFLECT_RAISED      0
#define B_MSG_SAFEGUARD_COVERED   1

// gSideStatusWoreOffStringIds
#define B_MSG_SIDE_STATUS_WORE_OFF 0
#define B_MSG_SAFEGUARD_WORE_OFF   1

// gRestUsedStringIds
#define B_MSG_WENT_TO_SLEEP 0
#define B_MSG_SLEPT_HEALTHY 1

// gFirstTurnOfTwoStringIds
#define B_MSG_WHIPPED_WHIRLWIND   0
#define B_MSG_CLOAKED_IN_SUNLIGHT 1
#define B_MSG_BURROWED_IN_GROUND  2
#define B_MSG_TUCKED_HEAD         3
#define B_MSG_SPRANG_UP           4
#define B_MSG_HID_UNDERWATER      5
#define B_MSG_FLEW_UP_HIGH        6
#define B_MSG_ABSORBED_LIGHT      7

// gSandstormHailDmgStringIds
#define B_MSG_DAMAGED_BY_SANDSTORM 0
#define B_MSG_DAMAGED_BY_HAIL      1

// gLeechSeedStringIds
#define B_MSG_SEEDED                  0
#define B_MSG_EVADED_ATTACK           1
#define B_MSG_LEECH_SEED_DOEST_AFFECT 2

// gWokeUpStringIds
#define B_MSG_WOKEUP        0
#define B_MSG_UPROAR_WOKEUP 1

// gPrimalWeatherBlocksAttackStringIds
#define B_MSG_FIZZLES_ATTACK   0
#define B_MSG_EVAPORATE_ATTACK 1

// gKOFailedStringIds
#define B_MSG_KO_MISSED  0
#define B_MSG_UNAFFECTED 1

// gSubsituteUsedStringIds
#define B_MSG_MADE_SUBSTITUTE        0
#define B_MSG_TOO_WEAK_TO_SUBSTITUTE 1
#define B_MSG_HAS_SUBSTITUTE         2

// gProtectLikeUsedStringIds
#define B_MSG_USED_PROTECT   0
#define B_MSG_BRACED_ITSELF  1

// gFutureMoveUsedStringIds
#define B_MSG_FORESAW_ATTACK   0
#define B_MSG_CHOSE_AS_DESTINY 1

// gInobedientStringIds
#define B_MSG_LOAFING_AROUND 0

// gFlashFireStringIds
#define B_MSG_FLASH_FIRE_BOOST       0
#define B_MSG_FLASH_FIRE_DONT_AFFECT 1

// gCaughtMonStringIds
#define B_MSG_TRANSFERRED_TO_SOMEONE_PC 0
#define B_MSG_TRANSFERRED_TO_BILL_PC    1
#define B_MSG_SOMEONE_PC_BOX_FULL       2
#define B_MSG_BILL_PC_BOX_FULL          3

// gSafariPokeblockResultStringIds
#define B_MSG_WATCHING_CAREFULLY 0
#define B_MSG_ANGRY              1
#define B_MSG_EATING             2

// gNoEscapeStringIds
#define B_MSG_CANT_ESCAPE            0
#define B_MSG_DONT_LEAVE_BIRTH       1
#define B_MSG_ABILITY_PREVENT_ESCAPE 2
#define B_MSG_ATK_CANT_ESCAPE        3

// gWeatherContinuesStringIds
#define B_MSG_RAIN_CONTINUES         0
#define B_MSG_RAIN_STOPPED           1
#define B_MSG_SUN_CONTINUES          2
#define B_MSG_SUN_STOPPED            3
#define B_MSG_SANDSTORM_CONTINUES    4
#define B_MSG_SANDSTORM_STOPPED      5
#define B_MSG_HAIL_CONTINUES         6
#define B_MSG_HAIL_STOPPED           7
#define B_MSG_FOG_CONTINUES          8
#define B_MSG_FOG_STOPPED            9
#define B_MSG_STRONG_WINDS_CONTINUES 10

// gMoveWeatherChangeStringIds
#define B_MSG_STARTED_RAIN      0
#define B_MSG_WEATHER_MOVE_FAIL 1
#define B_MSG_SANDSTORM_UP      2
#define B_MSG_SUN_TURN_HARSH    3
#define B_MSG_STARTED_HAIL      4

// gPartyStatusHealStringIds
#define B_MSG_BELL_CHIMED    0
#define B_MSG_SOOTHING_AROMA 1

// gCantUseItemStringIds
#define B_MSG_CANT_USE_ITEM 0
#define B_MSG_BOX_FULL      1

// gNotAllowedMoveStringIds
#define B_MSG_MOVE_DISABLED           0
#define B_MSG_NO_MOVES                1
#define B_MSG_MOVE_TORMENTED          2
#define B_MSG_MOVE_TAUNTED            3
#define B_MSG_MOVE_SEALED             4
#define B_MSG_MOVE_LOCKED_CHOICE_ITEM 5
#define B_MSG_MOVE_NO_PP              6

#endif // GUARD_BATTLE_STRING_IDS_H
