#ifndef GUARD_CONSTANTS_BATTLE_PARTNERS_H
#define GUARD_CONSTANTS_BATTLE_PARTNERS_H

#define PARTNER_NONE 0
#define PARTNER_RAID_YOUNGSTER_NOAH 1
#define PARTNER_RAID_PKMN_BREEDER_KIT 2
#define PARTNER_RAID_GENTLEMAN_MARTIN 3
#define PARTNER_RAID_BLACK_BELT_OSCAR 4
#define PARTNER_RAID_PKMN_BREEDER_POPPY 5
#define PARTNER_RAID_GENTLEMAN_ALFIE 6
#define PARTNER_RAID_YOUNGSTER_AUSTIN 7
#define PARTNER_RAID_BLACK_BELT_ARTHUR 8
#define PARTNER_RAID_YOUNGSTER_LOGAN 9
#define PARTNER_RAID_YOUNGSTER_EVAN 10
#define PARTNER_COUNT 11

#endif  // GUARD_CONSTANTS_BATTLE_PARTNERS_H
