#ifndef GUARD_CONSTANTS_POKE_RIDE_H
#define GUARD_CONSTANTS_POKE_RIDE_H

#define RIDE_NONE        0
#define RIDE_TAUROS      1
#define RIDE_STOUTLAND   2
#define RIDE_MUDSDALE    3
#define RIDE_MACHAMP     4
#define RIDE_SHARPEDO    5
#define RIDE_CHARIZARD   6
#define NUM_RIDE_POKEMON 6

#endif // GUARD_CONSTANTS_POKE_RIDE_H