#ifndef GUARD_CONSTANTS_TRAINER_SLIDES_H
#define GUARD_CONSTANTS_TRAINER_SLIDES_H

#define TRAINER_SLIDE_FIRST_MON_SEND_OUT 0
#define TRAINER_SLIDE_FIRST_MON_DOWN 1
#define TRAINER_SLIDE_LAST_MON_SEND_OUT 2
#define TRAINER_SLIDE_LAST_MON_LOW_HP 3
#define TRAINER_SLIDE_FIRST_SUPER_EFFECTIVE_HIT_TAKEN 4
#define TRAINER_SLIDE_FIRST_CRITICAL_TAKEN 5
#define TRAINER_SLIDE_MEGA_EVOLUTION 6
#define TRAINER_SLIDE_Z_MOVE 7
#define TRAINER_SLIDE_DYNAMAX 8
#define TRAINER_SLIDE_TERASTALIZATION 9

#endif // GUARD_CONSTANTS_TRAINER_SLIDES_H
