// DO NOT MODIFY THIS FILE. IT IS AUTO GENERATED BY tms_creator_helper.py

#ifdef __INTELLISENSE__
const struct Item gTmsInfo_Gen_5[] =
{
#endif

	[ITEM_TM01_HONE_CLAWS] =
	{
		.name = _("TM01"),
		.holdEffectParam = MOVE_HONE_CLAWS,
		.description = (u8*)&gBattleMoves[MOVE_HONE_CLAWS].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM02_DRAGON_CLAW] =
	{
		.name = _("TM02"),
		.holdEffectParam = MOVE_DRAGON_CLAW,
		.description = (u8*)&gBattleMoves[MOVE_DRAGON_CLAW].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM03_PSYSHOCK] =
	{
		.name = _("TM03"),
		.holdEffectParam = MOVE_PSYSHOCK,
		.description = (u8*)&gBattleMoves[MOVE_PSYSHOCK].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM04_CALM_MIND] =
	{
		.name = _("TM04"),
		.holdEffectParam = MOVE_CALM_MIND,
		.description = (u8*)&gBattleMoves[MOVE_CALM_MIND].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM05_ROAR] =
	{
		.name = _("TM05"),
		.holdEffectParam = MOVE_ROAR,
		.description = (u8*)&gBattleMoves[MOVE_ROAR].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM06_TOXIC] =
	{
		.name = _("TM06"),
		.holdEffectParam = MOVE_TOXIC,
		.description = (u8*)&gBattleMoves[MOVE_TOXIC].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM07_HAIL] =
	{
		.name = _("TM07"),
		.holdEffectParam = MOVE_HAIL,
		.description = (u8*)&gBattleMoves[MOVE_HAIL].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM08_BULK_UP] =
	{
		.name = _("TM08"),
		.holdEffectParam = MOVE_BULK_UP,
		.description = (u8*)&gBattleMoves[MOVE_BULK_UP].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM09_VENOSHOCK] =
	{
		.name = _("TM09"),
		.holdEffectParam = MOVE_VENOSHOCK,
		.description = (u8*)&gBattleMoves[MOVE_VENOSHOCK].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM10_HIDDEN_POWER] =
	{
		.name = _("TM10"),
		.holdEffectParam = MOVE_HIDDEN_POWER,
		.description = (u8*)&gBattleMoves[MOVE_HIDDEN_POWER].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM11_SUNNY_DAY] =
	{
		.name = _("TM11"),
		.holdEffectParam = MOVE_SUNNY_DAY,
		.description = (u8*)&gBattleMoves[MOVE_SUNNY_DAY].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM12_TAUNT] =
	{
		.name = _("TM12"),
		.holdEffectParam = MOVE_TAUNT,
		.description = (u8*)&gBattleMoves[MOVE_TAUNT].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM13_ICE_BEAM] =
	{
		.name = _("TM13"),
		.holdEffectParam = MOVE_ICE_BEAM,
		.description = (u8*)&gBattleMoves[MOVE_ICE_BEAM].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM14_BLIZZARD] =
	{
		.name = _("TM14"),
		.holdEffectParam = MOVE_BLIZZARD,
		.description = (u8*)&gBattleMoves[MOVE_BLIZZARD].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM15_HYPER_BEAM] =
	{
		.name = _("TM15"),
		.holdEffectParam = MOVE_HYPER_BEAM,
		.description = (u8*)&gBattleMoves[MOVE_HYPER_BEAM].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM16_LIGHT_SCREEN] =
	{
		.name = _("TM16"),
		.holdEffectParam = MOVE_LIGHT_SCREEN,
		.description = (u8*)&gBattleMoves[MOVE_LIGHT_SCREEN].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM17_PROTECT] =
	{
		.name = _("TM17"),
		.holdEffectParam = MOVE_PROTECT,
		.description = (u8*)&gBattleMoves[MOVE_PROTECT].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM18_RAIN_DANCE] =
	{
		.name = _("TM18"),
		.holdEffectParam = MOVE_RAIN_DANCE,
		.description = (u8*)&gBattleMoves[MOVE_RAIN_DANCE].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM19_TELEKINESIS] =
	{
		.name = _("TM19"),
		.holdEffectParam = MOVE_TELEKINESIS,
		.description = (u8*)&gBattleMoves[MOVE_TELEKINESIS].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM20_SAFEGUARD] =
	{
		.name = _("TM20"),
		.holdEffectParam = MOVE_SAFEGUARD,
		.description = (u8*)&gBattleMoves[MOVE_SAFEGUARD].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM21_FRUSTRATION] =
	{
		.name = _("TM21"),
		.holdEffectParam = MOVE_FRUSTRATION,
		.description = (u8*)&gBattleMoves[MOVE_FRUSTRATION].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM22_SOLAR_BEAM] =
	{
		.name = _("TM22"),
		.holdEffectParam = MOVE_SOLAR_BEAM,
		.description = (u8*)&gBattleMoves[MOVE_SOLAR_BEAM].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM23_SMACK_DOWN] =
	{
		.name = _("TM23"),
		.holdEffectParam = MOVE_SMACK_DOWN,
		.description = (u8*)&gBattleMoves[MOVE_SMACK_DOWN].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM24_THUNDERBOLT] =
	{
		.name = _("TM24"),
		.holdEffectParam = MOVE_THUNDERBOLT,
		.description = (u8*)&gBattleMoves[MOVE_THUNDERBOLT].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM25_THUNDER] =
	{
		.name = _("TM25"),
		.holdEffectParam = MOVE_THUNDER,
		.description = (u8*)&gBattleMoves[MOVE_THUNDER].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM26_EARTHQUAKE] =
	{
		.name = _("TM26"),
		.holdEffectParam = MOVE_EARTHQUAKE,
		.description = (u8*)&gBattleMoves[MOVE_EARTHQUAKE].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM27_RETURN] =
	{
		.name = _("TM27"),
		.holdEffectParam = MOVE_RETURN,
		.description = (u8*)&gBattleMoves[MOVE_RETURN].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM28_DIG] =
	{
		.name = _("TM28"),
		.holdEffectParam = MOVE_DIG,
		.description = (u8*)&gBattleMoves[MOVE_DIG].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM29_PSYCHIC] =
	{
		.name = _("TM29"),
		.holdEffectParam = MOVE_PSYCHIC,
		.description = (u8*)&gBattleMoves[MOVE_PSYCHIC].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM30_SHADOW_BALL] =
	{
		.name = _("TM30"),
		.holdEffectParam = MOVE_SHADOW_BALL,
		.description = (u8*)&gBattleMoves[MOVE_SHADOW_BALL].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM31_BRICK_BREAK] =
	{
		.name = _("TM31"),
		.holdEffectParam = MOVE_BRICK_BREAK,
		.description = (u8*)&gBattleMoves[MOVE_BRICK_BREAK].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM32_DOUBLE_TEAM] =
	{
		.name = _("TM32"),
		.holdEffectParam = MOVE_DOUBLE_TEAM,
		.description = (u8*)&gBattleMoves[MOVE_DOUBLE_TEAM].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM33_REFLECT] =
	{
		.name = _("TM33"),
		.holdEffectParam = MOVE_REFLECT,
		.description = (u8*)&gBattleMoves[MOVE_REFLECT].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM34_SLUDGE_WAVE] =
	{
		.name = _("TM34"),
		.holdEffectParam = MOVE_SLUDGE_WAVE,
		.description = (u8*)&gBattleMoves[MOVE_SLUDGE_WAVE].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM35_FLAMETHROWER] =
	{
		.name = _("TM35"),
		.holdEffectParam = MOVE_FLAMETHROWER,
		.description = (u8*)&gBattleMoves[MOVE_FLAMETHROWER].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM36_SLUDGE_BOMB] =
	{
		.name = _("TM36"),
		.holdEffectParam = MOVE_SLUDGE_BOMB,
		.description = (u8*)&gBattleMoves[MOVE_SLUDGE_BOMB].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM37_SANDSTORM] =
	{
		.name = _("TM37"),
		.holdEffectParam = MOVE_SANDSTORM,
		.description = (u8*)&gBattleMoves[MOVE_SANDSTORM].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM38_FIRE_BLAST] =
	{
		.name = _("TM38"),
		.holdEffectParam = MOVE_FIRE_BLAST,
		.description = (u8*)&gBattleMoves[MOVE_FIRE_BLAST].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM39_ROCK_TOMB] =
	{
		.name = _("TM39"),
		.holdEffectParam = MOVE_ROCK_TOMB,
		.description = (u8*)&gBattleMoves[MOVE_ROCK_TOMB].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM40_AERIAL_ACE] =
	{
		.name = _("TM40"),
		.holdEffectParam = MOVE_AERIAL_ACE,
		.description = (u8*)&gBattleMoves[MOVE_AERIAL_ACE].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM41_TORMENT] =
	{
		.name = _("TM41"),
		.holdEffectParam = MOVE_TORMENT,
		.description = (u8*)&gBattleMoves[MOVE_TORMENT].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM42_FACADE] =
	{
		.name = _("TM42"),
		.holdEffectParam = MOVE_FACADE,
		.description = (u8*)&gBattleMoves[MOVE_FACADE].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM43_FLAME_CHARGE] =
	{
		.name = _("TM43"),
		.holdEffectParam = MOVE_FLAME_CHARGE,
		.description = (u8*)&gBattleMoves[MOVE_FLAME_CHARGE].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM44_REST] =
	{
		.name = _("TM44"),
		.holdEffectParam = MOVE_REST,
		.description = (u8*)&gBattleMoves[MOVE_REST].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM45_ATTRACT] =
	{
		.name = _("TM45"),
		.holdEffectParam = MOVE_ATTRACT,
		.description = (u8*)&gBattleMoves[MOVE_ATTRACT].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM46_THIEF] =
	{
		.name = _("TM46"),
		.holdEffectParam = MOVE_THIEF,
		.description = (u8*)&gBattleMoves[MOVE_THIEF].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM47_LOW_SWEEP] =
	{
		.name = _("TM47"),
		.holdEffectParam = MOVE_LOW_SWEEP,
		.description = (u8*)&gBattleMoves[MOVE_LOW_SWEEP].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM48_ROUND] =
	{
		.name = _("TM48"),
		.holdEffectParam = MOVE_ROUND,
		.description = (u8*)&gBattleMoves[MOVE_ROUND].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM49_ECHOED_VOICE] =
	{
		.name = _("TM49"),
		.holdEffectParam = MOVE_ECHOED_VOICE,
		.description = (u8*)&gBattleMoves[MOVE_ECHOED_VOICE].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM50_OVERHEAT] =
	{
		.name = _("TM50"),
		.holdEffectParam = MOVE_OVERHEAT,
		.description = (u8*)&gBattleMoves[MOVE_OVERHEAT].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM51_ALLY_SWITCH] =
	{
		.name = _("TM51"),
		.holdEffectParam = MOVE_ALLY_SWITCH,
		.description = (u8*)&gBattleMoves[MOVE_ALLY_SWITCH].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM52_FOCUS_BLAST] =
	{
		.name = _("TM52"),
		.holdEffectParam = MOVE_FOCUS_BLAST,
		.description = (u8*)&gBattleMoves[MOVE_FOCUS_BLAST].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM53_ENERGY_BALL] =
	{
		.name = _("TM53"),
		.holdEffectParam = MOVE_ENERGY_BALL,
		.description = (u8*)&gBattleMoves[MOVE_ENERGY_BALL].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM54_FALSE_SWIPE] =
	{
		.name = _("TM54"),
		.holdEffectParam = MOVE_FALSE_SWIPE,
		.description = (u8*)&gBattleMoves[MOVE_FALSE_SWIPE].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM55_SCALD] =
	{
		.name = _("TM55"),
		.holdEffectParam = MOVE_SCALD,
		.description = (u8*)&gBattleMoves[MOVE_SCALD].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM56_FLING] =
	{
		.name = _("TM56"),
		.holdEffectParam = MOVE_FLING,
		.description = (u8*)&gBattleMoves[MOVE_FLING].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM57_CHARGE_BEAM] =
	{
		.name = _("TM57"),
		.holdEffectParam = MOVE_CHARGE_BEAM,
		.description = (u8*)&gBattleMoves[MOVE_CHARGE_BEAM].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM58_SKY_DROP] =
	{
		.name = _("TM58"),
		.holdEffectParam = MOVE_SKY_DROP,
		.description = (u8*)&gBattleMoves[MOVE_SKY_DROP].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM59_INCINERATE] =
	{
		.name = _("TM59"),
		.holdEffectParam = MOVE_INCINERATE,
		.description = (u8*)&gBattleMoves[MOVE_INCINERATE].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM60_QUASH] =
	{
		.name = _("TM60"),
		.holdEffectParam = MOVE_QUASH,
		.description = (u8*)&gBattleMoves[MOVE_QUASH].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM61_WILL_O_WISP] =
	{
		.name = _("TM61"),
		.holdEffectParam = MOVE_WILL_O_WISP,
		.description = (u8*)&gBattleMoves[MOVE_WILL_O_WISP].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM62_ACROBATICS] =
	{
		.name = _("TM62"),
		.holdEffectParam = MOVE_ACROBATICS,
		.description = (u8*)&gBattleMoves[MOVE_ACROBATICS].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM63_EMBARGO] =
	{
		.name = _("TM63"),
		.holdEffectParam = MOVE_EMBARGO,
		.description = (u8*)&gBattleMoves[MOVE_EMBARGO].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM64_EXPLOSION] =
	{
		.name = _("TM64"),
		.holdEffectParam = MOVE_EXPLOSION,
		.description = (u8*)&gBattleMoves[MOVE_EXPLOSION].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM65_SHADOW_CLAW] =
	{
		.name = _("TM65"),
		.holdEffectParam = MOVE_SHADOW_CLAW,
		.description = (u8*)&gBattleMoves[MOVE_SHADOW_CLAW].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM66_PAYBACK] =
	{
		.name = _("TM66"),
		.holdEffectParam = MOVE_PAYBACK,
		.description = (u8*)&gBattleMoves[MOVE_PAYBACK].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM67_RETALIATE] =
	{
		.name = _("TM67"),
		.holdEffectParam = MOVE_RETALIATE,
		.description = (u8*)&gBattleMoves[MOVE_RETALIATE].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM68_GIGA_IMPACT] =
	{
		.name = _("TM68"),
		.holdEffectParam = MOVE_GIGA_IMPACT,
		.description = (u8*)&gBattleMoves[MOVE_GIGA_IMPACT].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM69_ROCK_POLISH] =
	{
		.name = _("TM69"),
		.holdEffectParam = MOVE_ROCK_POLISH,
		.description = (u8*)&gBattleMoves[MOVE_ROCK_POLISH].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM70_FLASH] =
	{
		.name = _("TM70"),
		.holdEffectParam = MOVE_FLASH,
		.description = (u8*)&gBattleMoves[MOVE_FLASH].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM71_STONE_EDGE] =
	{
		.name = _("TM71"),
		.holdEffectParam = MOVE_STONE_EDGE,
		.description = (u8*)&gBattleMoves[MOVE_STONE_EDGE].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM72_VOLT_SWITCH] =
	{
		.name = _("TM72"),
		.holdEffectParam = MOVE_VOLT_SWITCH,
		.description = (u8*)&gBattleMoves[MOVE_VOLT_SWITCH].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM73_THUNDER_WAVE] =
	{
		.name = _("TM73"),
		.holdEffectParam = MOVE_THUNDER_WAVE,
		.description = (u8*)&gBattleMoves[MOVE_THUNDER_WAVE].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM74_GYRO_BALL] =
	{
		.name = _("TM74"),
		.holdEffectParam = MOVE_GYRO_BALL,
		.description = (u8*)&gBattleMoves[MOVE_GYRO_BALL].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM75_SWORDS_DANCE] =
	{
		.name = _("TM75"),
		.holdEffectParam = MOVE_SWORDS_DANCE,
		.description = (u8*)&gBattleMoves[MOVE_SWORDS_DANCE].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM76_STRUGGLE_BUG] =
	{
		.name = _("TM76"),
		.holdEffectParam = MOVE_STRUGGLE_BUG,
		.description = (u8*)&gBattleMoves[MOVE_STRUGGLE_BUG].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM77_PSYCH_UP] =
	{
		.name = _("TM77"),
		.holdEffectParam = MOVE_PSYCH_UP,
		.description = (u8*)&gBattleMoves[MOVE_PSYCH_UP].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM78_BULLDOZE] =
	{
		.name = _("TM78"),
		.holdEffectParam = MOVE_BULLDOZE,
		.description = (u8*)&gBattleMoves[MOVE_BULLDOZE].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM79_FROST_BREATH] =
	{
		.name = _("TM79"),
		.holdEffectParam = MOVE_FROST_BREATH,
		.description = (u8*)&gBattleMoves[MOVE_FROST_BREATH].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM80_ROCK_SLIDE] =
	{
		.name = _("TM80"),
		.holdEffectParam = MOVE_ROCK_SLIDE,
		.description = (u8*)&gBattleMoves[MOVE_ROCK_SLIDE].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM81_X_SCISSOR] =
	{
		.name = _("TM81"),
		.holdEffectParam = MOVE_X_SCISSOR,
		.description = (u8*)&gBattleMoves[MOVE_X_SCISSOR].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM82_DRAGON_TAIL] =
	{
		.name = _("TM82"),
		.holdEffectParam = MOVE_DRAGON_TAIL,
		.description = (u8*)&gBattleMoves[MOVE_DRAGON_TAIL].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM83_WORK_UP] =
	{
		.name = _("TM83"),
		.holdEffectParam = MOVE_WORK_UP,
		.description = (u8*)&gBattleMoves[MOVE_WORK_UP].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM84_POISON_JAB] =
	{
		.name = _("TM84"),
		.holdEffectParam = MOVE_POISON_JAB,
		.description = (u8*)&gBattleMoves[MOVE_POISON_JAB].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM85_DREAM_EATER] =
	{
		.name = _("TM85"),
		.holdEffectParam = MOVE_DREAM_EATER,
		.description = (u8*)&gBattleMoves[MOVE_DREAM_EATER].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM86_GRASS_KNOT] =
	{
		.name = _("TM86"),
		.holdEffectParam = MOVE_GRASS_KNOT,
		.description = (u8*)&gBattleMoves[MOVE_GRASS_KNOT].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM87_SWAGGER] =
	{
		.name = _("TM87"),
		.holdEffectParam = MOVE_SWAGGER,
		.description = (u8*)&gBattleMoves[MOVE_SWAGGER].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM88_PLUCK] =
	{
		.name = _("TM88"),
		.holdEffectParam = MOVE_PLUCK,
		.description = (u8*)&gBattleMoves[MOVE_PLUCK].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM89_U_TURN] =
	{
		.name = _("TM89"),
		.holdEffectParam = MOVE_U_TURN,
		.description = (u8*)&gBattleMoves[MOVE_U_TURN].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM90_SUBSTITUTE] =
	{
		.name = _("TM90"),
		.holdEffectParam = MOVE_SUBSTITUTE,
		.description = (u8*)&gBattleMoves[MOVE_SUBSTITUTE].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM91_FLASH_CANNON] =
	{
		.name = _("TM91"),
		.holdEffectParam = MOVE_FLASH_CANNON,
		.description = (u8*)&gBattleMoves[MOVE_FLASH_CANNON].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM92_TRICK_ROOM] =
	{
		.name = _("TM92"),
		.holdEffectParam = MOVE_TRICK_ROOM,
		.description = (u8*)&gBattleMoves[MOVE_TRICK_ROOM].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM93_WILD_CHARGE] =
	{
		.name = _("TM93"),
		.holdEffectParam = MOVE_WILD_CHARGE,
		.description = (u8*)&gBattleMoves[MOVE_WILD_CHARGE].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM94_ROCK_SMASH] =
	{
		.name = _("TM94"),
		.holdEffectParam = MOVE_ROCK_SMASH,
		.description = (u8*)&gBattleMoves[MOVE_ROCK_SMASH].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM95_SNARL] =
	{
		.name = _("TM95"),
		.holdEffectParam = MOVE_SNARL,
		.description = (u8*)&gBattleMoves[MOVE_SNARL].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM96_CUT] =
	{
		.name = _("TM96"),
		.holdEffectParam = MOVE_CUT,
		.description = (u8*)&gBattleMoves[MOVE_CUT].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

#ifdef __INTELLISENSE__
};
#endif
