// DO NOT MODIFY THIS FILE. IT IS AUTO GENERATED BY tms_creator_helper.py

#ifdef __INTELLISENSE__
const struct Item gTmsInfo_Gen_3[] =
{
#endif

	[ITEM_TM01_FOCUS_PUNCH] =
	{
		.name = _("TM01"),
		.holdEffectParam = MOVE_FOCUS_PUNCH,
		.description = (u8*)&gBattleMoves[MOVE_FOCUS_PUNCH].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM02_DRAGON_CLAW] =
	{
		.name = _("TM02"),
		.holdEffectParam = MOVE_DRAGON_CLAW,
		.description = (u8*)&gBattleMoves[MOVE_DRAGON_CLAW].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM03_WATER_PULSE] =
	{
		.name = _("TM03"),
		.holdEffectParam = MOVE_WATER_PULSE,
		.description = (u8*)&gBattleMoves[MOVE_WATER_PULSE].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM04_CALM_MIND] =
	{
		.name = _("TM04"),
		.holdEffectParam = MOVE_CALM_MIND,
		.description = (u8*)&gBattleMoves[MOVE_CALM_MIND].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM05_ROAR] =
	{
		.name = _("TM05"),
		.holdEffectParam = MOVE_ROAR,
		.description = (u8*)&gBattleMoves[MOVE_ROAR].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM06_TOXIC] =
	{
		.name = _("TM06"),
		.holdEffectParam = MOVE_TOXIC,
		.description = (u8*)&gBattleMoves[MOVE_TOXIC].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM07_HAIL] =
	{
		.name = _("TM07"),
		.holdEffectParam = MOVE_HAIL,
		.description = (u8*)&gBattleMoves[MOVE_HAIL].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM08_BULK_UP] =
	{
		.name = _("TM08"),
		.holdEffectParam = MOVE_BULK_UP,
		.description = (u8*)&gBattleMoves[MOVE_BULK_UP].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM09_BULLET_SEED] =
	{
		.name = _("TM09"),
		.holdEffectParam = MOVE_BULLET_SEED,
		.description = (u8*)&gBattleMoves[MOVE_BULLET_SEED].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM10_HIDDEN_POWER] =
	{
		.name = _("TM10"),
		.holdEffectParam = MOVE_HIDDEN_POWER,
		.description = (u8*)&gBattleMoves[MOVE_HIDDEN_POWER].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM11_SUNNY_DAY] =
	{
		.name = _("TM11"),
		.holdEffectParam = MOVE_SUNNY_DAY,
		.description = (u8*)&gBattleMoves[MOVE_SUNNY_DAY].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM12_TAUNT] =
	{
		.name = _("TM12"),
		.holdEffectParam = MOVE_TAUNT,
		.description = (u8*)&gBattleMoves[MOVE_TAUNT].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM13_ICE_BEAM] =
	{
		.name = _("TM13"),
		.holdEffectParam = MOVE_ICE_BEAM,
		.description = (u8*)&gBattleMoves[MOVE_ICE_BEAM].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM14_BLIZZARD] =
	{
		.name = _("TM14"),
		.holdEffectParam = MOVE_BLIZZARD,
		.description = (u8*)&gBattleMoves[MOVE_BLIZZARD].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM15_HYPER_BEAM] =
	{
		.name = _("TM15"),
		.holdEffectParam = MOVE_HYPER_BEAM,
		.description = (u8*)&gBattleMoves[MOVE_HYPER_BEAM].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM16_LIGHT_SCREEN] =
	{
		.name = _("TM16"),
		.holdEffectParam = MOVE_LIGHT_SCREEN,
		.description = (u8*)&gBattleMoves[MOVE_LIGHT_SCREEN].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM17_PROTECT] =
	{
		.name = _("TM17"),
		.holdEffectParam = MOVE_PROTECT,
		.description = (u8*)&gBattleMoves[MOVE_PROTECT].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM18_RAIN_DANCE] =
	{
		.name = _("TM18"),
		.holdEffectParam = MOVE_RAIN_DANCE,
		.description = (u8*)&gBattleMoves[MOVE_RAIN_DANCE].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM19_GIGA_DRAIN] =
	{
		.name = _("TM19"),
		.holdEffectParam = MOVE_GIGA_DRAIN,
		.description = (u8*)&gBattleMoves[MOVE_GIGA_DRAIN].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM20_SAFEGUARD] =
	{
		.name = _("TM20"),
		.holdEffectParam = MOVE_SAFEGUARD,
		.description = (u8*)&gBattleMoves[MOVE_SAFEGUARD].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM21_FRUSTRATION] =
	{
		.name = _("TM21"),
		.holdEffectParam = MOVE_FRUSTRATION,
		.description = (u8*)&gBattleMoves[MOVE_FRUSTRATION].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM22_SOLAR_BEAM] =
	{
		.name = _("TM22"),
		.holdEffectParam = MOVE_SOLAR_BEAM,
		.description = (u8*)&gBattleMoves[MOVE_SOLAR_BEAM].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM23_IRON_TAIL] =
	{
		.name = _("TM23"),
		.holdEffectParam = MOVE_IRON_TAIL,
		.description = (u8*)&gBattleMoves[MOVE_IRON_TAIL].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM24_THUNDERBOLT] =
	{
		.name = _("TM24"),
		.holdEffectParam = MOVE_THUNDERBOLT,
		.description = (u8*)&gBattleMoves[MOVE_THUNDERBOLT].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM25_THUNDER] =
	{
		.name = _("TM25"),
		.holdEffectParam = MOVE_THUNDER,
		.description = (u8*)&gBattleMoves[MOVE_THUNDER].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM26_EARTHQUAKE] =
	{
		.name = _("TM26"),
		.holdEffectParam = MOVE_EARTHQUAKE,
		.description = (u8*)&gBattleMoves[MOVE_EARTHQUAKE].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM27_RETURN] =
	{
		.name = _("TM27"),
		.holdEffectParam = MOVE_RETURN,
		.description = (u8*)&gBattleMoves[MOVE_RETURN].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM28_DIG] =
	{
		.name = _("TM28"),
		.holdEffectParam = MOVE_DIG,
		.description = (u8*)&gBattleMoves[MOVE_DIG].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM29_PSYCHIC] =
	{
		.name = _("TM29"),
		.holdEffectParam = MOVE_PSYCHIC,
		.description = (u8*)&gBattleMoves[MOVE_PSYCHIC].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM30_SHADOW_BALL] =
	{
		.name = _("TM30"),
		.holdEffectParam = MOVE_SHADOW_BALL,
		.description = (u8*)&gBattleMoves[MOVE_SHADOW_BALL].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM31_BRICK_BREAK] =
	{
		.name = _("TM31"),
		.holdEffectParam = MOVE_BRICK_BREAK,
		.description = (u8*)&gBattleMoves[MOVE_BRICK_BREAK].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM32_DOUBLE_TEAM] =
	{
		.name = _("TM32"),
		.holdEffectParam = MOVE_DOUBLE_TEAM,
		.description = (u8*)&gBattleMoves[MOVE_DOUBLE_TEAM].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM33_REFLECT] =
	{
		.name = _("TM33"),
		.holdEffectParam = MOVE_REFLECT,
		.description = (u8*)&gBattleMoves[MOVE_REFLECT].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM34_SHOCK_WAVE] =
	{
		.name = _("TM34"),
		.holdEffectParam = MOVE_SHOCK_WAVE,
		.description = (u8*)&gBattleMoves[MOVE_SHOCK_WAVE].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM35_FLAMETHROWER] =
	{
		.name = _("TM35"),
		.holdEffectParam = MOVE_FLAMETHROWER,
		.description = (u8*)&gBattleMoves[MOVE_FLAMETHROWER].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM36_SLUDGE_BOMB] =
	{
		.name = _("TM36"),
		.holdEffectParam = MOVE_SLUDGE_BOMB,
		.description = (u8*)&gBattleMoves[MOVE_SLUDGE_BOMB].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM37_SANDSTORM] =
	{
		.name = _("TM37"),
		.holdEffectParam = MOVE_SANDSTORM,
		.description = (u8*)&gBattleMoves[MOVE_SANDSTORM].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM38_FIRE_BLAST] =
	{
		.name = _("TM38"),
		.holdEffectParam = MOVE_FIRE_BLAST,
		.description = (u8*)&gBattleMoves[MOVE_FIRE_BLAST].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM39_ROCK_TOMB] =
	{
		.name = _("TM39"),
		.holdEffectParam = MOVE_ROCK_TOMB,
		.description = (u8*)&gBattleMoves[MOVE_ROCK_TOMB].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM40_AERIAL_ACE] =
	{
		.name = _("TM40"),
		.holdEffectParam = MOVE_AERIAL_ACE,
		.description = (u8*)&gBattleMoves[MOVE_AERIAL_ACE].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM41_TORMENT] =
	{
		.name = _("TM41"),
		.holdEffectParam = MOVE_TORMENT,
		.description = (u8*)&gBattleMoves[MOVE_TORMENT].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM42_FACADE] =
	{
		.name = _("TM42"),
		.holdEffectParam = MOVE_FACADE,
		.description = (u8*)&gBattleMoves[MOVE_FACADE].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM43_SECRET_POWER] =
	{
		.name = _("TM43"),
		.holdEffectParam = MOVE_SECRET_POWER,
		.description = (u8*)&gBattleMoves[MOVE_SECRET_POWER].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM44_REST] =
	{
		.name = _("TM44"),
		.holdEffectParam = MOVE_REST,
		.description = (u8*)&gBattleMoves[MOVE_REST].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM45_ATTRACT] =
	{
		.name = _("TM45"),
		.holdEffectParam = MOVE_ATTRACT,
		.description = (u8*)&gBattleMoves[MOVE_ATTRACT].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM46_THIEF] =
	{
		.name = _("TM46"),
		.holdEffectParam = MOVE_THIEF,
		.description = (u8*)&gBattleMoves[MOVE_THIEF].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM47_STEEL_WING] =
	{
		.name = _("TM47"),
		.holdEffectParam = MOVE_STEEL_WING,
		.description = (u8*)&gBattleMoves[MOVE_STEEL_WING].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM48_SKILL_SWAP] =
	{
		.name = _("TM48"),
		.holdEffectParam = MOVE_SKILL_SWAP,
		.description = (u8*)&gBattleMoves[MOVE_SKILL_SWAP].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM49_SNATCH] =
	{
		.name = _("TM49"),
		.holdEffectParam = MOVE_SNATCH,
		.description = (u8*)&gBattleMoves[MOVE_SNATCH].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM50_OVERHEAT] =
	{
		.name = _("TM50"),
		.holdEffectParam = MOVE_OVERHEAT,
		.description = (u8*)&gBattleMoves[MOVE_OVERHEAT].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM51_CUT] =
	{
		.name = _("TM51"),
		.holdEffectParam = MOVE_CUT,
		.description = (u8*)&gBattleMoves[MOVE_CUT].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM52_FLASH] =
	{
		.name = _("TM52"),
		.holdEffectParam = MOVE_FLASH,
		.description = (u8*)&gBattleMoves[MOVE_FLASH].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

#ifdef __INTELLISENSE__
};
#endif
