// DO NOT MODIFY THIS FILE. IT IS AUTO GENERATED BY tms_creator_helper.py

#ifdef __INTELLISENSE__
const struct Item gTmsInfo_Gen_8[] =
{
#endif

	[ITEM_TM01_MEGA_PUNCH] =
	{
		.name = _("TM01"),
		.holdEffectParam = MOVE_MEGA_PUNCH,
		.description = (u8*)&gBattleMoves[MOVE_MEGA_PUNCH].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM02_MEGA_KICK] =
	{
		.name = _("TM02"),
		.holdEffectParam = MOVE_MEGA_KICK,
		.description = (u8*)&gBattleMoves[MOVE_MEGA_KICK].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM03_PAY_DAY] =
	{
		.name = _("TM03"),
		.holdEffectParam = MOVE_PAY_DAY,
		.description = (u8*)&gBattleMoves[MOVE_PAY_DAY].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM04_FIRE_PUNCH] =
	{
		.name = _("TM04"),
		.holdEffectParam = MOVE_FIRE_PUNCH,
		.description = (u8*)&gBattleMoves[MOVE_FIRE_PUNCH].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM05_ICE_PUNCH] =
	{
		.name = _("TM05"),
		.holdEffectParam = MOVE_ICE_PUNCH,
		.description = (u8*)&gBattleMoves[MOVE_ICE_PUNCH].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM06_THUNDER_PUNCH] =
	{
		.name = _("TM06"),
		.holdEffectParam = MOVE_THUNDER_PUNCH,
		.description = (u8*)&gBattleMoves[MOVE_THUNDER_PUNCH].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM07_FLY] =
	{
		.name = _("TM07"),
		.holdEffectParam = MOVE_FLY,
		.description = (u8*)&gBattleMoves[MOVE_FLY].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM08_PIN_MISSILE] =
	{
		.name = _("TM08"),
		.holdEffectParam = MOVE_PIN_MISSILE,
		.description = (u8*)&gBattleMoves[MOVE_PIN_MISSILE].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM09_HYPER_BEAM] =
	{
		.name = _("TM09"),
		.holdEffectParam = MOVE_HYPER_BEAM,
		.description = (u8*)&gBattleMoves[MOVE_HYPER_BEAM].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM10_GIGA_IMPACT] =
	{
		.name = _("TM10"),
		.holdEffectParam = MOVE_GIGA_IMPACT,
		.description = (u8*)&gBattleMoves[MOVE_GIGA_IMPACT].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM11_MAGICAL_LEAF] =
	{
		.name = _("TM11"),
		.holdEffectParam = MOVE_MAGICAL_LEAF,
		.description = (u8*)&gBattleMoves[MOVE_MAGICAL_LEAF].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM12_SOLAR_BEAM] =
	{
		.name = _("TM12"),
		.holdEffectParam = MOVE_SOLAR_BEAM,
		.description = (u8*)&gBattleMoves[MOVE_SOLAR_BEAM].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM13_SOLAR_BLADE] =
	{
		.name = _("TM13"),
		.holdEffectParam = MOVE_SOLAR_BLADE,
		.description = (u8*)&gBattleMoves[MOVE_SOLAR_BLADE].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM14_FIRE_SPIN] =
	{
		.name = _("TM14"),
		.holdEffectParam = MOVE_FIRE_SPIN,
		.description = (u8*)&gBattleMoves[MOVE_FIRE_SPIN].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM15_THUNDER_WAVE] =
	{
		.name = _("TM15"),
		.holdEffectParam = MOVE_THUNDER_WAVE,
		.description = (u8*)&gBattleMoves[MOVE_THUNDER_WAVE].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM16_DIG] =
	{
		.name = _("TM16"),
		.holdEffectParam = MOVE_DIG,
		.description = (u8*)&gBattleMoves[MOVE_DIG].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM17_SCREECH] =
	{
		.name = _("TM17"),
		.holdEffectParam = MOVE_SCREECH,
		.description = (u8*)&gBattleMoves[MOVE_SCREECH].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM18_LIGHT_SCREEN] =
	{
		.name = _("TM18"),
		.holdEffectParam = MOVE_LIGHT_SCREEN,
		.description = (u8*)&gBattleMoves[MOVE_LIGHT_SCREEN].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM19_REFLECT] =
	{
		.name = _("TM19"),
		.holdEffectParam = MOVE_REFLECT,
		.description = (u8*)&gBattleMoves[MOVE_REFLECT].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM20_SAFEGUARD] =
	{
		.name = _("TM20"),
		.holdEffectParam = MOVE_SAFEGUARD,
		.description = (u8*)&gBattleMoves[MOVE_SAFEGUARD].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM21_SELF_DESTRUCT] =
	{
		.name = _("TM21"),
		.holdEffectParam = MOVE_SELF_DESTRUCT,
		.description = (u8*)&gBattleMoves[MOVE_SELF_DESTRUCT].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM22_REST] =
	{
		.name = _("TM22"),
		.holdEffectParam = MOVE_REST,
		.description = (u8*)&gBattleMoves[MOVE_REST].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM23_ROCK_SLIDE] =
	{
		.name = _("TM23"),
		.holdEffectParam = MOVE_ROCK_SLIDE,
		.description = (u8*)&gBattleMoves[MOVE_ROCK_SLIDE].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM24_THIEF] =
	{
		.name = _("TM24"),
		.holdEffectParam = MOVE_THIEF,
		.description = (u8*)&gBattleMoves[MOVE_THIEF].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM25_SNORE] =
	{
		.name = _("TM25"),
		.holdEffectParam = MOVE_SNORE,
		.description = (u8*)&gBattleMoves[MOVE_SNORE].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM26_PROTECT] =
	{
		.name = _("TM26"),
		.holdEffectParam = MOVE_PROTECT,
		.description = (u8*)&gBattleMoves[MOVE_PROTECT].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM27_SCARY_FACE] =
	{
		.name = _("TM27"),
		.holdEffectParam = MOVE_SCARY_FACE,
		.description = (u8*)&gBattleMoves[MOVE_SCARY_FACE].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM28_ICY_WIND] =
	{
		.name = _("TM28"),
		.holdEffectParam = MOVE_ICY_WIND,
		.description = (u8*)&gBattleMoves[MOVE_ICY_WIND].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM29_GIGA_DRAIN] =
	{
		.name = _("TM29"),
		.holdEffectParam = MOVE_GIGA_DRAIN,
		.description = (u8*)&gBattleMoves[MOVE_GIGA_DRAIN].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM30_CHARM] =
	{
		.name = _("TM30"),
		.holdEffectParam = MOVE_CHARM,
		.description = (u8*)&gBattleMoves[MOVE_CHARM].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM31_STEEL_WING] =
	{
		.name = _("TM31"),
		.holdEffectParam = MOVE_STEEL_WING,
		.description = (u8*)&gBattleMoves[MOVE_STEEL_WING].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM32_ATTRACT] =
	{
		.name = _("TM32"),
		.holdEffectParam = MOVE_ATTRACT,
		.description = (u8*)&gBattleMoves[MOVE_ATTRACT].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM33_SANDSTORM] =
	{
		.name = _("TM33"),
		.holdEffectParam = MOVE_SANDSTORM,
		.description = (u8*)&gBattleMoves[MOVE_SANDSTORM].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM34_RAIN_DANCE] =
	{
		.name = _("TM34"),
		.holdEffectParam = MOVE_RAIN_DANCE,
		.description = (u8*)&gBattleMoves[MOVE_RAIN_DANCE].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM35_SUNNY_DAY] =
	{
		.name = _("TM35"),
		.holdEffectParam = MOVE_SUNNY_DAY,
		.description = (u8*)&gBattleMoves[MOVE_SUNNY_DAY].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM36_HAIL] =
	{
		.name = _("TM36"),
		.holdEffectParam = MOVE_HAIL,
		.description = (u8*)&gBattleMoves[MOVE_HAIL].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM37_WHIRLPOOL] =
	{
		.name = _("TM37"),
		.holdEffectParam = MOVE_WHIRLPOOL,
		.description = (u8*)&gBattleMoves[MOVE_WHIRLPOOL].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM38_BEAT_UP] =
	{
		.name = _("TM38"),
		.holdEffectParam = MOVE_BEAT_UP,
		.description = (u8*)&gBattleMoves[MOVE_BEAT_UP].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM39_WILL_O_WISP] =
	{
		.name = _("TM39"),
		.holdEffectParam = MOVE_WILL_O_WISP,
		.description = (u8*)&gBattleMoves[MOVE_WILL_O_WISP].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM40_FACADE] =
	{
		.name = _("TM40"),
		.holdEffectParam = MOVE_FACADE,
		.description = (u8*)&gBattleMoves[MOVE_FACADE].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM41_SWIFT] =
	{
		.name = _("TM41"),
		.holdEffectParam = MOVE_SWIFT,
		.description = (u8*)&gBattleMoves[MOVE_SWIFT].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM42_HELPING_HAND] =
	{
		.name = _("TM42"),
		.holdEffectParam = MOVE_HELPING_HAND,
		.description = (u8*)&gBattleMoves[MOVE_HELPING_HAND].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM43_REVENGE] =
	{
		.name = _("TM43"),
		.holdEffectParam = MOVE_REVENGE,
		.description = (u8*)&gBattleMoves[MOVE_REVENGE].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM44_BRICK_BREAK] =
	{
		.name = _("TM44"),
		.holdEffectParam = MOVE_BRICK_BREAK,
		.description = (u8*)&gBattleMoves[MOVE_BRICK_BREAK].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM45_IMPRISON] =
	{
		.name = _("TM45"),
		.holdEffectParam = MOVE_IMPRISON,
		.description = (u8*)&gBattleMoves[MOVE_IMPRISON].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM46_DIVE] =
	{
		.name = _("TM46"),
		.holdEffectParam = MOVE_DIVE,
		.description = (u8*)&gBattleMoves[MOVE_DIVE].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM47_WEATHER_BALL] =
	{
		.name = _("TM47"),
		.holdEffectParam = MOVE_WEATHER_BALL,
		.description = (u8*)&gBattleMoves[MOVE_WEATHER_BALL].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM48_FAKE_TEARS] =
	{
		.name = _("TM48"),
		.holdEffectParam = MOVE_FAKE_TEARS,
		.description = (u8*)&gBattleMoves[MOVE_FAKE_TEARS].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM49_ROCK_TOMB] =
	{
		.name = _("TM49"),
		.holdEffectParam = MOVE_ROCK_TOMB,
		.description = (u8*)&gBattleMoves[MOVE_ROCK_TOMB].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM50_SAND_TOMB] =
	{
		.name = _("TM50"),
		.holdEffectParam = MOVE_SAND_TOMB,
		.description = (u8*)&gBattleMoves[MOVE_SAND_TOMB].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM51_BULLET_SEED] =
	{
		.name = _("TM51"),
		.holdEffectParam = MOVE_BULLET_SEED,
		.description = (u8*)&gBattleMoves[MOVE_BULLET_SEED].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM52_ICICLE_SPEAR] =
	{
		.name = _("TM52"),
		.holdEffectParam = MOVE_ICICLE_SPEAR,
		.description = (u8*)&gBattleMoves[MOVE_ICICLE_SPEAR].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM53_BOUNCE] =
	{
		.name = _("TM53"),
		.holdEffectParam = MOVE_BOUNCE,
		.description = (u8*)&gBattleMoves[MOVE_BOUNCE].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM54_MUD_SHOT] =
	{
		.name = _("TM54"),
		.holdEffectParam = MOVE_MUD_SHOT,
		.description = (u8*)&gBattleMoves[MOVE_MUD_SHOT].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM55_ROCK_BAST] =
	{
		.name = _("TM55"),
		.holdEffectParam = MOVE_ROCK_BAST,
		.description = (u8*)&gBattleMoves[MOVE_ROCK_BAST].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM56_BRINE] =
	{
		.name = _("TM56"),
		.holdEffectParam = MOVE_BRINE,
		.description = (u8*)&gBattleMoves[MOVE_BRINE].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM57_U_TURN] =
	{
		.name = _("TM57"),
		.holdEffectParam = MOVE_U_TURN,
		.description = (u8*)&gBattleMoves[MOVE_U_TURN].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM58_PAYBACK] =
	{
		.name = _("TM58"),
		.holdEffectParam = MOVE_PAYBACK,
		.description = (u8*)&gBattleMoves[MOVE_PAYBACK].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM59_ASSURANCE] =
	{
		.name = _("TM59"),
		.holdEffectParam = MOVE_ASSURANCE,
		.description = (u8*)&gBattleMoves[MOVE_ASSURANCE].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM60_FLING] =
	{
		.name = _("TM60"),
		.holdEffectParam = MOVE_FLING,
		.description = (u8*)&gBattleMoves[MOVE_FLING].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM61_POWER_SWAP] =
	{
		.name = _("TM61"),
		.holdEffectParam = MOVE_POWER_SWAP,
		.description = (u8*)&gBattleMoves[MOVE_POWER_SWAP].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM62_GUARD_SWAP] =
	{
		.name = _("TM62"),
		.holdEffectParam = MOVE_GUARD_SWAP,
		.description = (u8*)&gBattleMoves[MOVE_GUARD_SWAP].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM63_SPEED_SWAP] =
	{
		.name = _("TM63"),
		.holdEffectParam = MOVE_SPEED_SWAP,
		.description = (u8*)&gBattleMoves[MOVE_SPEED_SWAP].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM64_DRAIN_PUNCH] =
	{
		.name = _("TM64"),
		.holdEffectParam = MOVE_DRAIN_PUNCH,
		.description = (u8*)&gBattleMoves[MOVE_DRAIN_PUNCH].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM65_AVALANCHE] =
	{
		.name = _("TM65"),
		.holdEffectParam = MOVE_AVALANCHE,
		.description = (u8*)&gBattleMoves[MOVE_AVALANCHE].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM66_SHADOW_CLAW] =
	{
		.name = _("TM66"),
		.holdEffectParam = MOVE_SHADOW_CLAW,
		.description = (u8*)&gBattleMoves[MOVE_SHADOW_CLAW].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM67_THUNDER_FANG] =
	{
		.name = _("TM67"),
		.holdEffectParam = MOVE_THUNDER_FANG,
		.description = (u8*)&gBattleMoves[MOVE_THUNDER_FANG].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM68_ICE_FANG] =
	{
		.name = _("TM68"),
		.holdEffectParam = MOVE_ICE_FANG,
		.description = (u8*)&gBattleMoves[MOVE_ICE_FANG].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM69_FIRE_FANG] =
	{
		.name = _("TM69"),
		.holdEffectParam = MOVE_FIRE_FANG,
		.description = (u8*)&gBattleMoves[MOVE_FIRE_FANG].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM70_PSYCHO_CUT] =
	{
		.name = _("TM70"),
		.holdEffectParam = MOVE_PSYCHO_CUT,
		.description = (u8*)&gBattleMoves[MOVE_PSYCHO_CUT].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM71_TRICK_ROOM] =
	{
		.name = _("TM71"),
		.holdEffectParam = MOVE_TRICK_ROOM,
		.description = (u8*)&gBattleMoves[MOVE_TRICK_ROOM].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM72_WONDER_ROOM] =
	{
		.name = _("TM72"),
		.holdEffectParam = MOVE_WONDER_ROOM,
		.description = (u8*)&gBattleMoves[MOVE_WONDER_ROOM].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM73_MAGIC_ROOM] =
	{
		.name = _("TM73"),
		.holdEffectParam = MOVE_MAGIC_ROOM,
		.description = (u8*)&gBattleMoves[MOVE_MAGIC_ROOM].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM74_CROSS_POISON] =
	{
		.name = _("TM74"),
		.holdEffectParam = MOVE_CROSS_POISON,
		.description = (u8*)&gBattleMoves[MOVE_CROSS_POISON].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM75_VENOSHOCK] =
	{
		.name = _("TM75"),
		.holdEffectParam = MOVE_VENOSHOCK,
		.description = (u8*)&gBattleMoves[MOVE_VENOSHOCK].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM76_LOW_SWEEP] =
	{
		.name = _("TM76"),
		.holdEffectParam = MOVE_LOW_SWEEP,
		.description = (u8*)&gBattleMoves[MOVE_LOW_SWEEP].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM77_ROUND] =
	{
		.name = _("TM77"),
		.holdEffectParam = MOVE_ROUND,
		.description = (u8*)&gBattleMoves[MOVE_ROUND].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM78_HEX] =
	{
		.name = _("TM78"),
		.holdEffectParam = MOVE_HEX,
		.description = (u8*)&gBattleMoves[MOVE_HEX].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM79_ACROBATICS] =
	{
		.name = _("TM79"),
		.holdEffectParam = MOVE_ACROBATICS,
		.description = (u8*)&gBattleMoves[MOVE_ACROBATICS].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM80_RETALIATE] =
	{
		.name = _("TM80"),
		.holdEffectParam = MOVE_RETALIATE,
		.description = (u8*)&gBattleMoves[MOVE_RETALIATE].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM81_VOLT_SWITCH] =
	{
		.name = _("TM81"),
		.holdEffectParam = MOVE_VOLT_SWITCH,
		.description = (u8*)&gBattleMoves[MOVE_VOLT_SWITCH].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM82_BULLDOZE] =
	{
		.name = _("TM82"),
		.holdEffectParam = MOVE_BULLDOZE,
		.description = (u8*)&gBattleMoves[MOVE_BULLDOZE].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM83_ELECTROWEB] =
	{
		.name = _("TM83"),
		.holdEffectParam = MOVE_ELECTROWEB,
		.description = (u8*)&gBattleMoves[MOVE_ELECTROWEB].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM84_RAZOR_SHELL] =
	{
		.name = _("TM84"),
		.holdEffectParam = MOVE_RAZOR_SHELL,
		.description = (u8*)&gBattleMoves[MOVE_RAZOR_SHELL].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM85_TAIL_SLAP] =
	{
		.name = _("TM85"),
		.holdEffectParam = MOVE_TAIL_SLAP,
		.description = (u8*)&gBattleMoves[MOVE_TAIL_SLAP].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM86_SNARL] =
	{
		.name = _("TM86"),
		.holdEffectParam = MOVE_SNARL,
		.description = (u8*)&gBattleMoves[MOVE_SNARL].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM87_PHANTOM_FORCE] =
	{
		.name = _("TM87"),
		.holdEffectParam = MOVE_PHANTOM_FORCE,
		.description = (u8*)&gBattleMoves[MOVE_PHANTOM_FORCE].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM88_DRAINING_KISS] =
	{
		.name = _("TM88"),
		.holdEffectParam = MOVE_DRAINING_KISS,
		.description = (u8*)&gBattleMoves[MOVE_DRAINING_KISS].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM89_GRASSY_TERRAN] =
	{
		.name = _("TM89"),
		.holdEffectParam = MOVE_GRASSY_TERRAN,
		.description = (u8*)&gBattleMoves[MOVE_GRASSY_TERRAN].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM90_MISTY_TERRAIN] =
	{
		.name = _("TM90"),
		.holdEffectParam = MOVE_MISTY_TERRAIN,
		.description = (u8*)&gBattleMoves[MOVE_MISTY_TERRAIN].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM91_ELECTRIC_TERRAIN] =
	{
		.name = _("TM91"),
		.holdEffectParam = MOVE_ELECTRIC_TERRAIN,
		.description = (u8*)&gBattleMoves[MOVE_ELECTRIC_TERRAIN].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM92_PSYCHIC_TERRAIN] =
	{
		.name = _("TM92"),
		.holdEffectParam = MOVE_PSYCHIC_TERRAIN,
		.description = (u8*)&gBattleMoves[MOVE_PSYCHIC_TERRAIN].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM93_MYSTICAL_FIRE] =
	{
		.name = _("TM93"),
		.holdEffectParam = MOVE_MYSTICAL_FIRE,
		.description = (u8*)&gBattleMoves[MOVE_MYSTICAL_FIRE].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM94_EERIE_IMPULSE] =
	{
		.name = _("TM94"),
		.holdEffectParam = MOVE_EERIE_IMPULSE,
		.description = (u8*)&gBattleMoves[MOVE_EERIE_IMPULSE].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM95_FALSE_SWIPE] =
	{
		.name = _("TM95"),
		.holdEffectParam = MOVE_FALSE_SWIPE,
		.description = (u8*)&gBattleMoves[MOVE_FALSE_SWIPE].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM96_AIR_SLASH] =
	{
		.name = _("TM96"),
		.holdEffectParam = MOVE_AIR_SLASH,
		.description = (u8*)&gBattleMoves[MOVE_AIR_SLASH].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM97_SMART_STRIKE] =
	{
		.name = _("TM97"),
		.holdEffectParam = MOVE_SMART_STRIKE,
		.description = (u8*)&gBattleMoves[MOVE_SMART_STRIKE].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM98_BRUTAL_SWING] =
	{
		.name = _("TM98"),
		.holdEffectParam = MOVE_BRUTAL_SWING,
		.description = (u8*)&gBattleMoves[MOVE_BRUTAL_SWING].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM99_STOMPING_TANTRUM] =
	{
		.name = _("TM99"),
		.holdEffectParam = MOVE_STOMPING_TANTRUM,
		.description = (u8*)&gBattleMoves[MOVE_STOMPING_TANTRUM].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM100_BREAKING_SWIPE] =
	{
		.name = _("TM100"),
		.holdEffectParam = MOVE_BREAKING_SWIPE,
		.description = (u8*)&gBattleMoves[MOVE_BREAKING_SWIPE].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM101_CUT] =
	{
		.name = _("TM101"),
		.holdEffectParam = MOVE_CUT,
		.description = (u8*)&gBattleMoves[MOVE_CUT].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

	[ITEM_TM102_FLASH] =
	{
		.name = _("TM102"),
		.holdEffectParam = MOVE_FLASH,
		.description = (u8*)&gBattleMoves[MOVE_FLASH].description,
		.price = 3000,
		.pocket = POCKET_TM_CASE,
		.type = ITEM_TYPE_PARTY_MENU,
	},

#ifdef __INTELLISENSE__
};
#endif
