Route12_FishingHouse_Text_DoYouLikeToFish:: @ 819EFE0
    .string "I'm the FISHING GURU's younger\n"
    .string "brother.\p"
    .string "I simply looove fishing!\n"
    .string "I can't bear to go without.\p"
    .string "Tell me, do you like to fish?$"

Route12_FishingHouse_Text_TakeThisAndFish:: @ 819F05B
    .string "Grand! I like your style.\n"
    .string "I think we can be friends.\p"
    .string "Take this and fish, young friend!$"

Route12_FishingHouse_Text_ReceivedSuperRod:: @ 819F0B2
    .string "{PLAYER} received a SUPER ROD from\n"
    .string "the FISHING GURU's brother.$"

Route12_FishingHouse_Text_OhThatsDisappointing:: @ 819F1FA
    .string "Oh…\n"
    .string "That's so disappointing…$"

Route12_FishingHouse_Text_NoRoomForGift:: @ 819F494
    .string "Oh, no!\p"
    .string "I had a gift for you, but you have\n"
    .string "no room for it.$"

