#ifndef GUARD_BATTLE_MOVE_EFFECTS_H
#define GUARD_BATTLE_MOVE_EFFECTS_H

enum
{
	EFFECT_HIT,
	EFFECT_MULTI_HIT,
	EFFECT_OHKO,
	EFFECT_TWO_TURNS_ATTACK,
	EFFECT_USER_ATTACK_UP_2,
	EFFECT_RANDOM_SWITCH,
	EFFECT_SEMI_INVULNERABLE,
	EFFECT_RECOIL_IF_MISS,
	EFFECT_ACCURACY_DOWN,
	EFFECT_DEFENSE_DOWN,
	EFFECT_ATTACK_DOWN,
	EFFECT_SLEEP,
	EFFECT_CONFUSE,
	EFFECT_FIXED_DAMAGE,
	EFFECT_DISABLE_MOVE,
	EFFECT_SET_MIST,
	EFFECT_DAMAGE_BASED_TARGET_WEIGHT,
	EFFECT_COUNTER_ATTACK,
	EFFECT_USER_LEVEL_TO_DAMAGE,
	EFFECT_HIT_ABSORB,
	EFFECT_SET_SEEDED,
	EFFECT_USER_ATTACK_AND_SP_ATTACK_UP_2X_IN_SUNNY,
	EFFECT_SKIP_CHARGING_IN_WEATHER,
	EFFECT_SET_POISON,
	EFFECT_SET_PARALYZE,
	EFFECT_SPEED_DOWN_2,
	EFFECT_SET_TOXIC_POISON,
	EFFECT_ATTACK_UP,
	EFFECT_SPEED_UP_2,
	EFFECT_RAGE,
	EFFECT_TELEPORT,
	EFFECT_MIMIC_MOVE,
	EFFECT_DEFENSE_DOWN_2,
	EFFECT_EVASION_UP,
	EFFECT_RESTORE_HP,
	EFFECT_DEFENSE_UP,
	EFFECT_EVASION_UP_SET_MINIMIZE,
	EFFECT_DEFENSE_UP_SET_DEFENSE_CURL,
	EFFECT_DEFENSE_UP_2,
	EFFECT_SET_LIGHT_SCREEN,
	EFFECT_NORMALISE_FIELD_BUFFS,
	EFFECT_SET_REFLECT,
	EFFECT_FOCUS_ENERGY,
	EFFECT_BIDE,
	EFFECT_METRONOME,
	EFFECT_MIRROR_MOVE,
	EFFECT_EXPLOSION,
	EFFECT_SPECIAL_DEFENSE_UP_2,
	EFFECT_DREAM_EATER,
	EFFECT_NEVER_MISS_IN_WEATHER,
	EFFECT_TRANSFORM,
	EFFECT_PSYWAVE,
	EFFECT_DO_NOTHING,
	EFFECT_REST,
	EFFECT_CONVERSION,
	EFFECT_SUPER_FANG,
	EFFECT_SUBSTITUTE,
	EFFECT_SKETCH,
	EFFECT_TRIPLE_KICK,
	EFFECT_MEAN_LOOK,
	EFFECT_LOCK_ON,
	EFFECT_NIGHTMARE,
	EFFECT_SNORE,
	EFFECT_CURSE,
	EFFECT_FLAIL,
	EFFECT_CONVERSION_2,
	EFFECT_SPITE,
	EFFECT_PROTECT,
	EFFECT_BELLY_DRUM,
	EFFECT_SPIKES,
	EFFECT_FORESIGHT,
	EFFECT_DESTINY_BOND,
	EFFECT_PERISH_SONG,
	EFFECT_SET_WEATHER,
	EFFECT_ENDURE,
	EFFECT_ATTACK_DOWN_2,
	EFFECT_ROLLOUT,
	EFFECT_FALSE_SWIPE,
	EFFECT_SWAGGER,
	EFFECT_FURY_CUTTER,
	EFFECT_ATTRACT,
	EFFECT_SLEEP_TALK,
	EFFECT_HEAL_BELL,
	EFFECT_RETURN,
	EFFECT_PRESENT,
	EFFECT_FRUSTRATION,
	EFFECT_SAFEGUARD,
	EFFECT_PAIN_SPLIT,
	EFFECT_MAGNITUDE,
	EFFECT_BATON_PASS,
	EFFECT_ENCORE,
	EFFECT_PURSUIT,
	EFFECT_EVASION_DOWN_2,
	EFFECT_MORNING_SUN,
	EFFECT_HIDDEN_POWER,
	EFFECT_PSYCH_UP,
	EFFECT_FUTURE_SIGHT,
	EFFECT_BEAT_UP,
	EFFECT_FAKE_OUT,
	EFFECT_STOCKPILE,
	EFFECT_SPIT_UP,
	EFFECT_SWALLOW,
	EFFECT_TORMENT,
	EFFECT_FLATTER,
	EFFECT_WILL_O_WISP,
	EFFECT_MEMENTO,
	EFFECT_FACADE,
	EFFECT_FOCUS_PUNCH,
	EFFECT_CURE_STATUS1_FROM_ARG,
	EFFECT_FOLLOW_ME,
	EFFECT_NATURE_POWER,
	EFFECT_CHARGE,
	EFFECT_TAUNT,
	EFFECT_HELPING_HAND,
	EFFECT_TRICK,
	EFFECT_ROLE_PLAY,
	EFFECT_WISH,
	EFFECT_ASSIST,
	EFFECT_INGRAIN,
	EFFECT_MAGIC_COAT,
	EFFECT_RECYCLE,
	EFFECT_REVENGE,
	EFFECT_BRICK_BREAK,
	EFFECT_YAWN,
	EFFECT_KNOCK_OFF,
	EFFECT_ENDEAVOR,
	EFFECT_ERUPTION,
	EFFECT_SKILL_SWAP,
	EFFECT_IMPRISON,
	EFFECT_REFRESH,
	EFFECT_GRUDGE,
	EFFECT_SNATCH,
	EFFECT_CAMOUFLAGE,
	EFFECT_SPECIAL_ATTACK_UP_3,
	EFFECT_MUD_SPORT,
	EFFECT_WEATHER_BALL,
	EFFECT_SPECIAL_DEFENSE_DOWN_2,
	EFFECT_TICKLE,
	EFFECT_COSMIC_POWER,
	EFFECT_HOWL,
	EFFECT_BULK_UP,
	EFFECT_WATER_SPORT,
	EFFECT_CALM_MIND,
	EFFECT_DRAGON_DANCE,
	EFFECT_ROOST,
	EFFECT_GRAVITY,
	EFFECT_MIRACLE_EYE,
	EFFECT_GYRO_BALL,
	EFFECT_HEALING_WISH,
	EFFECT_BRINE,
	EFFECT_NATURAL_GIFT,
	EFFECT_BUG_BITE,
	EFFECT_TAILWIND,
	EFFECT_ACUPRESSURE,
	EFFECT_HIT_ESCAPE,
	EFFECT_PAYBACK,
	EFFECT_ASSURANCE,
	EFFECT_EMBARGO,
	EFFECT_FLING,
	EFFECT_PSYCHO_SHIFT,
	EFFECT_TRUMP_CARD,
	EFFECT_HEAL_BLOCK,
	EFFECT_WRING_OUT,
	EFFECT_POWER_TRICK,
	EFFECT_GASTRO_ACID,
	EFFECT_LUCKY_CHANT,
	EFFECT_ME_FIRST,
	EFFECT_COPYCAT,
	EFFECT_POWER_SWAP,
	EFFECT_GUARD_SWAP,
	EFFECT_PUNISHMENT,
	EFFECT_LAST_RESORT,
	EFFECT_SET_ABILITY,
	EFFECT_SUCKER_PUNCH,
	EFFECT_TOXIC_SPIKES,
	EFFECT_HEART_SWAP,
	EFFECTS_COUNT,
};





#define EFFECT_SPEED_UP 12
#define EFFECT_SPECIAL_ATTACK_UP 13
#define EFFECT_SPECIAL_DEFENSE_UP 14
#define EFFECT_ACCURACY_UP 15
#define EFFECT_SPEED_DOWN 20
#define EFFECT_SPECIAL_ATTACK_DOWN 21  // unused
#define EFFECT_SPECIAL_DEFENSE_DOWN 22  // unused
#define EFFECT_EVASION_DOWN 24
#define EFFECT_SPECIAL_ATTACK_UP_2 53
#define EFFECT_ACCURACY_UP_2 55
#define EFFECT_EVASION_UP_2 56
#define EFFECT_SPECIAL_ATTACK_DOWN_2 61
#define EFFECT_ACCURACY_DOWN_2 63
#define EFFECT_EVASION_DOWN_HIT 74
#define EFFECT_FLINCH_MINIMIZE_HIT 150
#define EFFECT_HEX                          217
#define EFFECT_ACROBATICS                   220
#define EFFECT_HEAT_CRASH                   221
#define EFFECT_STORED_POWER                 223
#define EFFECT_ELECTRO_BALL                 224
#define EFFECT_ECHOED_VOICE                 226
#define EFFECT_ROUND                        228
#define EFFECT_VENOSHOCK                    230
#define EFFECT_RETALIATE                    231
#define EFFECT_BULLDOZE                     232
#define EFFECT_FOUL_PLAY                    233
#define EFFECT_PSYSHOCK                     234
#define EFFECT_AQUA_RING                    240
#define EFFECT_TRICK_ROOM                   241
#define EFFECT_WONDER_ROOM                  242
#define EFFECT_MAGIC_ROOM                   243
#define EFFECT_MAGNET_RISE                  244
#define EFFECT_STEALTH_ROCK                 247
#define EFFECT_TELEKINESIS                  248
#define EFFECT_POWER_SPLIT                  252
#define EFFECT_GUARD_SPLIT                  253
#define EFFECT_STICKY_WEB                   254
#define EFFECT_SPECIAL_DEFENSE_DOWN_HIT_2   258
#define EFFECT_SIMPLE_BEAM                  259
#define EFFECT_ENTRAINMENT                  260
#define EFFECT_HEAL_PULSE                   261
#define EFFECT_QUASH                        262
#define EFFECT_ION_DELUGE                   263
#define EFFECT_FREEZE_DRY                   264
#define EFFECT_TOPSY_TURVY                  265
#define EFFECT_MISTY_TERRAIN                266
#define EFFECT_GRASSY_TERRAIN               267
#define EFFECT_ELECTRIC_TERRAIN             268
#define EFFECT_PSYCHIC_TERRAIN              269
#define EFFECT_ATTACK_ACCURACY_UP           270
#define EFFECT_ATTACK_SPATK_UP              271
#define EFFECT_HURRICANE                    272
#define EFFECT_TWO_TYPED_MOVE               273
#define EFFECT_SPEED_UP_HIT                 275
#define EFFECT_QUIVER_DANCE                 276
#define EFFECT_COIL                         277
#define EFFECT_ELECTRIFY                    278
#define EFFECT_SCALD                        279
#define EFFECT_REFLECT_TYPE                 280
#define EFFECT_SOAK                         281
#define EFFECT_FLINCH_STATUS                286
#define EFFECT_SHELL_SMASH                  288
#define EFFECT_SHIFT_GEAR                   289
#define EFFECT_DEFENSE_UP_3                 290
#define EFFECT_NOBLE_ROAR                   291
#define EFFECT_VENOM_DRENCH                 292
#define EFFECT_TOXIC_THREAD                 293
#define EFFECT_CLEAR_SMOG                   294
#define EFFECT_HIT_SWITCH_TARGET            295
#define EFFECT_FINAL_GAMBIT                 296
#define EFFECT_CHANGE_TYPE_ON_ITEM          297
#define EFFECT_AUTOTOMIZE                   298
#define EFFECT_DEFOG                        300
#define EFFECT_HIT_ENEMY_HEAL_ALLY          301
#define EFFECT_SMACK_DOWN                   302
#define EFFECT_SYNCHRONOISE                 303
#define EFFECT_FLAME_BURST                  306
#define EFFECT_AFTER_YOU                    307
#define EFFECT_BESTOW                       308
#define EFFECT_ROTOTILLER                   309
#define EFFECT_FLOWER_SHIELD                310
#define EFFECT_HIT_PREVENT_ESCAPE           311
#define EFFECT_SPEED_SWAP                   312
#define EFFECT_DEFENSE_UP2_HIT              313
#define EFFECT_REVELATION_DANCE             314
#define EFFECT_AURORA_VEIL                  315
#define EFFECT_THIRD_TYPE                   316
#define EFFECT_SPARKLING_ARIA               318
#define EFFECT_AROMATIC_MIST                320
#define EFFECT_POWDER                       321
#define EFFECT_SP_ATTACK_UP_HIT             322
#define EFFECT_BELCH                        323
#define EFFECT_PARTING_SHOT                 324
#define EFFECT_SPECTRAL_THIEF               325
#define EFFECT_V_CREATE                     326
#define EFFECT_MAT_BLOCK                    327
#define EFFECT_STOMPING_TANTRUM             328
#define EFFECT_CORE_ENFORCER                329
#define EFFECT_INSTRUCT                     330
#define EFFECT_THROAT_CHOP                  331
#define EFFECT_LASER_FOCUS                  332
#define EFFECT_MAGNETIC_FLUX                333
#define EFFECT_GEAR_UP                      334
#define EFFECT_INCINERATE                   335
#define EFFECT_STRENGTH_SAP                 337
#define EFFECT_MIND_BLOWN                   338
#define EFFECT_PURIFY                       339
#define EFFECT_BURN_UP                      340
#define EFFECT_SHORE_UP                     341
#define EFFECT_GEOMANCY                     342
#define EFFECT_FAIRY_LOCK                   343
#define EFFECT_ALLY_SWITCH                  344
#define EFFECT_RELIC_SONG                   345
#define EFFECT_ATTACKER_DEFENSE_DOWN_HIT    346
#define EFFECT_BODY_PRESS                   347
#define EFFECT_EERIE_SPELL                  348
#define EFFECT_JUNGLE_HEALING               349
#define EFFECT_COACHING                     350
#define EFFECT_LASH_OUT                     351
#define EFFECT_GRASSY_GLIDE                 352
#define EFFECT_REMOVE_TERRAIN               353
#define EFFECT_DYNAMAX_DOUBLE_DMG           354
#define EFFECT_DECORATE                     355
#define EFFECT_SNIPE_SHOT                   356
#define EFFECT_STUFF_CHEEKS                 358
#define EFFECT_GRAV_APPLE                   359
#define EFFECT_EVASION_UP_HIT               360
#define EFFECT_GLITZY_GLOW                  361
#define EFFECT_BADDY_BAD                    362
#define EFFECT_SAPPY_SEED                   363
#define EFFECT_FREEZY_FROST                 364
#define EFFECT_SPARKLY_SWIRL                365
#define EFFECT_PLASMA_FISTS                 366
#define EFFECT_HYPERSPACE_FURY              367
#define EFFECT_AURA_WHEEL                   368
#define EFFECT_PHOTON_GEYSER                369
#define EFFECT_SHELL_SIDE_ARM               370
#define EFFECT_TERRAIN_PULSE                371
#define EFFECT_JAW_LOCK                     372
#define EFFECT_NO_RETREAT                   373
#define EFFECT_TAR_SHOT                     374
#define EFFECT_POLTERGEIST                  375
#define EFFECT_OCTOLOCK                     376
#define EFFECT_CLANGOROUS_SOUL              377
#define EFFECT_BOLT_BEAK                    378
#define EFFECT_SKY_DROP                     379
#define EFFECT_EXPANDING_FORCE              380
#define EFFECT_SCALE_SHOT                   381
#define EFFECT_METEOR_BEAM                  382
#define EFFECT_RISING_VOLTAGE               383
#define EFFECT_BEAK_BLAST                   384
#define EFFECT_COURT_CHANGE                 385
#define EFFECT_STEEL_BEAM                   386
#define EFFECT_EXTREME_EVOBOOST             387
#define EFFECT_DAMAGE_SET_TERRAIN           388 // genesis supernova
#define EFFECT_DARK_VOID                    389
#define EFFECT_PLEDGE                       390
#define EFFECT_FUSION_COMBO                 393
#define EFFECT_ALWAYS_CRIT 397
#define EFFECT_CAPTIVATE 399
#define EFFECT_FELL_STINGER 400
#define EFFECT_INFERNAL_PARADE 401
#define EFFECT_PLACEHOLDER 0

#include "constants/move_effect_bytes.h"

#endif  // GUARD_BATTLE_MOVE_EFFECTS_H
