#ifndef GUARD_BATTLE_TRANSITION_H
#define GUARD_BATTLE_TRANSITION_H

#include "global.h"

enum
{
    MUGSHOT_COLOR_NONE,
    MUGSHOT_COLOR_PURPLE,
    MUGSHOT_COLOR_GREEN,
    MUGSHOT_COLOR_PINK,
    MUGSHOT_COLOR_BUE,
    MUGSHOT_COLOR_YELLOW,
    MUGSHOT_COLOR_COUNT
};

enum
{
    B_TRANSITION_BLUR,
    B_TRANSITION_DISTORTED_WAVE,
    B_TRANSITION_HORIZONTAL_CORRUGATE,
    B_TRANSITION_BIG_POKEBALL,
    B_TRANSITION_REGICE,
    B_TRANSITION_REGISTEEL,
    B_TRANSITION_REGIROCK,
    B_TRANSITION_SLIDING_POKEBALLS,
    B_TRANSITION_CLOCKWISE_BLACKFADE,
    B_TRANSITION_FULLSCREEN_WAVE,
    B_TRANSITION_BLACK_WAVE_TO_RIGHT,
    B_TRANSITION_SLICED_SCREEN,
    B_TRANSITION_WHITEFADE_IN_STRIPES,
    B_TRANSITION_GRID_SQUARES,
    B_TRANSITION_BLACK_DOODLES,
    B_TRANSITION_MUGSHOT,
    B_TRANSITION_ANTI_CLOCKWISE_SPIRAL,
    B_TRANSITION_SHRED_SPLIT,
    B_TRANSITION_KYOGRE,
    B_TRANSITION_GROUDON,
    B_TRANSITION_BLACKHOLE,
    B_TRANSITION_BLACKHOLE_PULSATE,
    B_TRANSITION_RAYQUAZA,
    B_TRANSITION_RECTANGULAR_SPIRAL,
};

void BT_StartOnField(u32 transitionId);
bool32 BT_IsDone(void);

#endif // GUARD_BATTLE_TRANSITION_H
