#ifndef GUARD_TRAINER_SLIDE_H
#define GUARD_TRAINER_SLIDE_H

#include "global.h"

enum
{
	TRAINER_SLIDE_FIRST_MON_SEND_OUT,
	TRAINER_SLIDE_FIRST_MON_DOWN,
	TRAINER_SLIDE_LAST_MON_SEND_OUT,
	TRAINER_SLIDE_LAST_MON_LOW_HP,
	TRAINER_SLIDE_FIRST_SUPER_EFFECTIVE_HIT_TAKEN,
	TRAINER_SLIDE_FIRST_CRITICAL_TAKEN,
	TRAINER_SLIDE_MEGA_EVOLUTION,
	TRAINER_SLIDE_Z_MOVE,
	TRAINER_SLIDE_DYNAMAX,
	TRAINER_SLIDE_TERASTALIZATION,
};

bool8 ShouldDoTrainerSlide(u8 battlerId, u8 caseId);

#endif // GUARD_TRAINER_SLIDE_H
